In [35]:
import csv # for writing dataframes to csv
import random # for making a random choice
import os # for scanning directories
import itertools
from collections import Counter
from string import ascii_uppercase


import kintypes as kt # bringing large lists of kin types into the namespace
import math # for calculating logs
import pandas as pd
import numpy as np
import scipy.stats
import statistics
import re
from tqdm import tqdm

from Levenshtein import distance as lvs_dist

# Internal co-selection

Internal co-selection refers to a process of kin term evolution whereby terminological changes in one part of the paradigm co-occur with changes in related parts of the paradigm, increasing the predictive structure of the paradigm.

In this notebook, we will build simulations to investigate the robustness of this tendency cross-linguistically, using data from Kinbank, a global database of kin terminology. 

We will measure predictive structure between two generations as the symmetric conditional entropy between each of those generations given the other, i.e. H(X|Y) + H(Y|X).


### 1. Extract kin terminology from Kinbank

First, let's actually load our data in.

In [36]:
kinbank = pd.read_csv('../../data/kinbank.csv')

# get all glottocodes
all_glottocodes = list(set(kinbank['Glottocode']))

['siri1273',
 'slav1253',
 'caro1242',
 'kumy1244',
 'nepa1254',
 'wail1244',
 'nort2942',
 'siee1239',
 'umpi1239',
 'kumb1268',
 'urdu1245',
 'dehu1237',
 'siwa1245',
 'pohn1238',
 'eyak1241',
 'ling1263',
 'beka1241',
 'usar1243',
 'kama1365',
 'tido1248',
 'bign1238',
 'wang1288',
 'here1253',
 'suru1262',
 'lauj1238',
 'mido1240',
 'urav1235',
 'nyam1271',
 'bung1269',
 'bier1244',
 'mara1378',
 'mari1426',
 'urip1239',
 'wels1247',
 'toca1235',
 'budz1238',
 'tswa1253',
 'ital1282',
 'renn1242',
 'tami1289',
 'tupi1274',
 'otoo1241',
 'limi1242',
 'aman1265',
 'ponc1241',
 'wyan1247',
 'taus1251',
 'duma1253',
 'yulp1239',
 'hunz1247',
 'mber1257',
 'chip1262',
 'raro1241',
 'yami1254',
 'tuam1242',
 'cent2142',
 'para1312',
 'touo1238',
 'udmu1245',
 'nort2836',
 'tiko1237',
 'toho1245',
 'wata1253',
 'cota1241',
 'panj1256',
 'taji1246',
 'saar1237',
 'hiww1237',
 'ngon1269',
 'mali1284',
 'movi1243',
 'nort2944',
 'band1339',
 'gimi1243',
 'east1436',
 'yugu1249',
 'enap1235',
 'nort2672',
 'lolo1264',
 'afri1274',
 'suku1261',
 'plai1258',
 'bino1237',
 'kaza1248',
 'alam1246',
 'umir1236',
 'agob1244',
 'iban1264',
 'telu1262',
 'cent2092',
 'hanu1241',
 'bann1248',
 'ship1254',
 'guny1241',
 'waya1270',
 'yaka1269',
 'nali1244',
 'soga1242',
 'lava1239',
 'bezh1248',
 'stan1323',
 'luba1249',
 'sout2977',
 'cogu1240',
 'sana1298',
 'achi1257',
 'fris1239',
 'west2392',
 'yali1257',
 'onto1237',
 'hinu1240',
 'moks1248',
 'nort2845',
 'yeru1240',
 'kodi1247',
 'idaa1241',
 'olda1245',
 'pali1274',
 'aghu1253',
 'chem1251',
 'lauu1247',
 'waru1266',
 'bitt1240',
 'qawa1238',
 'batl1238',
 'tson1249',
 'tzel1254',
 'ojib1241',
 'djin1251',
 'bala1314',
 'tuva1244',
 'east2443',
 'west2615',
 'unua1237',
 'cent2090',
 'kili1267',
 'dier1241',
 'kwom1262',
 'vera1241',
 'tsog1243',
 'pitj1243',
 'tupi1273',
 'west2369',
 'fort1240',
 'marw1260',
 'kuni1267',
 'sara1326',
 'hida1246',
 'binu1244',
 'pamp1243',
 'mose1249',
 'nort2702',
 'yaoo1241',
 'baub1235',
 'bala1310',
 'nese1235',
 'darl1243',
 'nort2966',
 'pitt1247',
 'puel1244',
 'loni1238',
 'yama1264',
 'lama1277',
 'bela1254',
 'tuba1279',
 'jing1260',
 'prak1243',
 'aser1237',
 'edop1238',
 'mina1268',
 'mohe1244',
 'gada1258',
 'sate1242',
 'tapi1254',
 'tlin1245',
 'teiw1235',
 'lund1266',
 'sout2949',
 'gugu1255',
 'sang1331',
 'peor1238',
 'dako1258',
 'bagv1239',
 'cayu1262',
 'oldh1241',
 'chic1270',
 'wall1257',
 'yele1255',
 'chac1249',
 'naka1262',
 'poko1261',
 'tehu1242',
 'crow1244',
 'sout2959',
 'gela1263',
 'auuu1241',
 'mian1254',
 'utes1238',
 'huic1243',
 'aust1271',
 'macu1259',
 'nort2641',
 'serb1264',
 'carn1240',
 'nort2877',
 'khan1273',
 'gami1243',
 'cint1239',
 'nucl1479',
 'koya1251',
 'ngam1265',
 'sout1528',
 'ford1242',
 'xara1244',
 'algo1255',
 'tosk1239',
 'waff1241',
 'hunz1248',
 'rita1239',
 'stan1289',
 'east2295',
 'bilu1245',
 'badi1246',
 'cupe1243',
 'wang1287',
 'mesk1242',
 'murr1258',
 'epen1239',
 'ngal1292',
 'keii1239',
 'cebu1242',
 'kaba1285',
 'kans1243',
 'uppe1274',
 'raka1237',
 'anga1316',
 'mong1338',
 'vari1239',
 'akla1241',
 'komb1273',
 'kaiw1246',
 'watu1246',
 'sout2975',
 'mode1248',
 'ache1246',
 'roma1327',
 'mala1479',
 'yaka1277',
 'gale1259',
 'meko1237',
 'dupa1235',
 'yuki1243',
 'sout2856',
 'meru1245',
 'chuu1238',
 'wong1246',
 'bata1285',
 'baur1253',
 'port1286',
 'tiri1258',
 'gwii1239',
 'meta1238',
 'meke1243',
 'stan1288',
 'wayu1243',
 'sout2859',
 'sout2865',
 'suki1245',
 'wang1291',
 'chip1261',
 'west2559',
 'kalk1246',
 'chav1241',
 'luva1239',
 'gand1255',
 'giry1241',
 'mpuo1241',
 'naas1242',
 'alya1239',
 'gane1237',
 'penr1237',
 'waim1253',
 'nucl1301',
 'waru1265',
 'kari1311',
 'soge1235',
 'tele1256',
 'tusc1257',
 'mort1237',
 'hupa1239',
 'mbla1238',
 'sard1257',
 'slov1269',
 'weda1240',
 'dogr1252',
 'dond1249',
 'elam1244',
 'west2632',
 'kaya1329',
 'osse1245',
 'mund1330',
 'otta1242',
 'ghod1238',
 'serr1255',
 'punu1239',
 'bush1247',
 'modo1249',
 'olal1237',
 'yaqu1251',
 'lonw1238',
 'blag1240',
 'veps1250',
 'kare1337',
 'mash1270',
 'biri1256',
 'arab1267',
 'cent2101',
 'myen1241',
 'nort2951',
 'spok1245',
 'mala1464',
 'para1311',
 'mang1402',
 'pawn1254',
 'west2618',
 'roto1249',
 'gali1262',
 'west2560',
 'kuan1248',
 'cube1242',
 'moro1287',
 'kara1476',
 'kuka1246',
 'keya1238',
 'hehe1240',
 'yano1262',
 'baru1267',
 'kwai1243',
 'sang1330',
 'paiw1248',
 'jeha1242',
 'gunt1241',
 'selk1253',
 'suun1239',
 'west2622',
 'saaa1241',
 'yans1239',
 'toto1304',
 'nucl1454',
 'mala1468',
 'skol1241',
 'foii1241',
 'kuii1252',
 'nort2916',
 'dobu1241',
 'prus1238',
 'atam1239',
 'akka1240',
 'mang1408',
 'port1283',
 'oldr1238',
 'quec1382',
 'djam1256',
 'marq1246',
 'sher1255',
 'fore1265',
 'aniw1237',
 'huar1255',
 'stan1290',
 'woli1241',
 'indo1316',
 'tuyu1244',
 'dout1240',
 'nucl1310',
 'male1293',
 'pang1290',
 'paez1247',
 'nuuc1236',
 'goth1244',
 'waiw1244',
 'cent2084',
 'tubu1240',
 'clas1250',
 'muss1246',
 'vure1239',
 'choc1276',
 'osag1243',
 'sout2976',
 'mara1385',
 'umbu1257',
 'rade1240',
 'kwas1243',
 'burm1266',
 'luis1253',
 'taba1266',
 'coca1259',
 'puin1248',
 'mafe1237',
 'mikm1235',
 'neha1247',
 'rapa1244',
 'wipi1242',
 'bind1236',
 'slov1268',
 'yamd1240',
 'indo1317',
 'nina1238',
 'port1285',
 'wari1268',
 'comm1246',
 'paco1243',
 'dand1238',
 'nucl1653',
 'kaon1241',
 'gunw1252',
 'samo1305',
 'icel1247',
 'nucl1235',
 'mudu1242',
 'song1299',
 'tokh1242',
 'vend1245',
 'wall1255',
 'maor1246',
 'nyul1247',
 'ahin1234',
 'yelm1242',
 'cusc1236',
 'pala1344',
 'whit1269',
 'emau1237',
 'kagu1239',
 'achu1249',
 'sion1247',
 'biha1245',
 'sake1247',
 'lala1264',
 'dual1243',
 'amha1245',
 'adan1251',
 'hili1240',
 'yavi1244',
 'bung1264',
 'bata1289',
 'huli1244',
 'chek1238',
 'nucl1649',
 'emer1243',
 'yuca1254',
 'ancu1238',
 'oldw1239',
 'oriy1255',
 'cree1272',
 'kuuk1238',
 'koro1312',
 'laua1243',
 'mara1404',
 'tola1247',
 'laur1250',
 'sout2866',
 'mask1242',
 'iauu1242',
 'mung1271',
 'waja1257',
 'yind1247',
 'dari1249',
 'nucl1597',
 'fass1245',
 'phen1239',
 'pirr1240',
 'wawo1239',
 'bali1278',
 'coco1261',
 'ekon1238',
 'kiow1264',
 'oldn1244',
 'thao1240',
 'inan1242',
 'bali1275',
 'kele1257',
 'lake1258',
 'tupi1239',
 'sira1266',
 'bont1247',
 'homs1234',
 'kwer1261',
 'sout2969',
 'wiyo1248',
 'dadi1250',
 'trum1247',
 'guaj1256',
 'tokh1243',
 'niua1240',
 'meri1244',
 'thay1249',
 'kuvi1243',
 'toor1238',
 'ngar1287',
 'yura1255',
 'gogo1263',
 'west2515',
 'gang1267',
 'zigu1242',
 'mori1268',
 'sawa1247',
 'mung1266',
 'norw1259',
 'muru1266',
 'taje1237',
 'sika1262',
 'maib1239',
 'ende1235',
 'bret1244',
 'jude1256',
 'futu1245',
 'iyoj1235',
 'ding1239',
 'mapu1245',
 'mudb1240',
 'kaur1267',
 'oduu1239',
 'fiji1243',
 'binj1250',
 'guri1247',
 'bwai1243',
 'komc1235',
 'sula1245',
 'iliu1237',
 'toba1269',
 'brul1239',
 'tali1262',
 'akhv1239',
 'tivv1240',
 'west2599',
 'guma1253',
 'arak1252',
 'maba1278',
 'latv1249',
 'kuku1273',
 'west2555',
 'haya1250',
 'deho1238',
 'igna1246',
 'tuba1278',
 'mang1405',
 'seke1241',
 'dege1248',
 'namb1293',
 'zaba1237',
 'erav1244',
 'umaj1240',
 'area1240',
 'warl1254',
 'yaki1237',
 'lubu1242',
 'tong1325',
 'east2328',
 'tokp1240',
 'mara1399',
 'komi1268',
 'avat1244',
 'reja1240',
 'alan1249',
 'chib1270',
 'biak1248',
 'west2386',
 'kosa1249',
 'temb1276',
 'ampi1237',
 'orok1266',
 'kala1399',
 'merl1237',
 'iowa1245',
 'lamm1241',
 'mesc1238',
 'dhar1248',
 'wanm1242',
 'mand1446',
 'kada1286',
 'menu1237',
 'okan1243',
 'kuli1254',
 'bari1288',
 'yagw1240',
 'tons1240',
 'east2516',
 'lewo1242',
 'nang1262',
 'bafi1243',
 'bulg1262',
 'nort2961',
 'ngaa1240',
 'kode1237',
 'ayor1240',
 'wapi1253',
 'bayu1240',
 'mori1269',
 'erzy1239',
 'tula1253',
 'sang1321',
 'koro1311',
 'nort2839',
 'waia1242',
 'saaa1240',
 'isna1241',
 'pile1238',
 'tsaa1242',
 'winn1245',
 'kama1373',
 'hind1269',
 'dyir1250',
 'bloo1239',
 'lele1267',
 'chur1257',
 'wich1264',
 'djin1253',
 'dzon1239',
 'nage1237',
 'mada1284',
 'esto1258',
 'ekar1243',
 'gilb1244',
 'kyak1244',
 'bats1242',
 'yaka1272',
 'urak1238',
 'yuwa1244',
 'gusi1247',
 'moni1261',
 'gras1249',
 'cham1312',
 'guar1292',
 'mana1288',
 'lako1247',
 'ingu1240',
 'nucl1594',
 'komo1260',
 'sout2857',
 'pata1260',
 'anam1249',
 'amis1246',
 'laiw1239',
 'pila1245',
 'tetu1246',
 'kwam1252',
 'kada1242',
 'luxe1241',
 'maca1260',
 'mang1401',
 'maha1287',
 'buin1247',
 'baff1241',
 'mokp1239',
 'lahn1241',
 'wikm1247',
 'damp1237',
 'kick1244',
 'tomi1243',
 'atay1247',
 'hewa1241',
 'baho1237',
 'boun1245',
 'kiku1240',
 'stan1295',
 'tenh1241',
 'wath1238',
 'flin1247',
 'wira1265',
 'puka1242',
 'kira1248',
 'nucl1633',
 'niue1239',
 'hidd1238',
 'corn1251',
 'anci1242',
 'lang1320',
 'buku1249',
 'koda1255',
 'aves1237',
 'giga1238',
 'jaru1254',
 'shin1265',
 'yaum1237',
 'mart1256',
 'sout2869',
 'taia1239',
 'kala1397',
 'seta1246',
 'nort2847',
 'yand1253',
 'pwoo1239',
 'tahi1242',
 'toma1248',
 'suku1259',
 'ibal1244',
 'kanu1280',
 'buru1303',
 'kash1280',
 'waru1264',
 'baca1243',
 'lete1241',
 'waim1255',
 'lugu1238',
 'nort2677',
 'nucl1458',
 'kett1243',
 'loto1240',
 'vaoo1237',
 'cruz1243',
 'toke1240',
 'kuma1280',
 'sata1237',
 'lubu1243',
 'olde1238',
 'kemt1242',
 'mbya1239',
 'hawa1245',
 'warr1257',
 'bera1259',
 'yinh1234',
 'opat1246',
 'paus1244',
 'nene1249',
 'adny1235',
 'maga1262',
 'gwic1235',
 'mait1250',
 'mbal1257',
 'vlax1238',
 'nyaw1247',
 'mang1407',
 'onon1246',
 'shan1293',
 'marg1253',
 'mala1494',
 'narr1259',
 'zuni1245',
 'onaa1245',
 'beng1280',
 'nort2697',
 'nort2671',
 'neme1244',
 'mani1235',
 'malo1243',
 'utee1244',
 'kunz1244',
 'tolo1259',
 'colo1249',
 'mace1250',
 'ulaw1237',
 'atch1238',
 'matu1261',
 'kete1254',
 'toab1237',
 'nava1243',
 'ngul1246',
 'mono1275',
 'oldi1245',
 'karr1236',
 'sind1272',
 'cofa1242',
 'bila1255',
 'coma1245',
 'iwam1256',
 'moha1258',
 'song1300',
 'onei1249',
 'cent1972',
 'rapa1245',
 'east2447',
 'sini1245',
 'term1237',
 'xibe1242',
 'makl1246',
 'owaa1237',
 'pulu1242',
 'kuma1273',
 'luba1250',
 'waor1240',
 'ingr1248',
 'pota1247',
 'buka1261',
 'mere1242',
 'puyu1239',
 'niva1238',
 'seri1257',
 'bari1297',
 'stan1293',
 'temi1247',
 'arik1262',
 'nama1266',
 'raha1237',
 'chen1255',
 'casi1235',
 'taki1248',
 'baro1253',
 'bilb1241',
 'muns1251',
 'sund1252',
 'taku1257',
 'tomb1243',
 'wapp1239',
 'malu1245',
 'yany1243',
 'agua1253',
 'lena1238',
 'atta1244',
 'uabm1237',
 'maee1241',
 'bamu1253',
 'juru1256',
 'wiwi1237',
 'nort2952',
 'chep1245',
 'lipa1241',
 'litz1237',
 'paic1239',
 'lisu1250',
 'nyor1246',
 'sate1243',
 'cayu1261',
 'wamb1258',
 'butm1237',
 'nort2938',
 'jama1262',
 'rian1263',
 'sgaw1245',
 'nenn1238',
 'tial1239',
 'abui1241',
 'leng1262',
 'nort1551',
 'bann1247',
 'torr1261',
 'mana1295',
 'ling1265',
 'cham1309',
 'fipa1238',
 'tana1285',
 'rata1245',
 'sawi1257',
 'jica1244',
 'yomb1244',
 'yabe1254',
 'yidi1250',
 'bunu1267',
 'ivat1242',
 'mung1270',
 'wang1290',
 'anda1281',
 'dutc1256',
 'sang1333',
 'nyak1260',
 'yadh1237',
 'polc1243',
 'trin1274',
 'copp1244',
 'mini1251',
 'sans1269',
 'taum1237',
 'osse1243',
 'bard1254',
 'zulu1248',
 'balo1260',
 'bemb1257',
 'sene1264',
 'nucl1305',
 'ifug1247',
 'guja1252',
 'kipu1237',
 'yiry1245',
 'maan1238',
 'midd1317',
 'kara1499',
 'noga1249',
 'poli1260',
 'shaw1249',
 'anei1239',
 'cent2089',
 'imbo1238',
 'gupa1247',
 'vinm1237',
 'kank1243',
 'kere1283',
 'sibe1248',
 'kari1304',
 'haus1257',
 'awia1234',
 'gond1265',
 'czec1258',
 'arch1244',
 'malg1242',
 'budu1248',
 'moco1246',
 'onob1238',
 'swed1254',
 'nucl1460',
 'mars1254',
 'tuca1252',
 'buhi1245',
 'ngar1235',
 'icar1234',
 'lati1261',
 'phai1238',
 'mayo1264',
 'lamb1271',
 'wira1262',
 'kilm1241',
 'komn1238',
 'turu1249',
 'avar1256',
 'bend1258',
 'araw1273',
 'hano1246',
 'kawa1283',
 'krio1252',
 'assi1247',
 'sons1242',
 'mouk1240',
 'nort2954',
 'tong1329',
 'inxo1238',
 'mako1251',
 'kama1370',
 'cent2131',
 'matt1238',
 'midd1343',
 'yuro1248',
 'dani1285',
 'kota1274',
 'hitt1242',
 'kaur1271',
 'alba1267',
 'woge1237',
 'iban1267',
 'pagu1249',
 'yala1262',
 'shas1239',
 'lard1243',
 'ngan1291',
 'shon1251',
 'tady1237',
 'seki1238',
 'hopi1249',
 'iray1237',
 'kaya1318',
 'meno1252',
 'masa1299',
 'kart1247',
 'eude1234',
 'taga1270',
 'nucl1643',
 'pima1248',
 'cher1273',
 'ngad1258',
 'mono1273',
 'nyan1301',
 'saka1287',
 'lare1249',
 'savo1255',
 'beri1254',
 'kute1249',
 'ngun1274',
 'komb1274',
 'suzh1234',
 'high1278',
 'umbu1258',
 'nhan1238',
 'kuot1243',
 'iris1253',
 'vili1238',
 'wers1238',
 'tali1259',
 'woiw1237',
 'paam1238',
 'kora1295',
 'lamo1244',
 'rovi1238',
 'sumb1240',
 'chok1245',
 'daka1243',
 'assa1263',
 'rotu1241',
 'rout1237',
 'karo1304',
 'tang1347',
 'pash1269',
 'pume1238',
 'tong1321',
 'kima1246',
 'nama1268',
 'balu1257',
 'chim1301',
 'lozi1239',
 'tore1237',
 'chir1284',
 'neng1238',
 'japa1256',
 'boan1243',
 'ocea1241',
 ...]

`get_kin_terms()` uses a language's Glottocode to extract a dictionary of kin terms for that language from thr `kinbank` data.

In [37]:
def get_kin_terms(glottocode):
    language_data = kinbank[kinbank['Glottocode'] == glottocode]

    kinterms = {}

    for row in range(len(language_data)): # for each row of the data
        term = list(language_data['Form'])[row] # get the kin term
        relative = list(language_data['Parameter_ID'])[row] # and kin type stored in that row
        try:
            kinterms[relative] = term.lower() # add them to dict
        except:
            pass

    return kinterms

### 2. Pair up parent and child terms.

We're interested in the predictive structure between the kin terms in Generation 0 (Ego's generaiton) and Generation +1 (Ego's parents' generation).

We want create a data structure that pairs up parent types with the corresponding child types. This is because we're interested in whether kinship systems maintain patterns of terminological distinctions and mergers across these two generations, so we will need to know which parent terms 'go with' which child terms.

`get_pairs()` takes a kinship system as input, and outputs a list of tuples. The first element in the tuple is the parent term, the second is the corresponding child term. 

But for our calculations, we'll still need to know which terms belong to which generation. Luckily, we know that the 0th element in each tuple is from Ego's parents' generation and the 1st element is from Ego's generation. So we can happily split these tuples down the middle and populate two lists with the terms. `split_pairs()` takes a list of pairs and sorts it into terms that belong to Ego's generation and terms that belong to Ego's parents' generation.

In [38]:
def get_pairs(ks: dict, pairs:list) -> list:
    pairs_of_terms = []
    pairs_of_relatives = []

    for pair in pairs:
        if pair[0] in ks and pair[1] in ks:
            pairs_of_terms.append((ks[pair[0]],ks[pair[1]]))
            pairs_of_relatives.append((pair[0],pair[1]))
                            
    return pairs_of_terms,pairs_of_relatives

In [39]:
def split_pairs(pairs: list) -> list:
    gn = []
    gn1 = []
    for pair in pairs:
        gn.append(pair[1])
        gn1.append(pair[0])
    
    return gn,gn1

### 3. Calculate probabilities

To calculate entropy, we need a probability distribution over the terms in one single generation of a kinship system. So let's start with a function that can calculate the probability of a particular term.

Given a term and the full list of terms in the same generation, `probability()` counts how many times that term exists in `generation` and divides that by the total length of `generation`.

To calculate **conditional entropy** between the two generations of our system, we will need not only the probabilities of terms in a generation, but also the **joint probabilities** of every pair of terms across those two generations. In other words, we need to calculate the probabilities of our `get_pairs` output.

Given two terms, `joint_probability()` counts how many pairs made of those two terms exist in `pairs`, then divides that by the total length of `pairs`.

In [40]:
def probability(term: str, generation: list) -> float:
    return generation.count(term)/len(generation)

In [41]:
def joint_probability(term1: str, term2: str, pairs:list) -> float:
    pair = (term1,term2)
    
    return pairs.count(pair)/len(pairs)

In [16]:
def joint_probability_distribution(ks):
    
    terms,relatives = get_pairs(ks,kt.ics_pairs)
    
#     print(terms)
    
    parents = ['mM','fM','mF','fF']
        
    probs = {k:v for (k,v) in zip(terms, [0 for i in range(len(terms))])}  
    
    parent_pairs = 0
    parent_terms = []
    
    for pair in range(len(relatives)):
        if relatives[pair][0] in parents:
            parent_pairs += 1
            parent_terms.append(terms[pair][0])

    for i in range(len(terms)):
        if relatives[i][0] not in parents:
            probs[terms[i]] += 1/(len(relatives) - (parent_pairs/2))
        else:
            probs[terms[i]] += (1/(len(relatives) - (parent_pairs/2))) / 2

    return probs

### 4. Calculating symmetric conditional entropy 

Conditional entropy of Y given X is defined as

$$
H(Y|X) = -\sum_{x \in X,y \in Y}p(x,y) log_2 {p(x,y) \over p(x)}
$$

or in English, the inverse sum over two distributions Y and X of the probability of each y * the log probability of each y given x.

Conditional entropy is the amount of information needed to describe the outcome of a random variable Y given that we already know the value of another random variable X.

To calculate it, we need the joint probability of each pair (given by `joint_probability()`) and the probability of one member of that pair (given by `probability()`). We can then calculate the conditional probability of parent term given child term as the joint probability of those terms over the probability of the parent term.

`conditional_entropy()` iterates over all pairs to output the conditional entropy of Ego's generation given Ego's parents' generation.

In [17]:
# calculate the entropy of terms in generation X given the terms in generation Y
def conditional_entropy(ks,x,y):
    """Calculate the summed entropy of all pairs of kin terms in the system. 
    X and Y indicate which variable conditions which."""
    entropy = 0
    
    pairs_of_terms,relatives = get_pairs(ks,kt.ics_pairs)
    g0,g1 = split_pairs(pairs_of_terms)
    
    probabilities = joint_probability_distribution(ks)
    
    for parent,child in set(pairs_of_terms): # for each pair of terms; x = parent, y = child
        p_xy = probabilities[parent,child] # calculate their joint probability
        p_ch = probability(child,g0) # calculate the probability of the child term in its generation
        p_par = probability(parent,g1) # calculate the probability of the parent term in its generation
        
        if x == 0: # if we want ce of child term given parent term (H(child|parent)):
            entropy += p_xy * math.log2(p_xy/p_par)
        if x == 1: # if we want ce of parent term given child term (H(parent|child)):
            entropy += p_xy * math.log2(p_xy/p_ch)
            
    return round(-entropy,5)

In [15]:
conditional_entropy(get_kin_terms('stan1293'),0,1)

0.13697

Since our measure takes the sum of conditional entropy 'in both directions', we'll need a function that calculates that too.

In [46]:
def predictive_structure(ks):
    """Calculate the sum of H(X|Y) and H(Y|X)."""
    
    hxy = conditional_entropy(ks,0,1)
    hyx = conditional_entropy(ks,1,0)
    
    return hxy + hyx

In [19]:
predictive_structure(get_kin_terms('stan1293'))

1.07394

For each language, calculate its symmetric conditional entropy and save to a dataframe.

In [4]:
def calculate_PS(filename):
    df = []
    codes = []
            
    for code in tqdm(all_glottocodes):

        language = list(kinbank[kinbank['Glottocode'] == code]['Name'])[0] # get the language name
        family = list(kinbank[kinbank['Glottocode'] == code]['Family'])[0] # get the family 

        if code not in codes:
            codes.append(code)

            ks = get_kin_terms(code)

            pairs,relatives = get_pairs(ks,kt.ics_pairs)

            if pairs: # if pairs is not empty

                results = {}
                results['language'] = language
                results['language_family'] = family
                results['code'] = code
                results['simulation'] = 'N'
                results['predictive_structure'] = predictive_structure(ks)

                df.append(results)
        
    pd.DataFrame(df).to_csv('data/' + filename + '.csv',index=False)
    
    return pd.DataFrame(df)

In [5]:
# calculate_PS('typological_data')

## Simulating kinship systems

To investigate whether kinship systems have more predictive structure than chance, we can build a random baseline for each language to serve as a point of comparison.

To do this, we will take each language in our dataset, and randomly scramble which terms go with which relatives (within generations). This will randomise the syncretisms within the paradigm, breaking any predictable structure built by the internal co-selection process, while maintaining the amount of variation across the system overall.
 
We take the following steps:

1. Extract the kinship system of a language from kinbank.
2. Filter the two generations we are interested in.
3. Randomly reassign the kinship terms to new types.
4. Repeat the process 1000 times for each language.

We already have the infrastructure for the first two! `get_kin_terms()`,  `get_pairs()` and `split_pairs()` will do this for us. So let's skip to 3, and write a function that randomises which terms form pairs, assuming that we have already extracted the kinship system and filtered the relevant pairs.

### 3. Randomly rearrange kin terms

`kintypes.py` also contains a list of which kin types are in which generation, which we can use to split a kinship system by generation.

In [7]:
def split_ks(ks):
    """Split the kinship system into two dictionaries where keys are relatives and values are terms.
    One dict is the generation N terms, one is the generation N+1 terms."""
    gn = {}
    gn1 = {}
    for entry in ks:
        if entry in kt.generation_n:
            gn[entry] = ks[entry]
        elif entry in kt.generation_n1:
            gn1[entry] = ks[entry]
        else:
            pass

    return gn,gn1        

def shuffle_ks(ks):
    """Split the kinship system, shuffle the Generation N terms, then reassign keys to values."""
    gn_terms = []
    gn,gn1 = split_ks(ks)
    
    new_ks = {}
    
    for term in gn:
        gn_terms.append(gn[term])

    random.shuffle(gn_terms)
    
    for i in range(len(gn)):
        key = list(gn.keys())[i]
        new_ks[key] = gn_terms[i]
        

    return {**new_ks,**gn1}

Finally, let's run the simulation - shuffle each kinship system 1000 times, measure the predictive structure of each permutation, and calculate a z-score per language that tells us how extreme the true predictive structure of the system is.

In [18]:
def simulate_PS(filename: str, filename2: str, times: int):
    df = []
    z_df = []
    codes = []
        
    for code in tqdm(all_glottocodes):
        language = list(kinbank[kinbank['Glottocode'] == code]['Name'])[0] # get the language name
        family = list(kinbank[kinbank['Glottocode'] == code]['Family'])[0] # get the family 


        if code not in codes:
            codes.append(code)

            ks = get_kin_terms(code)

            true_value = predictive_structure(ks)
            
            simulated_values = []

            for i in range(times):
                sim = shuffle_ks(ks)
                pairs,relatives = get_pairs(sim,kt.ics_pairs)
                
                if pairs:
                    
                    ps = predictive_structure(sim)
                    simulated_values.append(ps)
                    
                    results = {}
                    results['language'] = language
                    results['language_family'] = family
                    results['code'] = code
                    results['simulation'] = 'Y'
                    results['predictive_structure'] = ps
                    results['true_value'] = true_value

                    df.append(results)
            
            if pairs:
                mean = np.mean(simulated_values)
                sd = np.std(simulated_values)

                z_results = {}
                z_results['language'] = language
                z_results['language_family'] = family
                z_results['code'] = code
                z_results['true_value'] = true_value
                z_results['simulated_mean'] = mean
                z_results['simulated_sd'] = sd
                z_results['z'] = (true_value - mean) / sd

                z_df.append(z_results)
                
    
    pd.DataFrame(df).to_csv('data/' + filename + '.csv',index=False)
    pd.DataFrame(z_df).to_csv('data/' + filename2 + '.csv',index=False)

    
    return pd.DataFrame(z_df)

In [9]:
# simulate_PS('simulated_data','predictive_structure_z',1000)

## Edit Distance

Predictive structure may be an artefact of compositionality - where kin terms are compositional between parent and child terms, as in Kurdish, predictive structure follows naturally. Here, we test whether kin term compositionality and predictive structure are correlated.

We measure compositionality as the average normalised Levenshtein edit distance between parent and child terms. To calculate this, we measure the edit distance between each pair of parent and child terms.

Note: we are not just comparing all labels for all meanings, but rather all labels for all categories! This prevents languages being penalised for being compositional but not having e.g. all unique labels across aunts and uncles.

So the first thing we need to do is work out which categories each language has, and who are the children of which category members.

In [10]:
def category_based_pairs(g1):
    
    # work out which g1 relatives share a term
    
    relatives = list(g1.keys())
    terms = list(g1.values())

    categories = []

    for term in terms:
        cat = []
        indices = [index for index, element in enumerate(terms) if element == term]
        for index in indices:
            cat.append(relatives[index])
        categories.append(cat)

    categories = [list(i) for i in set(map(tuple, categories))]
    
    # work out which children should share a term on this basis
    
    child_cats = []

    for cat in categories:
        new_category = []
        for individual in cat:
            for pair in kt.ics_pairs:
                if pair[0] == individual:
                    new_category.append(pair[1])
        child_cats.append(new_category)
        
    # and make a new list of parent-child pairs that should have equal semantic distance
    
    new_pairs = []
    
    for i in range(len(categories)):
        new_pairs += list(itertools.product(categories[i], child_cats[i]))
        
    return new_pairs

Now we need a function that spits out an array of edit distances for our language.

In [11]:
def edit_distance(g0,g1):
    edit_dists = []

    for relative1 in g0:
        term1 = g0[relative1]
        for relative2 in g1:
            data = {}
            term2 = g1[relative2]
            
            if relative1 == relative2:
                pass
            
            else:
            
                if len(term1) > 0 and len(term2) > 0:
                    dist = lvs_dist(term1,term2)/len(max(term1,term2))
                    edit_dists.append(dist)
                else:
                    pass

    return edit_dists

Together with our kinship system shuffling infrastructure, we can calculate a z-score for these edit distance measures - do kinship systems have extremely low edit distance? In our analysis, we look at how this corresponds with extremely low predictive structure.

In [13]:
def simulate_edit_distance(filename,times):
    df = []
    
    codes = []
        
    for code in tqdm(all_glottocodes):

        language = list(kinbank[kinbank['Glottocode'] == code]['Name'])[0] # get the language name
        family = list(kinbank[kinbank['Glottocode'] == code]['Family'])[0] # get the family 

        data = {}

        if code not in codes:
            codes.append(code)

            ks = get_kin_terms(code)
            pairs,relatives = get_pairs(ks)
            
            avgs = []

            for pair in pairs:
                try:
                    ed = lvs_dist(pair[0],pair[1]) / max(len(pair[0]),len(pair[1]))
                    avgs.append(ed)
                except:
                    continue

            try:            
                true_mean = np.mean(avgs)

            except:
                continue

            sim_avgs = []
            for i in range(times):
                sim = shuffle_ks(ks)
                sim_pairs = get_pairs(sim)[0]

                distances = []
                for pair in sim_pairs:
                    try:
                        sim_ed = lvs_dist(pair[0],pair[1]) / max(len(pair[0]),len(pair[1]))
                        distances.append(sim_ed)
                    except:
                        continue
                        
                sim_avgs.append(np.mean(distances))


            sim_mean = np.mean(sim_avgs)
            sd = np.std(sim_avgs)

            z = (true_mean - sim_mean) / sd

            data['language'] = language
            data['family'] = family
            data['code'] = code
            data['true_value'] = true_mean
            data['simulated_mean'] = sim_mean
            data['sd'] = sd
            data['z'] = z

            df.append(data)
                
    pd.DataFrame(df).to_csv('../data/new_measure/' + filename + '.csv',index=False)

    return pd.DataFrame(df)

In [14]:
# simulate_edit_distance('edit_distance',1000)

# Reviewer concerns

Reviewer 2 suggested that string length might be affecting our measure of compositionality. Here, we calculate the edit distance between randomly generated strings of the same length as in the real languages, so we can check that the edit distance of randomly generated strings is sufficiently different from the edit distance of the actual languages in our dataset.

In [ ]:
def replace_terms_with_strings(ks):
    
    new_ks = {}
        
    for key in ks:
        value = ks[key]
        new_ks[key] = ''.join([random.choice(ascii_uppercase) for i in range(len(value))])

    return new_ks

In [12]:
def random_edit_distance(filename,times):
    df = []
    
    codes = []
        
    for code in tqdm(all_glottocodes):

        language = list(kinbank[kinbank['Glottocode'] == code]['Name'])[0] # get the language name
        family = list(kinbank[kinbank['Glottocode'] == code]['Family'])[0] # get the family 

        data = {}

        if code not in codes:
            codes.append(code)

            true_ks = get_kin_terms(code)
            ks = replace_terms_with_strings(true_ks)
            pairs,relatives = get_pairs(ks)
            
            avgs = []

            for pair in pairs:
                try:
                    ed = lvs_dist(pair[0],pair[1]) / max(len(pair[0]),len(pair[1]))
                    avgs.append(ed)
                except:
                    continue

            try:            
                true_mean = np.mean(avgs)

            except:
                continue

            sim_avgs = []
            for i in range(times):
                sim = shuffle_ks(ks)
                sim_pairs = get_pairs(sim)[0]

                distances = []
                for pair in sim_pairs:
                    try:
                        sim_ed = lvs_dist(pair[0],pair[1]) / max(len(pair[0]),len(pair[1]))
                        distances.append(sim_ed)
                    except:
                        continue
                        
                sim_avgs.append(np.mean(distances))


            sim_mean = np.mean(sim_avgs)
            sd = np.std(sim_avgs)

            z = (true_mean - sim_mean) / sd

            data['language'] = language
            data['family'] = family
            data['code'] = code
            data['true_value'] = true_mean
            data['simulated_mean'] = sim_mean
            data['sd'] = sd
            data['z'] = z

            df.append(data)
                
#     pd.DataFrame(df).to_csv('data/' + filename + '.csv',index=False)

    return pd.DataFrame(df)

In [ ]:
# random_edit_distance('edit_distance_random_strings',1000)

### Appendix D

Reviewer 2 suggested that we check what this analysis looks like with the restricted number of kin types that were present in the experiment. It may be that our results are not so strong compared to the true data even when we control for the number of kin types.

That said, real languages are still free to vary much more than our experiment data, since the terms for some individuals are fixed in the experiment.

In [33]:
exp_pairs = [

# parents and siblings

('mM','mB'), ('mF','mB'),
('mM','mZ'), ('mF','mZ'),

# nuncles and cousins

# mother's brother

('mMeB','mMBS'),('mMeB','mMBD'),

# mother's sister
    
('mMeZ','mMZS'),('mMeZ','mMZD'),
    
# father's brother
    
('mFeB','mFBS'),('mFeB','mFBD'),
    
# father's sister

('mFeZ','mFZS'),('mFeZ','mFZD')

]

We need to update our `split_ks` functions slightly so that they use this smaller version of the meaning space. 

**We also need to make sure `get_pairs()` is using the `exp_pairs` array (inside the `simulate_PS()`, `joint_probability_distribution()` and `conditional_entropy()` functions).** This is set to `kt.ics_pairs` for the original analysis.

In [15]:
gn = ['mB','mZ','mMBS','mMBD','mMZS','mMZD','mFBS','mFBD','mFZS','mFZD']
gn1 = ['mM','mF','mMeB','mMeZ','mFeB','mFeZ']

def split_ks(ks):
    g0 = {}
    g1 = {}
    for entry in ks:
        if entry in gn:
            g0[entry] = ks[entry]
        elif entry in gn1:
            g1[entry] = ks[entry]
        else:
            pass
        
#     print(g0,g1)

    return g0,g1

In [59]:
# simulate_PS('small_sim','small_sim_z',1000)

  0%|▎                                                                                | 4/1127 [00:00<01:26, 13.03it/s]C:\Users\s1604058\AppData\Local\Temp\ipykernel_3516\950065671.py:52: RuntimeWarning: invalid value encountered in scalar divide
  z_results['z'] = (true_value - mean) / sd
100%|██████████████████████████████████████████████████████████████████████████████| 1127/1127 [01:35<00:00, 11.75it/s]

,language,language_family,code,true_value,simulated_mean,simulated_sd,z
0,Sirionó,Tupian,siri1273,0.94287,1.974595,0.284843,-3.622085
1,Kumyk,Turkic,kumy1244,1.07394,1.890741,0.161912,-5.044737
2,Nepali,Indo-European,nepa1254,0.33008,0.330080,0.000000,NaN
3,Eel River Athabaskan,NaN,wail1244,2.00000,1.354000,0.935245,0.690728
4,North Slavey,NaN,nort2942,3.00000,2.162000,0.541993,1.546147
...,...,...,...,...,...,...,...
733,Mwotlap,Austronesian,motl1237,3.00000,2.184000,0.525494,1.552824
734,Eastern Bolivian Guaraní,Tupian,east2555,1.87394,2.272715,0.133060,-2.996948
735,Northern Mansi,Uralic,mans1258,1.87394,2.271513,0.134958,-2.945906
736,Waropen,Austronesian,waro1242,1.00000,1.000000,0.000000,NaN
737,Kunzakh,Nakh-Daghestanian,kunz1243,1.47394,2.078271,0.210372,-2.872675

### Appendix C: Access to data affects predictiveness score

Checking whether languages with fewer kin types in their dataset

In [19]:
def count_data(ks):
    relatives = []
    for relative in ks:
#         print(relative)
        if relative in kt.generation_n or relative in kt.generation_n1:
            relatives.append(relative)
    
    return len(relatives)

In [20]:
def data_count(filename: str):
    df = []
    
    codes = []
        
    for code in tqdm(all_glottocodes):

        language = list(kinbank[kinbank['Glottocode'] == code]['Name'])[0] # get the language name
        family = list(kinbank[kinbank['Glottocode'] == code]['Family'])[0] # get the family 

        data = {}

        if code not in codes:
            codes.append(code)

            ks = get_kin_terms(code)
#             print(ks)

            length = count_data(ks)

            results = {}
            results['language'] = language
            results['language_family'] = family
            results['code'] = code
            results['data_length'] = length

            df.append(results)
        
    pd.DataFrame(df).to_csv('../data/new_measure/' + filename + '.csv',index=False)
    
    return pd.DataFrame(df)

In [25]:
data_count('data_count')

100%|██████████████████████████████████████████████████████████████████████████████| 1127/1127 [00:35<00:00, 31.48it/s]

        language    language_family      code  data_length
0        Sirionó             Tupian  siri1273           56
1          Slave                NaN  slav1253           28
2     Carolinian       Austronesian  caro1242            2
3          Kumyk             Turkic  kumy1244           60
4         Nepali      Indo-European  nepa1254           34
...          ...                ...       ...          ...
1122     Waropen       Austronesian  waro1242           34
1123       Tetum       Austronesian  tetu1245           32
1124      Piegan              Algic  pieg1239           28
1125       Meyah                NaN  meya1236           28
1126     Kunzakh  Nakh-Daghestanian  kunz1243           60

[1127 rows x 4 columns]