In [1]:
import random
import math
import os
import pandas as pd
import numpy as np
from tqdm import tqdm

C:\Users\s1604058\AppData\Roaming\Python\Python39\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\s1604058\AppData\Roaming\Python\Python39\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.4' currently installed).
  from pandas.core import (

In this notebook, we take the raw data produced by our participants at test and extract the final kinship systems they produced. From there, we can calculate the symmetric conditional entropy of their final languages, create simulated baselines against which we compare their true behaviour, and measure their 'accuracy': how often they made predictive generalisations.

First, let's import the dataframe containing all participants' responses.

In [2]:
all_data = pd.read_csv('data/all_data.csv')

And get a list of random IDs associated with each participant.

In [3]:
random_ids = list(set(list(all_data['random_id'])))

Next, we want to extract participants' data individually, so we can look at their final languages.

In [4]:
# get one dataframe

def get_ppt_df(ppt_id):
   
    df = all_data.drop(all_data[all_data.random_id != ppt_id].index)
    
    df.drop(index = df.index[0])
    
    # remove any rows where participants pressed the 'done' and 'undo' buttons
    df = df.drop(df[df.done == 1].index)
    df = df.drop(df[df.undo == 1].index)
    
    # filter any participant who failed more than 1 catch trial
    if len(df[df.catch_failed == True]) < 2:
        return df

And to extract the kinship system they produced into a dictionary format:

In [5]:
referents = ['mzd','mzs','mbd','mbs','z','b','fzd','fzs','fbd','fbs']

In [6]:
def get_ppt_ks(df):
        
    ks = {} # an empty dict to start
    
    choices = []
    
    for i in range(len(df)): # for each line in their dataframe
        relative = df['selectee'].values[i] # find out who the referent was for that trial
        
        if df['trial_type'].values[i] == 'catch': # ignore if it's a catch trial
            continue

        else:
            term = df['selection'].values[i] # find out what term they selected
            ks[relative] = term # add referent and term to dict
    
    # find out what the given G0 terms were for this participant and add referent and term to dict
    generaliser1 = df['generaliser1'].values[0] 
    ks[generaliser1] = df['generaliser1_term'].values[0]
    generaliser2 = df['generaliser2'].values[0]
    ks[generaliser2] = df['generaliser2_term'].values[0]
    
    return ks

Now we have a record of what labels our participants chose, let's build up the rest of the kinship system (i.e. what terms they were given in G+1, which are the same for every participant but not saved in the dataframe.)

In [7]:
# these lists represent the eight trial types in the experiment
# individuals in the same sublist share a term
language_types = [[['m'],['f'],['mz','mb','fz','fb']], # Type I
                [['m'],['f'],['mz','mb'],['fz','fb'],['z','b']], # Type IIside
                [['m'],['f'],['mz','fz'],['mb','fb'],['z','b']], # Type II gen
                [['m'],['f'],['mz','fb'],['mb','fz'],['z','b']], # Type II opp
                [['m'],['f'],['mz','mb','fz'],['fb'],['z','b']], # Type III fb
                [['m'],['f'],['mz','mb','fb'],['fz'],['z','b']], # Type III fz
                [['m'],['f'],['mz','fz','fb'],['mb'],['z','b']], # Type III mb
                [['m'],['f'],['fz','mb','fb'],['mz'],['z','b']]] # Type III mz

# given a participants' responses, add the rest of the kinship system to dict
def make_ks(language_type,ks):
    """ A language_type is a list of lists representing how terms are spread across the space of relatives. 
    Every relative in a sublist shares a term. This function takes that spread and adds to an existing dictionary where
    keys are relatives and values are terms."""
            
    for group in language_type: # for each group of relatives that share a term
        for relative in group: # for each relative in that group
            ks[relative] = str(language_type.index(group)) # assign them a value equal to the group's index (i.e. a unique 'term')

    return ks

## Proportion of predictive generalisations

For each participant, let's code how often they made a generalisation that increased the predictive structure of the system *at that point*. i.e., we want to assign them 1 if their choice led to the lowest symmetric conditional entropy of all four choices, or 0 if it led to a higher symmetric conditional entropy.

First, we need infrastructure for calculate symmetric conditional entropy.

In [8]:
# the pairs of individuals (Parents and CHildren) whose labels we expect to be informative of each other
pch_pairs = [('mz','mzd'),('mz','mzs'),('mb','mbd'),('mb','mbs'),('m','z'),('m','b'),('f','z'),('f','b'),('fz','fzd'),('fz','fzs'),('fb','fbd'),('fb','fbs')]

In [9]:
# pair up individuals for joint probability

def get_pairs(ks: dict) -> list:
    pairs_of_terms = []
    pairs_of_relatives = []

    for pair in pch_pairs:
        if pair[0] in ks and pair[1] in ks:
            pairs_of_terms.append((ks[pair[0]],ks[pair[1]]))
            pairs_of_relatives.append((pair[0],pair[1]))
                            
    return pairs_of_terms,pairs_of_relatives

In [10]:
# split the pairs to work out which generation the term belongs to

def split_pairs(pairs_of_terms: list) -> list:
    """This function takes the pairs_of_terms variable created by get_pairs and splits the terms up so we know what
    generation they belong to. We know the 0th element in the pair will always be the parent and the 1st the child."""
    
    gn = []
    gn1 = []
    for pair in pairs_of_terms: # for each pair of terms
        gn.append(pair[1]) # append the 1st element in the pair to the Generation N list
        gn1.append(pair[0]) # append the 0th element in the pair to the Generation N+1 list
    
    return gn,gn1

In [30]:
def probability(term: str, generation: list) -> float:
    """Calculate the probability of a term given how common it is in its generation."""
    return generation.count(term)/len(generation)

def joint_probability(term1: str, term2: str, pairs: list) -> float:
    """Calculate the joint probability of two terms - how commonly they are paired together."""
    pair = (term1,term2)
    return pairs.count(pair)/len(pairs)

def joint_probability_distribution(ks):
    
    terms,relatives = get_pairs(ks)
        
    probs = {k:v for (k,v) in zip(terms, [0 for i in range(len(terms))])}  
    

    for i in range(len(terms)):
            probs[terms[i]] += 1/len(relatives)

    return probs

In [82]:
# calculate the entropy of terms in generation X given the terms in generation Y
def conditional_entropy(ks,x,y):
    """Calculate the summed entropy of all pairs of kin terms in the system. 
    X and Y indicate which variable conditions which."""
    entropy = 0
    
    pairs_of_terms,relatives = get_pairs(ks)
    g0,g1 = split_pairs(pairs_of_terms)
    
    probabilities = joint_probability_distribution(ks)
    
    for parent,child in set(pairs_of_terms): # for each pair of terms; x = parent, y = child
        p_xy = probabilities[parent,child] # calculate their joint probability
        p_ch = probability(child,g0) # calculate the probability of the child term in its generation
        p_par = probability(parent,g1) # calculate the probability of the parent term in its generation
        
        if x == 0: # if we want ce of child term given parent term (H(child|parent)):
            entropy += p_xy * math.log2(round(p_xy/p_par,3))
#             print('conditional prob of ' + child + ' given ' + parent)
#             print(round(p_xy/p_par,3))
#             print('entropy = ', -p_xy * math.log2(round(p_xy/p_par,3)))
        if x == 1: # if we want ce of parent term given child term (H(parent|child)):
            entropy += p_xy * math.log2(round(p_xy/p_ch,3))
#             print('conditional prob of ' + parent + ' given ' + child)
#             print(round(p_xy/p_ch,3))
#             print('entropy = ', -p_xy * math.log2(round(p_xy/p_ch,3)))
            
    return round(-entropy,5)

In [83]:
def predictive_structure(ks):
    """Calculate the sum of H(X|Y) and H(Y|X)."""
    
    hxy = conditional_entropy(ks,0,1)
    hyx = conditional_entropy(ks,1,0)
    
    return hxy + hyx

In [84]:
ks = {
    'm': 'mama',
    'f': 'ise',
    'fb': 'isento',
    'fz': 'isenkati',
    'mb': 'ongundwe',
    'mz': 'nyinento',
    'fbs':'munyanya',
    'fbd':'munyanya',
    'fzs':'mwhiwha',
    'fzd':'mwhiwha',
    'mbs':'nyinarumi',
    'mbd': 'nyinento',
    'mzs': 'omwana',
    'mzd': 'omwana',
    'z': 'mukuru',
    'b': 'mukuru'
}

In [85]:
predictive_structure(ks)

0.5

In [86]:
test_df = get_ppt_df(random_ids[3])

[test_df['generaliser1'].iloc[0],test_df['generaliser2'].iloc[0]]

# system_df['generaliser1'].iloc[0],system_df['generaliser2'].iloc[0]

['mzs', 'fbd']

Now, let's save a dataframe that codes each participants' responses for whether or not they generalised predictively.

In [87]:
def accuracy(filename):
    
    data = []
    
    for ppt_id in random_ids:
        df = get_ppt_df(ppt_id)
        
        try:
            df.empty == False
        except:
            continue
            
        for system in [0,1,2,3,4,5,6,7]:
            
            system_df = df.drop(df[df.system != system].index)
            
            if system_df.empty:
                continue
                
            else:
                
#                 print(system_df)

                if True in set(system_df['catch_failed']): # if they failed a catch trial, don't look at their data
                    pass

                else:
                    generalisers = [system_df['generaliser1'].iloc[0],system_df['generaliser2'].iloc[0]]

                    gen_terms = [system_df['generaliser1_term'].iloc[0],system_df['generaliser2_term'].iloc[0]]

                    ks = {}

                    ks[generalisers[0]] = gen_terms[0] # set the first and second generalisers
                    ks[generalisers[1]] = gen_terms[1]

                    choices = [gen_terms[0],gen_terms[1]]

                    ks = make_ks(language_types[system],ks) # fill the kinship system as the participants saw it to begin with

                    for row in range(len(system_df)):

                        chosen_term = system_df['selection'].values[row]

                        selectee = system_df['selectee'].values[row]

                        ks[selectee] = chosen_term  # for each choice they made, add it to the ks incrementally

                        if ks[selectee] not in choices:
                            choices.append(ks[selectee])

                        hypothetical = ks
                        possible_pss = []

                        for choice in choices:
                            hypothetical[selectee] = choice
                            hyp_ps = predictive_structure(hypothetical)
                            possible_pss.append(hyp_ps)

                        new_ps = predictive_structure(ks)

                        if new_ps == min(possible_pss):
                            accuracy = 1
                        else:
                            accuracy = 0


                        results = {}

                        results['random_id'] = system_df['random_id'].values[0]
                        results['condition'] = system_df['condition'].values[0]
                        results['block'] = system_df['block'].values[0]
                        results['system'] = system_df['system'].values[0]
                        results['selectee'] = selectee
                        results['chosen_term'] = chosen_term
                        results['gen1'] = generalisers[0]
                        results['gen1_term'] = gen_terms[0]
                        results['gen2'] = generalisers[1]
                        results['gen2_term'] = gen_terms[1]
                        results['correct'] = accuracy

                        data.append(results)

    pd.DataFrame(data).to_csv('data/' + filename + '.csv',index=False) # save the dataframe

    return pd.DataFrame(data)

In [88]:
accuracy('accuracy_equal')

       random_id condition  block  system trial_type selectee selection  \
2585  1mxy428t9t      mfgb      5       0      catch        z    hyonăo
2586  1mxy428t9t      mfgb      5       0   critical      mbd    goozăi
2587  1mxy428t9t      mfgb      5       0   critical      mzs    goozăi
2588  1mxy428t9t      mfgb      5       0   critical      fzs    goozăi
2589  1mxy428t9t      mfgb      5       0   critical      mzd    goozăi
2590  1mxy428t9t      mfgb      5       0   critical      fbd    goozăi
2591  1mxy428t9t      mfgb      5       0   critical        b    goozăi
2592  1mxy428t9t      mfgb      5       0   critical      fzd    goozăi
2593  1mxy428t9t      mfgb      5       0   critical      fbs    goozăi

     expected  correct  undo  ...  generaliser2_term generaliser3  \
2585   hyonăo        1     0  ...             hyonăo          NaN
2586   goozăi        1     0  ...             hyonăo          NaN
2587   goozăi        1     0  ...             hyonăo          NaN
2588   goozăi        1     0  ...             hyonăo          NaN
2589   goozăi        1     0  ...             hyonăo          NaN
2590   goozăi        1     0  ...             hyonăo          NaN
2591   hyonăo        0     0  ...             hyonăo          NaN
2592   goozăi        1     0  ...             hyonăo          NaN
2593   goozăi        1     0  ...             hyonăo          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2585               NaN          NaN               NaN        False
2586               NaN          NaN               NaN          NaN
2587               NaN          NaN               NaN          NaN
2588               NaN          NaN               NaN          NaN
2589               NaN          NaN               NaN          NaN
2590               NaN          NaN               NaN          NaN
2591               NaN          NaN               NaN          NaN
2592               NaN          NaN               NaN          NaN
2593               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed    rt
2585             0         100       383441  2990
2586             3         101       386294  2852
2587             3         102       387698  1402
2588             3         103       390279  2579
2589             3         104       391491  1210
2590             3         105       392346   852
2591             3         106       393482  1133
2592             3         107       394378   894
2593             3         108       395203   822

[9 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2577  1mxy428t9t      mfgb      4       1   critical      mbd      øqoç
2578  1mxy428t9t      mfgb      4       1   critical      fzs  orinoçim
2579  1mxy428t9t      mfgb      4       1      catch      mzd      øqoç
2580  1mxy428t9t      mfgb      4       1   critical      mzs      øqoç
2581  1mxy428t9t      mfgb      4       1   critical      mbs      øqoç
2582  1mxy428t9t      mfgb      4       1   critical      fzd  orinoçim
2583  1mxy428t9t      mfgb      4       1   critical      fbs  orinoçim

      expected  correct  undo  ...  generaliser2_term generaliser3  \
2577      øqoç        1     0  ...               øqoç          NaN
2578  orinoçim        1     0  ...               øqoç          NaN
2579      øqoç        1     0  ...               øqoç          NaN
2580      øqoç        1     0  ...               øqoç          NaN
2581      øqoç        1     0  ...               øqoç          NaN
2582  orinoçim        1     0  ...               øqoç          NaN
2583  orinoçim        1     0  ...               øqoç          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2577               NaN          NaN               NaN          NaN
2578               NaN          NaN               NaN          NaN
2579               NaN          NaN               NaN        False
2580               NaN          NaN               NaN          NaN
2581               NaN          NaN               NaN          NaN
2582               NaN          NaN               NaN          NaN
2583               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed    rt
2577             0          83       349000  4243
2578             1          84       352000  2998
2579             0          85       354213  2210
2580             0          86       355864  1650
2581             0          87       357042  1176
2582             1          88       358738  1693
2583             1          89       359556   817

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2603  1mxy428t9t      mfgb      7       2      catch      fbs      ktot
2604  1mxy428t9t      mfgb      7       2   critical      fbd      ktot
2605  1mxy428t9t      mfgb      7       2   critical      mbs  tsåvvses
2606  1mxy428t9t      mfgb      7       2   critical      mbd      ktot
2607  1mxy428t9t      mfgb      7       2   critical      fzd      ktot
2608  1mxy428t9t      mfgb      7       2   critical      mzs  tsåvvses
2609  1mxy428t9t      mfgb      7       2   critical      mzd      ktot

      expected  correct  undo  ...  generaliser2_term generaliser3  \
2603      ktot        1     0  ...           tsåvvses          NaN
2604      ktot        1     0  ...           tsåvvses          NaN
2605      ktot        0     0  ...           tsåvvses          NaN
2606      ktot        1     0  ...           tsåvvses          NaN
2607  tsåvvses        0     0  ...           tsåvvses          NaN
2608  tsåvvses        1     0  ...           tsåvvses          NaN
2609  tsåvvses        0     0  ...           tsåvvses          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2603               NaN          NaN               NaN        False
2604               NaN          NaN               NaN          NaN
2605               NaN          NaN               NaN          NaN
2606               NaN          NaN               NaN          NaN
2607               NaN          NaN               NaN          NaN
2608               NaN          NaN               NaN          NaN
2609               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed     rt
2603             2         140       462743   2383
2604             2         141       476686  13941
2605             1         142       480252   3563
2606             2         143       481515   1260
2607             2         144       483106   1588
2608             1         145       484864   1756
2609             2         146       485690    825

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2611  1mxy428t9t      mfgb      8       3      catch      fbs     yaöpe
2612  1mxy428t9t      mfgb      8       3   critical      fzs     yaöpe
2613  1mxy428t9t      mfgb      8       3   critical      mzs     yaöpe
2614  1mxy428t9t      mfgb      8       3   critical      mzd     šïïnö
2615  1mxy428t9t      mfgb      8       3   critical      fbd     šïïnö
2616  1mxy428t9t      mfgb      8       3   critical      mbs     yaöpe
2617  1mxy428t9t      mfgb      8       3   critical      fzd     šïïnö

     expected  correct  undo  ...  generaliser2_term generaliser3  \
2611    yaöpe        1     0  ...              yaöpe          NaN
2612    šïïnö        0     0  ...              yaöpe          NaN
2613    yaöpe        1     0  ...              yaöpe          NaN
2614    yaöpe        0     0  ...              yaöpe          NaN
2615    yaöpe        0     0  ...              yaöpe          NaN
2616    šïïnö        0     0  ...              yaöpe          NaN
2617    šïïnö        1     0  ...              yaöpe          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2611               NaN          NaN               NaN        False
2612               NaN          NaN               NaN          NaN
2613               NaN          NaN               NaN          NaN
2614               NaN          NaN               NaN          NaN
2615               NaN          NaN               NaN          NaN
2616               NaN          NaN               NaN          NaN
2617               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed    rt
2611             1         159       513419  3055
2612             1         160       514725  1305
2613             1         161       516270  1543
2614             2         162       518123  1850
2615             2         163       519420  1294
2616             1         164       521168  1746
2617             2         165       524750  3580

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2553  1mxy428t9t      mfgb      1       4   critical      fzd    ozatof
2554  1mxy428t9t      mfgb      1       4   critical      mbd      ilug
2555  1mxy428t9t      mfgb      1       4   critical      mzd      ilug
2556  1mxy428t9t      mfgb      1       4   critical      fbs    ulywaf
2557  1mxy428t9t      mfgb      1       4   critical      fzs    ulywaf
2558  1mxy428t9t      mfgb      1       4   critical      mbs      ilug
2559  1mxy428t9t      mfgb      1       4      catch      mzs      ilug

     expected  correct  undo  ...  generaliser2_term generaliser3  \
2553     ilug        0     0  ...               ilug          fzd
2554     ilug        1     0  ...               ilug          fzd
2555     ilug        1     0  ...               ilug          fzd
2556   ulywaf        1     0  ...               ilug          fzd
2557     ilug        0     0  ...               ilug          fzd
2558     ilug        1     0  ...               ilug          fzd
2559     ilug        1     0  ...               ilug          fzd

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2553            ozatof          NaN               NaN          NaN
2554            ozatof          NaN               NaN          NaN
2555            ozatof          NaN               NaN          NaN
2556            ozatof          NaN               NaN          NaN
2557            ozatof          NaN               NaN          NaN
2558            ozatof          NaN               NaN          NaN
2559            ozatof          NaN               NaN        False

     button_number trial_index time_elapsed     rt
2553             1          26       164120  22776
2554             0          27       170098   5975
2555             0          28       172911   2809
2556             3          29       179911   6998
2557             3          30       182291   2377
2558             0          31       184928   2636
2559             0          32       188731   3800

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2561  1mxy428t9t      mfgb      2       5   critical      mbd  rbāranžā
2562  1mxy428t9t      mfgb      2       5      catch      mzs  rbāranžā
2563  1mxy428t9t      mfgb      2       5   critical      fzd     vbāžo
2564  1mxy428t9t      mfgb      2       5   critical      mbs  rbāranžā
2565  1mxy428t9t      mfgb      2       5   critical      mzd  rbāranžā
2566  1mxy428t9t      mfgb      2       5   critical      fbs     nžodo
2567  1mxy428t9t      mfgb      2       5   critical      fbd     vbāžo

      expected  correct  undo  ...  generaliser2_term generaliser3  \
2561  rbāranžā        1     0  ...           rbāranžā          NaN
2562  rbāranžā        1     0  ...           rbāranžā          NaN
2563     nžodo        0     0  ...           rbāranžā          fzd
2564  rbāranžā        1     0  ...           rbāranžā          fzd
2565  rbāranžā        1     0  ...           rbāranžā          fzd
2566  rbāranžā        0     0  ...           rbāranžā          fzd
2567  rbāranžā        0     0  ...           rbāranžā          fzd

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2561               NaN          NaN               NaN          NaN
2562               NaN          NaN               NaN        False
2563             vbāžo          NaN               NaN          NaN
2564             vbāžo          NaN               NaN          NaN
2565             vbāžo          NaN               NaN          NaN
2566             vbāžo          NaN               NaN          NaN
2567             vbāžo          NaN               NaN          NaN

     button_number trial_index time_elapsed    rt
2561             0          45       226868  4436
2562             0          46       230691  3821
2563             1          47       239352  8659
2564             0          48       241691  2339
2565             0          49       243794  2100
2566             2          50       249768  5973
2567             1          51       252005  2234

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2569  1mxy428t9t      mfgb      3       6   critical      fbd   popingi
2570  1mxy428t9t      mfgb      3       6   critical      fbs    lepego
2571  1mxy428t9t      mfgb      3       6   critical      fzs    kawuka
2572  1mxy428t9t      mfgb      3       6   critical      mzs    lepego
2573  1mxy428t9t      mfgb      3       6   critical      fzd    pygele
2574  1mxy428t9t      mfgb      3       6      catch      mbd   popingi
2575  1mxy428t9t      mfgb      3       6   critical      mbs   popingi

     expected  correct  undo  ...  generaliser2_term generaliser3  \
2569   lepego        0     0  ...             lepego          NaN
2570   lepego        1     0  ...             lepego          NaN
2571   lepego        0     0  ...             lepego          fzs
2572   lepego        1     0  ...             lepego          fzs
2573   lepego        0     0  ...             lepego          fzs
2574  popingi        1     0  ...             lepego          fzs
2575  popingi        1     0  ...             lepego          fzs

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2569               NaN          NaN               NaN          NaN
2570               NaN          NaN               NaN          NaN
2571            kawuka          NaN               NaN          NaN
2572            kawuka          NaN               NaN          NaN
2573            kawuka          fzd            pygele          NaN
2574            kawuka          fzd            pygele        False
2575            kawuka          fzd            pygele          NaN

     button_number trial_index time_elapsed     rt
2569             0          64       292449   6666
2570             3          65       303509  11057
2571             1          66       305954   2443
2572             3          67       310876   4919
2573             2          68       312621   1742
2574             0          69       314852   2229
2575             0          70       317514   2660

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2595  1mxy428t9t      mfgb      6       7   critical      mbs    morïky
2596  1mxy428t9t      mfgb      6       7   critical      fbd      kïmy
2597  1mxy428t9t      mfgb      6       7   critical      mbd      kïmy
2598  1mxy428t9t      mfgb      6       7   critical      fbs    morïky
2599  1mxy428t9t      mfgb      6       7   critical      fzs    morïky
2600  1mxy428t9t      mfgb      6       7   critical      mzd      kïmy
2601  1mxy428t9t      mfgb      6       7      catch      mzs    morïky

     expected  correct  undo  ...  generaliser2_term generaliser3  \
2595     kïmy        0     0  ...               kïmy          NaN
2596     kïmy        1     0  ...               kïmy          NaN
2597     kïmy        1     0  ...               kïmy          NaN
2598     kïmy        0     0  ...               kïmy          NaN
2599     kïmy        0     0  ...               kïmy          NaN
2600   morïky        0     0  ...               kïmy          NaN
2601   morïky        1     0  ...               kïmy          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2595               NaN          NaN               NaN          NaN
2596               NaN          NaN               NaN          NaN
2597               NaN          NaN               NaN          NaN
2598               NaN          NaN               NaN          NaN
2599               NaN          NaN               NaN          NaN
2600               NaN          NaN               NaN          NaN
2601               NaN          NaN               NaN        False

     button_number trial_index time_elapsed    rt
2595             3         121       422592  3195
2596             2         122       424809  2215
2597             2         123       426764  1953
2598             3         124       429289  2523
2599             3         125       430671  1380
2600             2         126       432120  1448
2601             3         127       433987  1865

[7 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
284  qe6qdpy4b2      mfbg      1       0   critical      mzs      vrêd
285  qe6qdpy4b2      mfbg      1       0   critical      mbs      vrêd
286  qe6qdpy4b2      mfbg      1       0   critical      mbd      vrêd
287  qe6qdpy4b2      mfbg      1       0   critical      fzd      vrêd
288  qe6qdpy4b2      mfbg      1       0      catch      fbs      vrêd
289  qe6qdpy4b2      mfbg      1       0   critical      fzs      vrêd
290  qe6qdpy4b2      mfbg      1       0   critical      mzd      vrêd
291  qe6qdpy4b2      mfbg      1       0   critical        b  rhymsvåd
292  qe6qdpy4b2      mfbg      1       0   critical      fbd      vrêd

     expected  correct  undo  ...  generaliser2_term generaliser3  \
284      vrêd        1     0  ...           rhymsvåd          NaN
285      vrêd        1     0  ...           rhymsvåd          NaN
286      vrêd        1     0  ...           rhymsvåd          NaN
287      vrêd        1     0  ...           rhymsvåd          NaN
288      vrêd        1     0  ...           rhymsvåd          NaN
289      vrêd        1     0  ...           rhymsvåd          NaN
290      vrêd        1     0  ...           rhymsvåd          NaN
291  rhymsvåd        1     0  ...           rhymsvåd          NaN
292      vrêd        1     0  ...           rhymsvåd          NaN

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
284               NaN          NaN               NaN          NaN
285               NaN          NaN               NaN          NaN
286               NaN          NaN               NaN          NaN
287               NaN          NaN               NaN          NaN
288               NaN          NaN               NaN        False
289               NaN          NaN               NaN          NaN
290               NaN          NaN               NaN          NaN
291               NaN          NaN               NaN          NaN
292               NaN          NaN               NaN          NaN

    button_number trial_index time_elapsed    rt
284             3          24        76859  6703
285             3          25        79915  3054
286             3          26        84451  4535
287             3          27        85811  1358
288             3          28        88235  2422
289             3          29        89739  1503
290             3          30        91003  1263
291             1          31        97475  6470
292             3          32        98827  1350

[9 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
318  qe6qdpy4b2      mfbg      5       1   critical      mbs      aweh
319  qe6qdpy4b2      mfbg      5       1      catch      mzd      aweh
320  qe6qdpy4b2      mfbg      5       1   critical      fbd    uquçun

      random_id condition  block  system trial_type selectee selection  \
258  zmpvzne4pl      fmbg      6       6   critical      mzd       gêă
259  zmpvzne4pl      fmbg      6       6   critical      mzs    nyumuo
260  zmpvzne4pl      fmbg      6       6   critical      fzs    nyumuo
261  zmpvzne4pl      fmbg      6       6   critical      mbs    nyumuo
262  zmpvzne4pl      fmbg      6       6      catch      mbd    niuhiê
263  zmpvzne4pl      fmbg      6       6   critical      fbs    nyumuo
264  zmpvzne4pl      fmbg      6       6   critical      fzd       gêă

    expected  correct  undo  ...  generaliser2_term generaliser3  \
258      gêă        1     0  ...                gêă          NaN
259      gêă        0     0  ...                gêă          mzs
260      gêă        0     0  ...                gêă          mzs
261   niuhiê        0     0  ...                gêă          mzs
262   niuhiê        1     0  ...                gêă          mzs
263      gêă        0     0  ...                gêă          mzs
264      gêă        1     0  ...                gêă          mzs

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
258               NaN          NaN               NaN          NaN
259            nyumuo          NaN               NaN          NaN
260            nyumuo          fzs            nyumuo          NaN
261            nyumuo          fzs            nyumuo          NaN
262            nyumuo          fzs            nyumuo        False
263            nyumuo          fzs            nyumuo          NaN
264            nyumuo          fzs            nyumuo          NaN

    button_number trial_index time_elapsed    rt
258             3         121       450364  7963
259             1         122       453042  2677
260             1         123       458889  5846
261             1         124       463500  4609
262             2         125       466079  2578
263             1         126       469600  3520
264             3         127       474474  4872

[7 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
218  zmpvzne4pl      fmbg      1       7   critical      fzs  kvurddåh
219  zmpvzne4pl      fmbg      1       7   critical      mzd      vrêd
220  zmpvzne4pl      fmbg      1       7   critical      fbs  kvurddåh
221  zmpvzne4pl      fmbg      1       7   critical      mbd      vrêd
222  zmpvzne4pl      fmbg      1       7      catch      fbd  kvurddåh
223  zmpvzne4pl      fmbg      1       7   critical      fzd  kvurddåh
224  zmpvzne4pl      fmbg      1       7   critical      mbs      vrêd

     expected  correct  undo  ...  generaliser2_term generaliser3  \
218  kvurddåh        1     0  ...           kvurddåh          NaN
219      vrêd        1     0  ...           kvurddåh          NaN
220  kvurddåh        1     0  ...           kvurddåh          NaN
221  kvurddåh        0     0  ...           kvurddåh          NaN
222  kvurddåh        1     0  ...           kvurddåh          NaN
223  kvurddåh        1     0  ...           kvurddåh          NaN
224  kvurddåh        0     0  ...           kvurddåh          NaN

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
218               NaN          NaN               NaN          NaN
219               NaN          NaN               NaN          NaN
220               NaN          NaN               NaN          NaN
221               NaN          NaN               NaN          NaN
222               NaN          NaN               NaN        False
223               NaN          NaN               NaN          NaN
224               NaN          NaN               NaN          NaN

    button_number trial_index time_elapsed     rt
218             0          26       206122  16424
219             2          27       217351  11227
220             0          28       220454   3102
221             2          29       225342   4888
222             0          30       226651   1308
223             0          31       229160   2508
224             2          32       230414   1253

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2685  llelh1mjm8      mfbg      1       0      catch        z   popingi
2686  llelh1mjm8      mfbg      1       0   critical      mzd    lepego
2687  llelh1mjm8      mfbg      1       0   critical      mzs    lepego
2688  llelh1mjm8      mfbg      1       0   critical      fzd    lepego
2689  llelh1mjm8      mfbg      1       0   critical      fzs    lepego
2690  llelh1mjm8      mfbg      1       0   critical      mbs    lepego
2691  llelh1mjm8      mfbg      1       0   critical      fbd    lepego
2698  llelh1mjm8      mfbg      1       0   critical      mzd    lepego
2699  llelh1mjm8      mfbg      1       0   critical      mzs    lepego
2700  llelh1mjm8      mfbg      1       0   critical      fzd    lepego
2701  llelh1mjm8      mfbg      1       0   critical      fzs    lepego
2702  llelh1mjm8      mfbg      1       0   critical      mbs    lepego
2703  llelh1mjm8      mfbg      1       0   critical      fbd    lepego
2704  llelh1mjm8      mfbg      1       0   critical      mbd    lepego
2705  llelh1mjm8      mfbg      1       0   critical        b    lepego
2707  llelh1mjm8      mfbg      1       0   critical        b   popingi

     expected  correct  undo  ...  generaliser2_term generaliser3  \
2685  popingi        1     0  ...            popingi          NaN
2686   lepego        1     0  ...            popingi          NaN
2687   lepego        1     0  ...            popingi          NaN
2688   lepego        1     0  ...            popingi          NaN
2689   lepego        1     0  ...            popingi          NaN
2690   lepego        1     0  ...            popingi          NaN
2691   lepego        1     0  ...            popingi          NaN
2698   lepego        1     0  ...            popingi          NaN
2699   lepego        1     0  ...            popingi          NaN
2700   lepego        1     0  ...            popingi          NaN
2701   lepego        1     0  ...            popingi          NaN
2702   lepego        1     0  ...            popingi          NaN
2703   lepego        1     0  ...            popingi          NaN
2704   lepego        1     0  ...            popingi          NaN
2705  popingi        0     0  ...            popingi          NaN
2707  popingi        1     0  ...            popingi          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2685               NaN          NaN               NaN        False
2686               NaN          NaN               NaN          NaN
2687               NaN          NaN               NaN          NaN
2688               NaN          NaN               NaN          NaN
2689               NaN          NaN               NaN          NaN
2690               NaN          NaN               NaN          NaN
2691               NaN          NaN               NaN          NaN
2698               NaN          NaN               NaN          NaN
2699               NaN          NaN               NaN          NaN
2700               NaN          NaN               NaN          NaN
2701               NaN          NaN               NaN          NaN
2702               NaN          NaN               NaN          NaN
2703               NaN          NaN               NaN          NaN
2704               NaN          NaN               NaN          NaN
2705               NaN          NaN               NaN          NaN
2707               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed     rt
2685             2          24       273656   5072
2686             1          25       297626  23969
2687             1          26       301011   3383
2688             1          27       304907   3896
2689             1          28       305531    623
2690             1          29       306276    743
2691             1          30       306716    439
2698             1          37       322269   2575
2699             1          38       322613    343
2700             1          39       322925    311
2701             1          40       323261    334
2702             1          41       323605    343
2703             1          42       324509    903
2704             1          43       325389    879
2705             1          44       326453   1063
2707             2          46       337543   8440

[16 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2761  llelh1mjm8      mfbg      8       1   critical      mzs    agivud
2762  llelh1mjm8      mfbg      8       1   critical      mbd      azuf
2763  llelh1mjm8      mfbg      8       1   critical      mbs      azuf
2764  llelh1mjm8      mfbg      8       1   critical      fzs    agivud
2765  llelh1mjm8      mfbg      8       1   critical      fzd    agivud
2766  llelh1mjm8      mfbg      8       1   critical      fbd      azuf
2767  llelh1mjm8      mfbg      8       1      catch      fbs      azuf

     expected  correct  undo  ...  generaliser2_term generaliser3  \
2761   agivud        1     0  ...             agivud          NaN
2762   agivud        0     0  ...             agivud          NaN
2763   agivud        0     0  ...             agivud          NaN
2764     azuf        0     0  ...             agivud          NaN
2765     azuf        0     0  ...             agivud          NaN
2766     azuf        1     0  ...             agivud          NaN
2767     azuf        1     0  ...             agivud          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2761               NaN          NaN               NaN          NaN
2762               NaN          NaN               NaN          NaN
2763               NaN          NaN               NaN          NaN
2764               NaN          NaN               NaN          NaN
2765               NaN          NaN               NaN          NaN
2766               NaN          NaN               NaN          NaN
2767               NaN          NaN               NaN        False

     button_number trial_index time_elapsed    rt
2761             3         177       689591  4056
2762             0         178       699552  9960
2763             0         179       700744  1191
2764             3         180       705385  4640
2765             3         181       707705  2319
2766             0         182       710114  2407
2767             0         183       712738  2623

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2753  llelh1mjm8      mfbg      7       2   critical      fbs     möïtu
2754  llelh1mjm8      mfbg      7       2   critical      mbs     möïtu
2755  llelh1mjm8      mfbg      7       2   critical      mzd     nuubö
2756  llelh1mjm8      mfbg      7       2   critical      fzd     nuubö
2757  llelh1mjm8      mfbg      7       2   critical      mzs     nuubö
2758  llelh1mjm8      mfbg      7       2   critical      fbd     möïtu
2759  llelh1mjm8      mfbg      7       2      catch      fzs     nuubö

     expected  correct  undo  ...  generaliser2_term generaliser3  \
2753    möïtu        1     0  ...              nuubö          NaN
2754    möïtu        1     0  ...              nuubö          NaN
2755    nuubö        1     0  ...              nuubö          NaN
2756    nuubö        1     0  ...              nuubö          NaN
2757    nuubö        1     0  ...              nuubö          NaN
2758    möïtu        1     0  ...              nuubö          NaN
2759    nuubö        1     0  ...              nuubö          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2753               NaN          NaN               NaN          NaN
2754               NaN          NaN               NaN          NaN
2755               NaN          NaN               NaN          NaN
2756               NaN          NaN               NaN          NaN
2757               NaN          NaN               NaN          NaN
2758               NaN          NaN               NaN          NaN
2759               NaN          NaN               NaN        False

     button_number trial_index time_elapsed    rt
2753             1         158       655771  8896
2754             1         159       657900  2127
2755             3         160       661804  3903
2756             3         161       663260  1455
2757             3         162       665764  2503
2758             1         163       670046  4280
2759             3         164       673045  2999

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2737  llelh1mjm8      mfbg      5       3   critical      mbd  orinoçim
2738  llelh1mjm8      mfbg      5       3      catch      fbs      øqoç
2739  llelh1mjm8      mfbg      5       3   critical      mzs  orinoçim
2740  llelh1mjm8      mfbg      5       3   critical      mzd  orinoçim
2741  llelh1mjm8      mfbg      5       3   critical      fbd      øqoç
2742  llelh1mjm8      mfbg      5       3   critical      fzs      øqoç
2743  llelh1mjm8      mfbg      5       3   critical      fzd      øqoç

      expected  correct  undo  ...  generaliser2_term generaliser3  \
2737  orinoçim        1     0  ...               øqoç          NaN
2738      øqoç        1     0  ...               øqoç          NaN
2739      øqoç        0     0  ...               øqoç          NaN
2740      øqoç        0     0  ...               øqoç          NaN
2741      øqoç        1     0  ...               øqoç          NaN
2742  orinoçim        0     0  ...               øqoç          NaN
2743  orinoçim        0     0  ...               øqoç          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2737               NaN          NaN               NaN          NaN
2738               NaN          NaN               NaN        False
2739               NaN          NaN               NaN          NaN
2740               NaN          NaN               NaN          NaN
2741               NaN          NaN               NaN          NaN
2742               NaN          NaN               NaN          NaN
2743               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed    rt
2737             2         120       575978  2728
2738             0         121       579835  3855
2739             2         122       583627  3792
2740             2         123       584507   879
2741             0         124       586884  2375
2742             0         125       588252  1367
2743             0         126       589052   799

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2745  llelh1mjm8      mfbg      6       4      catch      fzs     vbāžo
2746  llelh1mjm8      mfbg      6       4   critical      mzd     vbāžo
2747  llelh1mjm8      mfbg      6       4   critical      fbd    ngcāžo
2748  llelh1mjm8      mfbg      6       4   critical      mbs    ngcāžo
2749  llelh1mjm8      mfbg      6       4   critical      fzd     vbāžo
2750  llelh1mjm8      mfbg      6       4   critical      mzs     vbāžo
2751  llelh1mjm8      mfbg      6       4   critical      mbd    ngcāžo

     expected  correct  undo  ...  generaliser2_term generaliser3  \
2745    vbāžo        1     0  ...              vbāžo          NaN
2746    vbāžo        1     0  ...              vbāžo          NaN
2747   ngcāžo        1     0  ...              vbāžo          NaN
2748    vbāžo        0     0  ...              vbāžo          NaN
2749    vbāžo        1     0  ...              vbāžo          NaN
2750    vbāžo        1     0  ...              vbāžo          NaN
2751    vbāžo        0     0  ...              vbāžo          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2745               NaN          NaN               NaN        False
2746               NaN          NaN               NaN          NaN
2747               NaN          NaN               NaN          NaN
2748               NaN          NaN               NaN          NaN
2749               NaN          NaN               NaN          NaN
2750               NaN          NaN               NaN          NaN
2751               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed     rt
2745             3         139       601765   3232
2746             3         140       623336  21569
2747             1         141       625512   2175
2748             1         142       630017   4504
2749             3         143       632737   2719
2750             3         144       635977   3239
2751             1         145       636865    887

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2729  llelh1mjm8      mfbg      4       5   critical      fbs      bybï
2730  llelh1mjm8      mfbg      4       5   critical      mzd    zuvewu
2731  llelh1mjm8      mfbg      4       5   critical      mbs    zuvewu
2732  llelh1mjm8      mfbg      4       5   critical      fzs      bybï
2733  llelh1mjm8      mfbg      4       5   critical      mbd    zuvewu
2734  llelh1mjm8      mfbg      4       5   critical      fbd      bybï
2735  llelh1mjm8      mfbg      4       5      catch      mzs    zuvewu

     expected  correct  undo  ...  generaliser2_term generaliser3  \
2729   zuvewu        0     0  ...             zuvewu          NaN
2730   zuvewu        1     0  ...             zuvewu          NaN
2731   zuvewu        1     0  ...             zuvewu          NaN
2732     bybï        1     0  ...             zuvewu          NaN
2733   zuvewu        1     0  ...             zuvewu          NaN
2734   zuvewu        0     0  ...             zuvewu          NaN
2735   zuvewu        1     0  ...             zuvewu          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2729               NaN          NaN               NaN          NaN
2730               NaN          NaN               NaN          NaN
2731               NaN          NaN               NaN          NaN
2732               NaN          NaN               NaN          NaN
2733               NaN          NaN               NaN          NaN
2734               NaN          NaN               NaN          NaN
2735               NaN          NaN               NaN        False

     button_number trial_index time_elapsed    rt
2729             3         101       546583  4256
2730             2         102       550623  4040
2731             2         103       552200  1575
2732             3         104       553808  1607
2733             2         105       555216  1407
2734             3         106       556640  1423
2735             2         107       561825  5184

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2721  llelh1mjm8      mfbg      3       6   critical      fbd    goozăi
2722  llelh1mjm8      mfbg      3       6   critical      mzd    baumiă
2723  llelh1mjm8      mfbg      3       6   critical      fzd    goozăi
2724  llelh1mjm8      mfbg      3       6   critical      mzs    baumiă
2725  llelh1mjm8      mfbg      3       6      catch      mbd    baumiă
2726  llelh1mjm8      mfbg      3       6   critical      mbs    baumiă
2727  llelh1mjm8      mfbg      3       6   critical      fzs    goozăi

     expected  correct  undo  ...  generaliser2_term generaliser3  \
2721   goozăi        1     0  ...             goozăi          NaN
2722   goozăi        0     0  ...             goozăi          NaN
2723   goozăi        1     0  ...             goozăi          NaN
2724   goozăi        0     0  ...             goozăi          NaN
2725   baumiă        1     0  ...             goozăi          NaN
2726   baumiă        1     0  ...             goozăi          NaN
2727   goozăi        1     0  ...             goozăi          NaN


       random_id condition  block  system trial_type selectee selection  \
1538  n82s617h3t      mfbg      5       5      catch      fzd  orinoçim
1539  n82s617h3t      mfbg      5       5   critical      fbs      iqur
1540  n82s617h3t      mfbg      5       5   critical      fbd  orinoçim
1541  n82s617h3t      mfbg      5       5   critical      mbd      iqur
1542  n82s617h3t      mfbg      5       5   critical      mbs  içiqusem
1543  n82s617h3t      mfbg      5       5   critical      mzs  içiqusem
1544  n82s617h3t      mfbg      5       5   critical      fzs    adeçim

      expected  correct  undo  ...  generaliser2_term generaliser3  \
1538  orinoçim        1     0  ...               iqur          NaN
1539      iqur        1     0  ...               iqur          NaN
1540      iqur        0     0  ...               iqur          NaN
1541      iqur        1     0  ...               iqur          NaN
1542      iqur        0     0  ...               iqur          mbs
1543      iqur        0     0  ...               iqur          mbs
1544  orinoçim        0     0  ...               iqur          mbs

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1538               NaN          NaN               NaN        False
1539               NaN          NaN               NaN          NaN
1540               NaN          NaN               NaN          NaN
1541               NaN          NaN               NaN          NaN
1542          içiqusem          NaN               NaN          NaN
1543          içiqusem          NaN               NaN          NaN
1544          içiqusem          fzs            adeçim          NaN

     button_number trial_index time_elapsed     rt
1538             2         102       331083   2377
1539             0         103       342066  10978
1540             2         104       344180   2110
1541             0         105       349725   5541
1542             1         106       352960   3231
1543             1         107       353842    879
1544             3         108       363145   9299

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1522  n82s617h3t      mfbg      3       6      catch      fzd  lobowaby
1523  n82s617h3t      mfbg      3       6   critical      fbd  lobowaby
1524  n82s617h3t      mfbg      3       6   critical      fbs  lobowaby
1525  n82s617h3t      mfbg      3       6   critical      fzs  lobowaby
1526  n82s617h3t      mfbg      3       6   critical      mbs  bokokohï
1527  n82s617h3t      mfbg      3       6   critical      mzs  bokokohï
1528  n82s617h3t      mfbg      3       6   critical      mzd  bokokohï

      expected  correct  undo  ...  generaliser2_term generaliser3  \
1522  lobowaby        1     0  ...           lobowaby          NaN
1523  lobowaby        1     0  ...           lobowaby          NaN
1524  lobowaby        1     0  ...           lobowaby          NaN
1525  lobowaby        1     0  ...           lobowaby          NaN
1526  bokokohï        1     0  ...           lobowaby          NaN
1527  lobowaby        0     0  ...           lobowaby          NaN
1528  lobowaby        0     0  ...           lobowaby          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1522               NaN          NaN               NaN        False
1523               NaN          NaN               NaN          NaN
1524               NaN          NaN               NaN          NaN
1525               NaN          NaN               NaN          NaN
1526               NaN          NaN               NaN          NaN
1527               NaN          NaN               NaN          NaN
1528               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed    rt
1522             1          64       261738  6661
1523             1          65       267240  5498
1524             1          66       268838  1596
1525             1          67       270812  1969
1526             2          68       274515  3699
1527             2          69       275310   793
1528             2          70       276166   853

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1546  n82s617h3t      mfbg      6       7   critical      fzd     vbāžo
1547  n82s617h3t      mfbg      6       7   critical      mzd     vbāžo
1548  n82s617h3t      mfbg      6       7   critical      mbd     vbāžo
1549  n82s617h3t      mfbg      6       7   critical      fbd     vbāžo
1550  n82s617h3t      mfbg      6       7      catch      mbs     nžodo
1551  n82s617h3t      mfbg      6       7   critical      fzs     nžodo
1552  n82s617h3t      mfbg      6       7   critical      fbs     nžodo

      expected  correct  undo  ...  generaliser2_term generaliser3  \
1546     nžodo        0     0  ...              nžodo          fzd
1547  rbāranžā        0     0  ...              nžodo          fzd
1548     nžodo        0     0  ...              nžodo          fzd
1549     nžodo        0     0  ...              nžodo          fzd
1550     nžodo        1     0  ...              nžodo          fzd
1551     nžodo        1     0  ...              nžodo          fzd
1552     nžodo        1     0  ...              nžodo          fzd

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1546             vbāžo          NaN               NaN          NaN
1547             vbāžo          mzd             vbāžo          NaN
1548             vbāžo          mzd             vbāžo          NaN
1549             vbāžo          mzd             vbāžo          NaN
1550             vbāžo          mzd             vbāžo        False
1551             vbāžo          mzd             vbāžo          NaN
1552             vbāžo          mzd             vbāžo          NaN

     button_number trial_index time_elapsed     rt
1546             0         121       389060  19294
1547             0         122       392420   3358
1548             0         123       393605   1181
1549             0         124       395081   1472
1550             2         125       397253   2168
1551             2         126       398345   1089
1552             2         127       399825   1477

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2315  uf9y22kc7h      fmbg      2       0   critical      fbs      kïmy
2316  uf9y22kc7h      fmbg      2       0      catch      mzs    ryvïri
2317  uf9y22kc7h      fmbg      2       0   critical      mzd  męwaqïfe
2318  uf9y22kc7h      fmbg      2       0   critical      fbd    ryvïri
2319  uf9y22kc7h      fmbg      2       0   critical        z  męwaqïfe
2320  uf9y22kc7h      fmbg      2       0   critical      fzs  lobowaby
2321  uf9y22kc7h      fmbg      2       0   critical      fzd      kïmy
2322  uf9y22kc7h      fmbg      2       0   critical      mbd  męwaqïfe
2323  uf9y22kc7h      fmbg      2       0   critical      mbs    ryvïri

      expected  correct  undo  ...  generaliser2_term generaliser3  \
2315    ryvïri        0     0  ...           męwaqïfe          fbs
2316    ryvïri        1     0  ...           męwaqïfe          fbs
2317    ryvïri        0     0  ...           męwaqïfe          fbs
2318    ryvïri        1     0  ...           męwaqïfe          fbs
2319  męwaqïfe        1     0  ...           męwaqïfe          fbs
2320    ryvïri        0     0  ...           męwaqïfe          fbs
2321    ryvïri        0     0  ...           męwaqïfe          fbs
2322    ryvïri        0     0  ...           męwaqïfe          fbs
2323    ryvïri        1     0  ...           męwaqïfe          fbs

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2315              kïmy          NaN               NaN          NaN
2316              kïmy          NaN               NaN        False
2317              kïmy          NaN               NaN          NaN
2318              kïmy          NaN               NaN          NaN
2319              kïmy          NaN               NaN          NaN
2320              kïmy          NaN               NaN          NaN
2321              kïmy          fzd              kïmy          NaN
2322              kïmy          fzd              kïmy          NaN
2323              kïmy          fzd              kïmy          NaN

     button_number trial_index time_elapsed     rt
2315             0          43       486897  26988
2316             3          44       499323  12424
2317             2          45       514617  15291
2318             3          46       521756   7133
2319             2          47       534912  13153
2320             1          48       581177  46263
2321             0          49       594202  13022
2322             2          50       605956  11748
2323             3          51       616734  10775

[9 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2365  uf9y22kc7h      fmbg      8       1      catch      fzd    awupav
2366  uf9y22kc7h      fmbg      8       1   critical      fbd      ilug
2367  uf9y22kc7h      fmbg      8       1   critical      mzs      azuf
2368  uf9y22kc7h      fmbg      8       1   critical      fzs    agivud
2369  uf9y22kc7h      fmbg      8       1   critical      fbs      azuf
2370  uf9y22kc7h      fmbg      8       1   critical      mbs      azuf
2371  uf9y22kc7h      fmbg      8       1   critical      mzd    awupav

     expected  correct  undo  ...  generaliser2_term generaliser3  \
2365   awupav        1     0  ...               ilug          NaN
2366   awupav        0     0  ...               ilug          NaN
2367     ilug        0     0  ...               ilug          mzs
2368   awupav        0     0  ...               ilug          mzs
2369   awupav        0     0  ...               ilug          mzs
2370     ilug        0     0  ...               ilug          mzs
2371     ilug        0     0  ...               ilug          mzs

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2365               NaN          NaN               NaN        False
2366               NaN          NaN               NaN          NaN
2367              azuf          NaN               NaN          NaN
2368              azuf          fzs            agivud          NaN
2369              azuf          fzs            agivud          NaN
2370              azuf          fzs            agivud          NaN
2371              azuf          fzs            agivud          NaN

     button_number trial_index time_elapsed     rt
2365             3         159      1066125   5503
2366             0         160      1083462  17334
2367             2         161      1089207   5744
2368             1         162      1099808  10599
2369             2         163      1106291   6481
2370             2         164      1110107   3814
2371             3         165      1114214   4105

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2349  uf9y22kc7h      fmbg      6       2   critical      fzd      wupu
2350  uf9y22kc7h      fmbg      6       2   critical      fbs    lepego
2351  uf9y22kc7h      fmbg      6       2   critical      mzs    lepego
2352  uf9y22kc7h      fmbg      6       2   critical      fbd    lepego
2353  uf9y22kc7h      fmbg      6       2      catch      mzd    kawuka
2354  uf9y22kc7h      fmbg      6       2   critical      fzs      luge
2355  uf9y22kc7h      fmbg      6       2   critical      mbd    lepego

     expected  correct  undo  ...  generaliser2_term generaliser3  \
2349   kawuka        0     0  ...             kawuka          fzd
2350     luge        0     0  ...             kawuka          fzd
2351   kawuka        0     0  ...             kawuka          fzd
2352     luge        0     0  ...             kawuka          fzd
2353   kawuka        1     0  ...             kawuka          fzd
2354   kawuka        0     0  ...             kawuka          fzd
2355     luge        0     0  ...             kawuka          fzd

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2349              wupu          NaN               NaN          NaN
2350              wupu          NaN               NaN          NaN
2351              wupu          NaN               NaN          NaN
2352              wupu          NaN               NaN          NaN
2353              wupu          NaN               NaN        False
2354              wupu          NaN               NaN          NaN
2355              wupu          NaN               NaN          NaN

     button_number trial_index time_elapsed     rt
2349             0         121       913698   8055
2350             1         122       916341   2641
2351             1         123       920790   4447
2352             1         124       932989  12194
2353             3         125       938294   5302
2354             2         126       953874  15579
2355             1         127       962974   9097

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2325  uf9y22kc7h      fmbg      3       3   critical      mbs    niuhiê
2326  uf9y22kc7h      fmbg      3       3   critical      fbd       qăo
2327  uf9y22kc7h      fmbg      3       3   critical      fzd    huanăa
2328  uf9y22kc7h      fmbg      3       3   critical      mzs    baumiă
2329  uf9y22kc7h      fmbg      3       3   critical      fzs    baumiă
2330  uf9y22kc7h      fmbg      3       3   critical      mzd    niuhiê
2331  uf9y22kc7h      fmbg      3       3      catch      mbd       qăo

     expected  correct  undo  ...  generaliser2_term generaliser3  \
2325      qăo        0     0  ...             baumiă          mbs
2326   baumiă        0     0  ...             baumiă          mbs
2327      qăo        0     0  ...             baumiă          mbs
2328   baumiă        1     0  ...             baumiă          mbs
2329      qăo        0     0  ...             baumiă          mbs
2330   baumiă        0     0  ...             baumiă          mbs
2331      qăo        1     0  ...             baumiă          mbs

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2325            niuhiê          NaN               NaN          NaN
2326            niuhiê          NaN               NaN          NaN
2327            niuhiê          fzd            huanăa          NaN
2328            niuhiê          fzd            huanăa          NaN
2329            niuhiê          fzd            huanăa          NaN
2330            niuhiê          fzd            huanăa          NaN
2331            niuhiê          fzd            huanăa        False

     button_number trial_index time_elapsed     rt
2325             0          64       684347  48838
2326             1          65       700326  15978
2327             2          66       707044   6716
2328             3          67       721029  13983
2329             3          68       754357  33325
2330             0          69       759707   5347
2331             1          70       767325   7615

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2357  uf9y22kc7h      fmbg      7       4   critical      mzs  rhymsvåd
2358  uf9y22kc7h      fmbg      7       4   critical      mzd  smêvskêv
2359  uf9y22kc7h      fmbg      7       4   critical      mbd  ktåvrhus
2360  uf9y22kc7h      fmbg      7       4   critical      mbs  kvurddåh
2361  uf9y22kc7h      fmbg      7       4   critical      fbs  kvurddåh
2362  uf9y22kc7h      fmbg      7       4   critical      fzd  smêvskêv
2363  uf9y22kc7h      fmbg      7       4      catch      fzs  kvurddåh

      expected  correct  undo  ...  generaliser2_term generaliser3  \
2357  kvurddåh        0     0  ...           kvurddåh          NaN
2358  kvurddåh        0     0  ...           kvurddåh          mzd
2359  kvurddåh        0     0  ...           kvurddåh          mzd
2360  kvurddåh        1     0  ...           kvurddåh          mzd
2361  rhymsvåd        0     0  ...           kvurddåh          mzd
2362  kvurddåh        0     0  ...           kvurddåh          mzd
2363  kvurddåh        1     0  ...           kvurddåh          mzd

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2357               NaN          NaN               NaN          NaN
2358          smêvskêv          NaN               NaN          NaN
2359          smêvskêv          NaN               NaN          NaN
2360          smêvskêv          NaN               NaN          NaN
2361          smêvskêv          NaN               NaN          NaN
2362          smêvskêv          fzd          smêvskêv          NaN
2363          smêvskêv          fzd          smêvskêv        False

     button_number trial_index time_elapsed     rt
2357             2         140       998325  26699
2358             1         141      1015623  17296
2359             3         142      1032291  16665
2360             0         143      1037791   5498
2361             0         144      1043313   5520
2362             1         145      1051317   8002
2363             0         146      1055591   4269

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2307  uf9y22kc7h      fmbg      1       5   critical      fzd  rbāranžā
2308  uf9y22kc7h      fmbg      1       5   critical      mzd     žbodu
2309  uf9y22kc7h      fmbg      1       5   critical      mzs     žbodu
2310  uf9y22kc7h      fmbg      1       5   critical      fbd     žbodu
2311  uf9y22kc7h      fmbg      1       5   critical      fbs  rbāranžā
2312  uf9y22kc7h      fmbg      1       5      catch      mbd     žbodu
2313  uf9y22kc7h      fmbg      1       5   critical      mbs     byure

      expected  correct  undo  ...  generaliser2_term generaliser3  \
2307  rbāranžā        1     0  ...              žbodu          NaN
2308     žbodu        1     0  ...              žbodu          NaN
2309     žbodu        1     0  ...              žbodu          NaN
2310     žbodu        1     0  ...              žbodu          NaN
2311     žbodu        0     0  ...              žbodu          NaN
2312     žbodu        1     0  ...              žbodu          NaN
2313     žbodu        0     0  ...              žbodu          mbs

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2307               NaN          NaN               NaN          NaN
2308               NaN          NaN               NaN          NaN
2309               NaN          NaN               NaN          NaN
2310               NaN          NaN               NaN          NaN
2311               NaN          NaN               NaN          NaN
2312               NaN          NaN               NaN        False
2313             byure          NaN               NaN          NaN

     button_number trial_index time_elapsed     rt
2307             3          26       336049  11116
2308             0          27       362164  26106
2309             0          28       374598  12432
2310             0          29       380999   6399
2311             3          30       384575   3574
2312             0          31       412141  27564
2313             2          32       426013  13870

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2341  uf9y22kc7h      fmbg      5       6   critical      fbs     töeqo
2342  uf9y22kc7h      fmbg      5       6   critical      mzs  šaaqaude
2343  uf9y22kc7h      fmbg      5       6   critical      fbd     šïïnö
2344  uf9y22kc7h      fmbg      5       6   critical      fzs  šaaqaude
2345  uf9y22kc7h      fmbg      5       6   critical      mbd     šïïnö
2346  uf9y22kc7h      fmbg      5       6      catch      mzd   tuumïhu
2347  uf9y22kc7h      fmbg      5       6   critical      fzd   tuumïhu

     expected  correct  undo  ...  generaliser2_term generaliser3  \

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2837  wh08dqfy5x      mfbg      1       6   critical      mbs    hïlaki
2838  wh08dqfy5x      mfbg      1       6   critical      fbs    zuvewu
2839  wh08dqfy5x      mfbg      1       6   critical      fzs    zuvewu
2840  wh08dqfy5x      mfbg      1       6   critical      mzs    hïlaki
2841  wh08dqfy5x      mfbg      1       6   critical      mzd    hïlaki
2842  wh08dqfy5x      mfbg      1       6      catch      fzd    zuvewu
2843  wh08dqfy5x      mfbg      1       6   critical      fbd    zuvewu

     expected  correct  undo  ...  generaliser2_term generaliser3  \
2837   hïlaki        1     0  ...             zuvewu          NaN
2838   zuvewu        1     0  ...             zuvewu          NaN
2839   zuvewu        1     0  ...             zuvewu          NaN
2840   zuvewu        0     0  ...             zuvewu          NaN
2841   zuvewu        0     0  ...             zuvewu          NaN
2842   zuvewu        1     0  ...             zuvewu          NaN
2843   zuvewu        1     0  ...             zuvewu          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2837               NaN          NaN               NaN          NaN
2838               NaN          NaN               NaN          NaN
2839               NaN          NaN               NaN          NaN
2840               NaN          NaN               NaN          NaN
2841               NaN          NaN               NaN          NaN
2842               NaN          NaN               NaN        False
2843               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed     rt
2837             0          26      1788100  12182
2838             1          27      1790344   2242
2839             1          28      1792899   2554
2840             0          29      1794603   1703
2841             0          30      1795199    595
2842             1          31      1802262   7062
2843             1          32      1805006   2742

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2877  wh08dqfy5x      mfbg      6       7   critical      fzs    ulywaf
2878  wh08dqfy5x      mfbg      6       7   critical      mbs    ulywaf
2879  wh08dqfy5x      mfbg      6       7   critical      fbs    ulywaf
2880  wh08dqfy5x      mfbg      6       7   critical      fbd      azuf
2881  wh08dqfy5x      mfbg      6       7   critical      fzd      azuf
2882  wh08dqfy5x      mfbg      6       7   critical      mzd      azuf
2883  wh08dqfy5x      mfbg      6       7      catch      mbd      azuf

     expected  correct  undo  ...  generaliser2_term generaliser3  \
2877     azuf        0     0  ...               azuf          NaN
2878     azuf        0     0  ...               azuf          NaN
2879     azuf        0     0  ...               azuf          NaN
2880     azuf        1     0  ...               azuf          NaN
2881     azuf        1     0  ...               azuf          NaN
2882   ulywaf        0     0  ...               azuf          NaN
2883     azuf        1     0  ...               azuf          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2877               NaN          NaN               NaN          NaN
2878               NaN          NaN               NaN          NaN
2879               NaN          NaN               NaN          NaN
2880               NaN          NaN               NaN          NaN
2881               NaN          NaN               NaN          NaN
2882               NaN          NaN               NaN          NaN
2883               NaN          NaN               NaN        False

     button_number trial_index time_elapsed    rt
2877             1         121      1985398  4889
2878             1         122      1987653  2254
2879             1         123      1989216  1562
2880             3         124      1991845  2628
2881             3         125      1992761   915
2882             3         126      1993919  1157
2883             3         127      1996528  2608

[7 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
594  ccehyx1t6d      fmgb      5       0   critical      mbs     šïïnö
595  ccehyx1t6d      fmgb      5       0   critical      fzs     šïïnö
596  ccehyx1t6d      fmgb      5       0   critical      mbd     šïïnö
597  ccehyx1t6d      fmgb      5       0   critical      fzd     šïïnö
598  ccehyx1t6d      fmgb      5       0   critical      fbs     šïïnö
599  ccehyx1t6d      fmgb      5       0   critical      fbd     šïïnö
600  ccehyx1t6d      fmgb      5       0   critical        z     yaöpe
601  ccehyx1t6d      fmgb      5       0   critical      mzs     šïïnö
602  ccehyx1t6d      fmgb      5       0      catch      mzd     šïïnö

    expected  correct  undo  ...  generaliser2_term generaliser3  \
594    šïïnö        1     0  ...              töeqo          NaN
595    šïïnö        1     0  ...              töeqo          NaN
596    šïïnö        1     0  ...              töeqo          NaN
597    šïïnö        1     0  ...              töeqo          NaN
598    šïïnö        1     0  ...              töeqo          NaN
599    šïïnö        1     0  ...              töeqo          NaN
600    töeqo        0     0  ...              töeqo            z
601    šïïnö        1     0  ...              töeqo            z
602    šïïnö        1     0  ...              töeqo            z

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
594               NaN          NaN               NaN          NaN
595               NaN          NaN               NaN          NaN
596               NaN          NaN               NaN          NaN
597               NaN          NaN               NaN          NaN
598               NaN          NaN               NaN          NaN
599               NaN          NaN               NaN          NaN
600             yaöpe          NaN               NaN          NaN
601             yaöpe          NaN               NaN          NaN
602             yaöpe          NaN               NaN        False

    button_number trial_index time_elapsed     rt
594             1         100      1303091   7401
595             1         101      1321597  18505
596             1         102      1324415   2817
597             1         103      1325748   1332
598             1         104      1331800   6050
599             1         105      1332950   1149
600             0         106      1345504  12553
601             1         107      1349723   4217
602             1         108      1358641   8918

[9 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
578  ccehyx1t6d      fmgb      3       1   critical      fbd  egezalat
579  ccehyx1t6d      fmgb      3       1   critical      fzd  egezalat
580  ccehyx1t6d      fmgb      3       1   critical      mbs      otev
581  ccehyx1t6d      fmgb      3       1   critical      mzd      otev
582  ccehyx1t6d      fmgb      3       1      catch      mzs      otev
583  ccehyx1t6d      fmgb      3       1   critical      fzs  egezalat
584  ccehyx1t6d      fmgb      3       1   critical      mbd      otev

     expected  correct  undo  ...  generaliser2_term generaliser3  \
578  egezalat        1     0  ...               otev          NaN
579  egezalat        1     0  ...               otev          NaN
580      otev        1     0  ...               otev          NaN
581      otev        1     0  ...               otev          NaN
582      otev        1     0  ...               otev          NaN
583  egezalat        1     0  ...               otev          NaN
584      otev        1     0  ...               otev          NaN

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
578               NaN          NaN               NaN          NaN
579               NaN          NaN               NaN          NaN
580               NaN          NaN               NaN          NaN
581               NaN          NaN               NaN          NaN
582               NaN          NaN               NaN        False
583               NaN          NaN               NaN          NaN
584               NaN          NaN               NaN          NaN

    button_number trial_index time_elapsed     rt
578             0          64      1034692   9285
579             0          65      1039159   4466
580             2          66      1046029   6868
581             2          67      1047996   1966
582             2          68      1092359  44363
583             0          69      1155796  63435
584             2          70      1165966  10169

[7 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
612  ccehyx1t6d      fmgb      7       2   critical      mbs    goviku
613  ccehyx1t6d      fmgb      7       2   critical      fbs    pygele
614  ccehyx1t6d      fmgb      7       2   critical      mbd    goviku
615  ccehyx1t6d      fmgb      7       2   critical      fzd    pygele
616  ccehyx1t6d      fmgb      7       2      catch      mzs    goviku
617  ccehyx1t6d      fmgb      7       2   critical      mzd    goviku
618  ccehyx1t6d      fmgb      7       2   critical      fzs    pygele

    expected  correct  undo  ...  generaliser2_term generaliser3  \
612   pygele        0     0  ...             goviku          NaN
613   pygele        1     0  ...             goviku          NaN
614   pygele        0     0  ...             goviku          NaN
615   goviku        0     0  ...             goviku          NaN
616   goviku        1     0  ...             goviku          NaN
617   goviku        1     0  ...             goviku          NaN
618   goviku        0     0  ...             goviku          NaN

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
612               NaN          NaN               NaN          NaN
613               NaN          NaN               NaN          NaN
614               NaN          NaN               NaN          NaN
615               NaN          NaN               NaN          NaN
616               NaN          NaN               NaN        False
617               NaN          NaN               NaN          NaN
618               NaN          NaN               NaN          NaN

    button_number trial_index time_elapsed     rt
612             3         140      1485714  12153
613             0         141      1489549   3833
614             3         142      1493383   3833
615             0         143      1496084   2700
616             3         144      1502452   6367
617             3         145      1509639   7185
618             0         146      1512072   2432

[7 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
604  ccehyx1t6d      fmgb      6       3   critical      fzs     nžodo
605  ccehyx1t6d      fmgb      6       3   critical      fbs     nžodo
606  ccehyx1t6d      fmgb      6       3   critical      mzs  vropcāre
607  ccehyx1t6d      fmgb      6       3   critical      mbd     nžodo
608  ccehyx1t6d      fmgb      6       3   critical      fzd     nžodo
609  ccehyx1t6d      fmgb      6       3      catch      mbs     nžodo
610  ccehyx1t6d      fmgb      6       3   critical      fbd     nžodo

     expected  correct  undo  ...  generaliser2_term generaliser3  \
604     nžodo        1     0  ...           vropcāre          NaN
605  vropcāre        0     0  ...           vropcāre          NaN
606  vropcāre        1     0  ...           vropcāre          NaN
607     nžodo        1     0  ...           vropcāre          NaN
608     nžodo        1     0  ...           vropcāre          NaN
609     nžodo        1     0  ...           vropcāre          NaN
610  vropcāre        0     0  ...           vropcāre          NaN

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
604               NaN          NaN               NaN          NaN
605               NaN          NaN               NaN          NaN
606               NaN          NaN               NaN          NaN
607               NaN          NaN               NaN          NaN
608               NaN          NaN               NaN          NaN
609               NaN          NaN               NaN        False
610               NaN          NaN               NaN          NaN

    button_number trial_index time_elapsed     rt
604             0         121      1416226   9619
605             0         122      1423778   7551
606             3         123      1439166  15387
607             0         124      1442167   3000
608             0         125      1444635   2466
609             0         126      1449820   5184
610             0         127      1453570   3749

[7 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
570  ccehyx1t6d      fmgb      2       4   critical      mzd       qăo
571  ccehyx1t6d      fmgb      2       4   critical      fzd       gêă
572  ccehyx1t6d      fmgb      2       4   critical      fzs       gêă
573  ccehyx1t6d      fmgb      2       4      catch      mzs       qăo
574  ccehyx1t6d      fmgb      2       4   critical      mbs       qăo
575  ccehyx1t6d      fmgb      2       4   critical      fbd       gêă
576  ccehyx1t6d      fmgb      2       4   critical      mbd       qăo

    expected  correct  undo  ...  generaliser2_term generaliser3  \
570      qăo        1     0  ...                qăo          NaN
571      qăo        0     0  ...                qăo          NaN
572      qăo        0     0  ...                qăo          NaN
573      qăo        1     0  ...                qăo          NaN
574      qăo        1     0  ...                qăo          NaN
575      gêă        1     0  ...                qăo          NaN
576      qăo        1     0  ...                qăo          NaN

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
570               NaN          NaN               NaN          NaN
571               NaN          NaN               NaN          NaN
572               NaN          NaN               NaN          NaN
573               NaN          NaN               NaN        False
574               NaN          NaN               NaN          NaN
575               NaN          NaN               NaN          NaN
576               NaN          NaN               NaN          NaN

    button_number trial_index time_elapsed     rt
570             1          45       899634  26936
571             0          46       903885   4247
572             0          47       958185  54299
573             1          48       967004   8818
574             1          49       976707   9702
575             0          50       980642   3934
576             1          51       989245   8602

[7 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
620  ccehyx1t6d      fmgb      8       5   critical      mzd      rhåv
621  ccehyx1t6d      fmgb      8       5   critical      fzs  tsåvvses
622  ccehyx1t6d      fmgb      8       5   critical      mzs  tsåvvses
623  ccehyx1t6d      fmgb      8       5      catch      fbs  tsåvvses
624  ccehyx1t6d      fmgb      8       5   critical      fbd      rhåv
625  ccehyx1t6d      fmgb      8       5   critical      mbd      rhåv
626  ccehyx1t6d      fmgb      8       5   critical      mbs  tsåvvses

     expected  correct  undo  ...  generaliser2_term generaliser3  \
620  tsåvvses        0     0  ...           tsåvvses          NaN
621      rhåv        0     0  ...           tsåvvses          NaN
622  tsåvvses        1     0  ...           tsåvvses          NaN
623  tsåvvses        1     0  ...           tsåvvses          NaN
624  tsåvvses        0     0  ...           tsåvvses          NaN
625  tsåvvses        0     0  ...           tsåvvses          NaN
626  tsåvvses        1     0  ...           tsåvvses          NaN

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
620               NaN          NaN               NaN          NaN
621               NaN          NaN               NaN          NaN
622               NaN          NaN               NaN          NaN
623               NaN          NaN               NaN        False
624               NaN          NaN               NaN          NaN
625               NaN          NaN               NaN          NaN
626               NaN          NaN               NaN          NaN

    button_number trial_index time_elapsed    rt
620             2         159      1547600  6318
621             3         160      1552918  5317
622             3         161      1556652  3733
623             3         162      1561904  5250
624             2         163      1564972  3067
625             2         164      1566222  1249
626             3         165      1567972  1749

[7 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
562  ccehyx1t6d      fmgb      1       6   critical      mzd    hïlaki
563  ccehyx1t6d      fmgb      1       6   critical      fbd    hïlaki
564  ccehyx1t6d      fmgb      1       6   critical      mbd    morïky
565  ccehyx1t6d      fmgb      1       6   critical      fzd    hïlaki
566  ccehyx1t6d      fmgb      1       6   critical      fzs    hïlaki
567  ccehyx1t6d      fmgb      1       6   critical      mzs    morïky
568  ccehyx1t6d      fmgb      1       6      catch      mbs    morïky

    expected  correct  undo  ...  generaliser2_term generaliser3  \
562   hïlaki        1     0  ...             hïlaki          NaN
563   hïlaki        1     0  ...             hïlaki          NaN
564   morïky        1     0  ...             hïlaki          NaN
565   hïlaki        1     0  ...             hïlaki          NaN
566   hïlaki        1     0  ...             hïlaki          NaN
567   hïlaki        0     0  ...             hïlaki          NaN
568   morïky        1     0  ...             hïlaki          NaN

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
562               NaN          NaN               NaN          NaN
563               NaN          NaN               NaN          NaN
564               NaN          NaN               NaN          NaN
565               NaN          NaN               NaN          NaN
566               NaN          NaN               NaN          NaN
567               NaN          NaN               NaN          NaN
568               NaN          NaN               NaN        False

    button_number trial_index time_elapsed     rt
562             3          26       681949  40309
563             3          27       702739  20787
564             1          28       716127  13387
565             3          29       724680   8552
566             3          30       760424  35743
567             1          31       779347  18922
568             1          32       815091  35743

[7 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
586  ccehyx1t6d      fmgb      4       7      catch      fzd    emøyeç
587  ccehyx1t6d      fmgb      4       7   critical      mbs      iqur
588  ccehyx1t6d      fmgb      4       7   critical      mbd      iqur
589  ccehyx1t6d      fmgb      4       7   critical      fbd    emøyeç
590  ccehyx1t6d      fmgb      4       7   critical      fbs    emøyeç
591  ccehyx1t6d      fmgb      4       7   critical      fzs    emøyeç
592  ccehyx1t6d      fmgb      4       7   critical      mzd      iqur

    expected  correct  undo  ...  generaliser2_term generaliser3  \
586   emøyeç        1     0  ...             emøyeç          NaN
587   emøyeç        0     0  ...             emøyeç          NaN
588   emøyeç        0     0  ...             emøyeç          NaN
589   emøyeç        1     0  ...             emøyeç          NaN

       random_id condition  block  system trial_type selectee selection  \
1210  96dcxvnjng      mfgb      7       4   critical      fbs    adeçim
1211  96dcxvnjng      mfgb      7       4   critical      fzs    adeçim
1212  96dcxvnjng      mfgb      7       4   critical      fzd    adeçim
1213  96dcxvnjng      mfgb      7       4   critical      mzs    adeçim
1214  96dcxvnjng      mfgb      7       4   critical      mbd    adeçim
1215  96dcxvnjng      mfgb      7       4      catch      fbd    adeçim
1216  96dcxvnjng      mfgb      7       4   critical      mzd    adeçim

      expected  correct  undo  ...  generaliser2_term generaliser3  \
1210    adeçim        1     0  ...           orinoçim          NaN
1211  orinoçim        0     0  ...           orinoçim          NaN
1212  orinoçim        0     0  ...           orinoçim          NaN
1213  orinoçim        0     0  ...           orinoçim          NaN
1214  orinoçim        0     0  ...           orinoçim          NaN
1215    adeçim        1     0  ...           orinoçim          NaN
1216  orinoçim        0     0  ...           orinoçim          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1210               NaN          NaN               NaN          NaN
1211               NaN          NaN               NaN          NaN
1212               NaN          NaN               NaN          NaN
1213               NaN          NaN               NaN          NaN
1214               NaN          NaN               NaN          NaN
1215               NaN          NaN               NaN        False
1216               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed    rt
1210             2         140      1133538  4955
1211             2         141      1141958  8415
1212             2         142      1145685  3719
1213             2         143      1153586  7894
1214             2         144      1161156  7560
1215             2         145      1170264  9100
1216             2         146      1173388  3116

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1178  96dcxvnjng      mfgb      3       5   critical      mbs      kïmy
1179  96dcxvnjng      mfgb      3       5   critical      fbd    morïky
1180  96dcxvnjng      mfgb      3       5   critical      mbd      kïmy
1181  96dcxvnjng      mfgb      3       5   critical      mzs      kïmy
1182  96dcxvnjng      mfgb      3       5   critical      fzs    morïky
1183  96dcxvnjng      mfgb      3       5      catch      mzd      kïmy
1184  96dcxvnjng      mfgb      3       5   critical      fbs    morïky

     expected  correct  undo  ...  generaliser2_term generaliser3  \
1178     kïmy        1     0  ...               kïmy          NaN
1179     kïmy        0     0  ...               kïmy          NaN
1180     kïmy        1     0  ...               kïmy          NaN
1181     kïmy        1     0  ...               kïmy          NaN
1182   morïky        1     0  ...               kïmy          NaN
1183     kïmy        1     0  ...               kïmy          NaN
1184     kïmy        0     0  ...               kïmy          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1178               NaN          NaN               NaN          NaN
1179               NaN          NaN               NaN          NaN
1180               NaN          NaN               NaN          NaN
1181               NaN          NaN               NaN          NaN
1182               NaN          NaN               NaN          NaN
1183               NaN          NaN               NaN        False
1184               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed     rt
1178             2          64       680420  17698
1179             3          65       713934  33510
1180             2          66       716245   2302
1181             2          67       717908   1656
1182             3          68       728311  10395
1183             2          69       731862   3542
1184             3          70       733456   1591

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1202  96dcxvnjng      mfgb      6       6   critical      mzd      svik
1203  96dcxvnjng      mfgb      6       6   critical      mbd      svik
1204  96dcxvnjng      mfgb      6       6      catch      fzs      svik
1205  96dcxvnjng      mfgb      6       6   critical      fbs  tsåvvses
1206  96dcxvnjng      mfgb      6       6   critical      mzs  tsåvvses
1207  96dcxvnjng      mfgb      6       6   critical      fbd      svik
1208  96dcxvnjng      mfgb      6       6   critical      fzd  tsåvvses

      expected  correct  undo  ...  generaliser2_term generaliser3  \
1202      svik        1     0  ...               svik          NaN
1203  tsåvvses        0     0  ...               svik          NaN
1204      svik        1     0  ...               svik          NaN
1205      svik        0     0  ...               svik          NaN
1206      svik        0     0  ...               svik          NaN
1207      svik        1     0  ...               svik          NaN
1208      svik        0     0  ...               svik          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1202               NaN          NaN               NaN          NaN
1203               NaN          NaN               NaN          NaN
1204               NaN          NaN               NaN        False
1205               NaN          NaN               NaN          NaN
1206               NaN          NaN               NaN          NaN
1207               NaN          NaN               NaN          NaN
1208               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed    rt
1202             1         121      1047064  9347
1203             1         122      1054545  7474
1204             1         123      1061011  6459
1205             2         124      1063794  2775
1206             2         125      1065702  1898
1207             1         126      1068737  3026
1208             2         127      1077295  8550

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1170  96dcxvnjng      mfgb      2       7   critical      fbs    goozăi
1171  96dcxvnjng      mfgb      2       7   critical      fzs    goozăi
1172  96dcxvnjng      mfgb      2       7   critical      mzd    niuhiê
1173  96dcxvnjng      mfgb      2       7      catch      mzs    niuhiê
1174  96dcxvnjng      mfgb      2       7   critical      mbs    niuhiê
1175  96dcxvnjng      mfgb      2       7   critical      mbd    niuhiê
1176  96dcxvnjng      mfgb      2       7   critical      fzd    goozăi

     expected  correct  undo  ...  generaliser2_term generaliser3  \
1170   goozăi        1     0  ...             goozăi          NaN
1171   goozăi        1     0  ...             goozăi          NaN
1172   niuhiê        1     0  ...             goozăi          NaN
1173   niuhiê        1     0  ...             goozăi          NaN
1174   goozăi        0     0  ...             goozăi          NaN
1175   goozăi        0     0  ...             goozăi          NaN
1176   goozăi        1     0  ...             goozăi          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1170               NaN          NaN               NaN          NaN
1171               NaN          NaN               NaN          NaN
1172               NaN          NaN               NaN          NaN
1173               NaN          NaN               NaN        False
1174               NaN          NaN               NaN          NaN
1175               NaN          NaN               NaN          NaN
1176               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed     rt
1170             3          45       475437  92788
1171             3          46       478053   2610
1172             2          47       480889   2824
1173             2          48       488160   7263
1174             2          49       493664   5494
1175             2          50       495877   2204
1176             3          51       498530   2647

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1674  sspwqxgdcc      mfgb      4       0   critical      mbs  idanuluf
1675  sspwqxgdcc      mfgb      4       0   critical      fzd  idanuluf
1676  sspwqxgdcc      mfgb      4       0   critical      mzd  idanuluf
1677  sspwqxgdcc      mfgb      4       0   critical      mbd  idanuluf
1678  sspwqxgdcc      mfgb      4       0      catch        z    ozatof
1679  sspwqxgdcc      mfgb      4       0   critical      fbd  idanuluf
1680  sspwqxgdcc      mfgb      4       0   critical      fbs  idanuluf
1681  sspwqxgdcc      mfgb      4       0   critical      fzs  idanuluf
1682  sspwqxgdcc      mfgb      4       0   critical        b    ozatof

      expected  correct  undo  ...  generaliser2_term generaliser3  \
1674  idanuluf        1     0  ...             ozatof          NaN
1675  idanuluf        1     0  ...             ozatof          NaN
1676  idanuluf        1     0  ...             ozatof          NaN
1677  idanuluf        1     0  ...             ozatof          NaN
1678    ozatof        1     0  ...             ozatof          NaN
1679  idanuluf        1     0  ...             ozatof          NaN
1680  idanuluf        1     0  ...             ozatof          NaN
1681  idanuluf        1     0  ...             ozatof          NaN
1682    ozatof        1     0  ...             ozatof          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1674               NaN          NaN               NaN          NaN
1675               NaN          NaN               NaN          NaN
1676               NaN          NaN               NaN          NaN
1677               NaN          NaN               NaN          NaN
1678               NaN          NaN               NaN        False
1679               NaN          NaN               NaN          NaN
1680               NaN          NaN               NaN          NaN
1681               NaN          NaN               NaN          NaN
1682               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed     rt
1674             0          91       575097   8699
1675             0          92       597897  22796
1676             0          93       599381   1482
1677             0          94       601481   2099
1678             2          95       606948   5465
1679             0          96       608680   1730
1680             0          97       610030   1348
1681             0          98       611599   1567
1682             2          99       620248   8648

[9 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1708  sspwqxgdcc      mfgb      8       1   critical      fzs     pžicā
1709  sspwqxgdcc      mfgb      8       1   critical      fbs     pžicā
1710  sspwqxgdcc      mfgb      8       1   critical      mbs    ngcāžo
1711  sspwqxgdcc      mfgb      8       1   critical      fzd     pžicā
1712  sspwqxgdcc      mfgb      8       1   critical      mzd    ngcāžo
1713  sspwqxgdcc      mfgb      8       1      catch      mzs    ngcāžo
1714  sspwqxgdcc      mfgb      8       1   critical      mbd    ngcāžo

     expected  correct  undo  ...  generaliser2_term generaliser3  \
1708    pžicā        1     0  ...             ngcāžo          NaN
1709    pžicā        1     0  ...             ngcāžo          NaN
1710   ngcāžo        1     0  ...             ngcāžo          NaN
1711    pžicā        1     0  ...             ngcāžo          NaN
1712   ngcāžo        1     0  ...             ngcāžo          NaN
1713   ngcāžo        1     0  ...             ngcāžo          NaN
1714   ngcāžo        1     0  ...             ngcāžo          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1708               NaN          NaN               NaN          NaN
1709               NaN          NaN               NaN          NaN
1710               NaN          NaN               NaN          NaN
1711               NaN          NaN               NaN          NaN
1712               NaN          NaN               NaN          NaN
1713               NaN          NaN               NaN        False
1714               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed    rt
1708             3         169       789383  2716
1709             3         170       790748  1362
1710             2         171       794317  3567
1711             3         172       796649  2330
1712             2         173       798349  1698
1713             2         174       801599  3248
1714             2         175       802799  1198

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1658  sspwqxgdcc      mfgb      2       2   critical      mbs    morïky
1659  sspwqxgdcc      mfgb      2       2   critical      mzd  męwaqïfe
1660  sspwqxgdcc      mfgb      2       2   critical      fbs    morïky
1661  sspwqxgdcc      mfgb      2       2   critical      mzs  męwaqïfe
1662  sspwqxgdcc      mfgb      2       2      catch      fzd  męwaqïfe
1663  sspwqxgdcc      mfgb      2       2   critical      fzs  męwaqïfe
1664  sspwqxgdcc      mfgb      2       2   critical      fbd    morïky

      expected  correct  undo  ...  generaliser2_term generaliser3  \
1658    morïky        1     0  ...           męwaqïfe          NaN
1659  męwaqïfe        1     0  ...           męwaqïfe          NaN
1660    morïky        1     0  ...           męwaqïfe          NaN
1661  męwaqïfe        1     0  ...           męwaqïfe          NaN
1662  męwaqïfe        1     0  ...           męwaqïfe          NaN
1663  męwaqïfe        1     0  ...           męwaqïfe          NaN
1664    morïky        1     0  ...           męwaqïfe          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1658               NaN          NaN               NaN          NaN
1659               NaN          NaN               NaN          NaN
1660               NaN          NaN               NaN          NaN
1661               NaN          NaN               NaN          NaN
1662               NaN          NaN               NaN        False
1663               NaN          NaN               NaN          NaN
1664               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed    rt
1658             0          55       389061  8565
1659             1          56       397846  8782
1660             0          57       401262  3414
1661             1          58       403278  2014
1662             1          59       410545  7264
1663             1          60       415061  4515
1664             0          61       416862  1799

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1666  sspwqxgdcc      mfgb      3       3   critical      mbd    lawolu
1667  sspwqxgdcc      mfgb      3       3   critical      fzd    lawolu
1668  sspwqxgdcc      mfgb      3       3   critical      fbs    goviku
1669  sspwqxgdcc      mfgb      3       3   critical      mzs    goviku
1670  sspwqxgdcc      mfgb      3       3   critical      mzd    goviku
1671  sspwqxgdcc      mfgb      3       3      catch      fzs    lawolu
1672  sspwqxgdcc      mfgb      3       3   critical      mbs    lawolu

     expected  correct  undo  ...  generaliser2_term generaliser3  \
1666   lawolu        1     0  ...             goviku          NaN
1667   lawolu        1     0  ...             goviku          NaN
1668   goviku        1     0  ...             goviku          NaN
1669   goviku        1     0  ...             goviku          NaN
1670   goviku        1     0  ...             goviku          NaN
1671   lawolu        1     0  ...             goviku          NaN
1672   lawolu        1     0  ...             goviku          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1666               NaN          NaN               NaN          NaN
1667               NaN          NaN               NaN          NaN
1668               NaN          NaN               NaN          NaN
1669               NaN          NaN               NaN          NaN
1670               NaN          NaN               NaN          NaN
1671               NaN          NaN               NaN        False
1672               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed    rt
1666             0          74       511664  9765
1667             0          75       517079  5414
1668             3          76       519295  2214
1669             3          77       522479  3182
1670             3          78       523762  1282
1671             0          79       531463  7699
1672             0          80       537663  6198

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1640  sspwqxgdcc      mfgb      1       4      catch      mbs  orinoçim
1641  sspwqxgdcc      mfgb      1       4   critical      mzs  orinoçim
1642  sspwqxgdcc      mfgb      1       4   critical      fzd    emøyeç
1643  sspwqxgdcc      mfgb      1       4   critical      mbd  orinoçim
1644  sspwqxgdcc      mfgb      1       4   critical      fbd    emøyeç
1645  sspwqxgdcc      mfgb      1       4   critical      fzs    emøyeç
1646  sspwqxgdcc      mfgb      1       4   critical      mzd  orinoçim
1652  sspwqxgdcc      mfgb      1       4   critical      fzd  orinoçim
1653  sspwqxgdcc      mfgb      1       4   critical      mbd  orinoçim
1654  sspwqxgdcc      mfgb      1       4   critical      fbd    emøyeç
1655  sspwqxgdcc      mfgb      1       4   critical      fzs  orinoçim
1656  sspwqxgdcc      mfgb      1       4   critical      mzd  orinoçim

      expected  correct  undo  ...  generaliser2_term generaliser3  \
1640  orinoçim        1     0  ...           orinoçim          NaN
1641  orinoçim        1     0  ...           orinoçim          NaN
1642  orinoçim        0     0  ...           orinoçim          NaN
1643  orinoçim        1     0  ...           orinoçim          NaN
1644    emøyeç        1     0  ...           orinoçim          NaN
1645  orinoçim        0     0  ...           orinoçim          NaN
1646  orinoçim        1     0  ...           orinoçim          NaN
1652  orinoçim        1     0  ...           orinoçim          NaN
1653  orinoçim        1     0  ...           orinoçim          NaN
1654    emøyeç        1     0  ...           orinoçim          NaN
1655  orinoçim        1     0  ...           orinoçim          NaN
1656  orinoçim        1     0  ...           orinoçim          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1640               NaN          NaN               NaN        False
1641               NaN          NaN               NaN          NaN
1642               NaN          NaN               NaN          NaN
1643               NaN          NaN               NaN          NaN
1644               NaN          NaN               NaN          NaN
1645               NaN          NaN               NaN          NaN
1646               NaN          NaN               NaN          NaN
1652               NaN          NaN               NaN          NaN
1653               NaN          NaN               NaN          NaN
1654               NaN          NaN               NaN          NaN
1655               NaN          NaN               NaN          NaN
1656               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed     rt
1640             1          26       207692   7297

      random_id condition  block  system trial_type selectee selection  \
628  3fs5m6cp2b      mfbg      1       5   critical      fbd    awupav
629  3fs5m6cp2b      mfbg      1       5      catch      mzd    awupav
630  3fs5m6cp2b      mfbg      1       5   critical      fbs    awupav
631  3fs5m6cp2b      mfbg      1       5   critical      mbd    awupav
632  3fs5m6cp2b      mfbg      1       5   critical      mzs    awupav
633  3fs5m6cp2b      mfbg      1       5   critical      mbs    awupav
634  3fs5m6cp2b      mfbg      1       5   critical      fzd      ilug

    expected  correct  undo  ...  generaliser2_term generaliser3  \
628   awupav        1     0  ...             awupav          NaN
629   awupav        1     0  ...             awupav          NaN
630   awupav        1     0  ...             awupav          NaN
631   awupav        1     0  ...             awupav          NaN
632   awupav        1     0  ...             awupav          NaN
633   awupav        1     0  ...             awupav          NaN
634     ilug        1     0  ...             awupav          NaN

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
628               NaN          NaN               NaN          NaN
629               NaN          NaN               NaN        False
630               NaN          NaN               NaN          NaN
631               NaN          NaN               NaN          NaN
632               NaN          NaN               NaN          NaN
633               NaN          NaN               NaN          NaN
634               NaN          NaN               NaN          NaN

    button_number trial_index time_elapsed     rt
628             3          26       166359  12206
629             3          27       182309  15727
630             3          28       197095  14782
631             3          29       207587  10488
632             3          30       214553   6961
633             3          31       216508   1950
634             1          32       218201   1687

[7 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
704  3fs5m6cp2b      mfbg      8       6   critical      fzd    pygele
706  3fs5m6cp2b      mfbg      8       6   critical      fzd    goviku
707  3fs5m6cp2b      mfbg      8       6   critical      fbs      luge
708  3fs5m6cp2b      mfbg      8       6   critical      fzs      luge
709  3fs5m6cp2b      mfbg      8       6   critical      mbs    pygele
710  3fs5m6cp2b      mfbg      8       6   critical      mzs      luge
711  3fs5m6cp2b      mfbg      8       6      catch      fbd    goviku
712  3fs5m6cp2b      mfbg      8       6   critical      mzd    goviku

    expected  correct  undo  ...  generaliser2_term generaliser3  \
704   goviku        0     0  ...             goviku          fzd
706   goviku        1     0  ...             goviku          fzd
707   goviku        0     0  ...             goviku          fzd
708   goviku        0     0  ...             goviku          fzd
709  ngapapu        0     0  ...             goviku          fzd
710   goviku        0     0  ...             goviku          fzd
711   goviku        1     0  ...             goviku          fzd
712   goviku        1     0  ...             goviku          fzd

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
704            pygele          NaN               NaN          NaN
706            pygele          NaN               NaN          NaN
707            pygele          fbs              luge          NaN
708            pygele          fbs              luge          NaN
709            pygele          fbs              luge          NaN
710            pygele          fbs              luge          NaN
711            pygele          fbs              luge        False
712            pygele          fbs              luge          NaN

    button_number trial_index time_elapsed    rt
704             0         177       823212  9758
706             2         179       832611  2390
707             1         180       836206  3592
708             1         181       837619  1409
709             0         182       843283  5660
710             1         183       847153  3865
711             2         184       848302  1145
712             2         185       849810  1504

[8 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
678  3fs5m6cp2b      mfbg      5       7   critical      fbd  canšuehu
679  3fs5m6cp2b      mfbg      5       7   critical      fzs  canšuehu
680  3fs5m6cp2b      mfbg      5       7   critical      fzd  canšuehu
681  3fs5m6cp2b      mfbg      5       7   critical      mbd  canšuehu
682  3fs5m6cp2b      mfbg      5       7      catch      mzd     yaöpe
683  3fs5m6cp2b      mfbg      5       7   critical      mzs     yaöpe
684  3fs5m6cp2b      mfbg      5       7   critical      fbs  canšuehu

     expected  correct  undo  ...  generaliser2_term generaliser3  \
678  canšuehu        1     0  ...           canšuehu          NaN
679  canšuehu        1     0  ...           canšuehu          NaN
680  canšuehu        1     0  ...           canšuehu          NaN
681  canšuehu        1     0  ...           canšuehu          NaN
682     yaöpe        1     0  ...           canšuehu          NaN
683     yaöpe        1     0  ...           canšuehu          NaN
684  canšuehu        1     0  ...           canšuehu          NaN

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
678               NaN          NaN               NaN          NaN
679               NaN          NaN               NaN          NaN
680               NaN          NaN               NaN          NaN
681               NaN          NaN               NaN          NaN
682               NaN          NaN               NaN        False
683               NaN          NaN               NaN          NaN
684               NaN          NaN               NaN          NaN

    button_number trial_index time_elapsed    rt
678             2         120       649939  3918
679             2         121       658627  8684
680             2         122       660003  1372
681             2         123       661834  1826
682             3         124       664184  2347
683             3         125       665128   940
684             2         126       667244  2113

[7 rows x 24 columns]
     random_id condition  block  system trial_type selectee selection  \
8   9r62k0regr      mfgb      2       0   critical      fbd   popingi
9   9r62k0regr      mfgb      2       0   critical      fzs   ngapapu
10  9r62k0regr      mfgb      2       0   critical      fbs    lepego
11  9r62k0regr      mfgb      2       0      catch        z    kawuka
12  9r62k0regr      mfgb      2       0   critical      fzd   popingi
13  9r62k0regr      mfgb      2       0   critical      mbd   popingi
14  9r62k0regr      mfgb      2       0   critical      mbs    lepego
15  9r62k0regr      mfgb      2       0   critical      mzd   popingi
16  9r62k0regr      mfgb      2       0   critical        b    kawuka

   expected  correct  undo  ...  generaliser2_term generaliser3  \
8   ngapapu        0     0  ...             kawuka          fbd
9   ngapapu        1     0  ...             kawuka          fbd
10  ngapapu        0     0  ...             kawuka          fbd
11   kawuka        1     0  ...             kawuka          fbd
12  ngapapu        0     0  ...             kawuka          fbd
13  ngapapu        0     0  ...             kawuka          fbd
14  ngapapu        0     0  ...             kawuka          fbd
15  ngapapu        0     0  ...             kawuka          fbd
16   kawuka        1     0  ...             kawuka          fbd

   generaliser3_term generaliser4 generaliser4_term catch_failed  \
8            popingi          NaN               NaN          NaN
9            popingi          NaN               NaN          NaN
10           popingi          fbs            lepego          NaN
11           popingi          fbs            lepego        False
12           popingi          fbs            lepego          NaN
13           popingi          fbs            lepego          NaN
14           popingi          fbs            lepego          NaN
15           popingi          fbs            lepego          NaN
16           popingi          fbs            lepego          NaN

   button_number trial_index time_elapsed     rt
8              2          43       126883    185
9              0          44       139531  12647
10             3          45       145398   5866
11             1          46       147454   2055
12             2          47       153556   6101
13             2          48       157972   4415
14             3          49       159944   1971
15             2          50       163635   3690
16             1          51       177553  13916

[9 rows x 24 columns]
     random_id condition  block  system trial_type selectee selection  \
18  9r62k0regr      mfgb      3       1      catch      fzs   sfêvdok
19  9r62k0regr      mfgb      3       1   critical      fbs      rhåv
20  9r62k0regr      mfgb      3       1   critical      mbd  rhymsvåd
21  9r62k0regr      mfgb      3       1   critical      fzd  rhymsvåd
22  9r62k0regr      mfgb      3       1   critical      mzs      rhåv
23  9r62k0regr      mfgb      3       1   critical      mzd  rhymsvåd
24  9r62k0regr      mfgb      3       1   critical      fbd  rhymsvåd

   expected  correct  undo  ...  generaliser2_term generaliser3  \
18  sfêvdok        1     0  ...               vrêd          NaN
19  sfêvdok        0     0  ...               vrêd          fbs
20     vrêd        0     0  ...               vrêd          fbs
21  sfêvdok        0     0  ...               vrêd          fbs
22     vrêd        0     0  ...               vrêd          fbs
23     vrêd        0     0  ...               vrêd          fbs
24  sfêvdok        0     0  ...               vrêd          fbs

   generaliser3_term generaliser4 generaliser4_term catch_failed  \
18               NaN          NaN               NaN        False
19              rhåv          NaN               NaN          NaN
20              rhåv          mbd          rhymsvåd          NaN
21              rhåv          mbd          rhymsvåd          NaN
22              rhåv          mbd          rhymsvåd          NaN
23              rhåv          mbd          rhymsvåd          NaN
24              rhåv          mbd          rhymsvåd          NaN

   button_number trial_index time_elapsed     rt
18             0          64       188765   2232
19             3          65       201327  12561
20             2          66       210569   9240
21             2          67       221205  10635
22             3          68       224161   2956
23             2          69       226404   2242
24             2          70       227686   1281

[7 rows x 24 columns]
     random_id condition  block  system trial_type selectee selection  \
58  9r62k0regr      mfgb      8       2   critical      fzs    morïky
59  9r62k0regr      mfgb      8       2   critical      mzd  męwaqïfe
60  9r62k0regr      mfgb      8       2   critical      mzs    morïky
61  9r62k0regr      mfgb      8       2   critical      fbd  bokokohï
62  9r62k0regr      mfgb      8       2      catch      mbs    hïlaki
63  9r62k0regr      mfgb      8       2   critical      mbd  bokokohï
64  9r62k0regr      mfgb      8       2   critical      fbs    hïlaki

    expected  correct  undo  ...  generaliser2_term generaliser3  \
58  męwaqïfe        0     0  ...           męwaqïfe          fzs
59  męwaqïfe        1     0  ...           męwaqïfe          fzs
60  męwaqïfe        0     0  ...           męwaqïfe          fzs
61    hïlaki        0     0  ...           męwaqïfe          fzs
62    hïlaki        1     0  ...           męwaqïfe          fzs
63    hïlaki        0     0  ...           męwaqïfe          fzs
64    hïlaki        1     0  ...           męwaqïfe          fzs

   generaliser3_term generaliser4 generaliser4_term catch_failed  \
58            morïky          NaN               NaN          NaN
59            morïky          NaN               NaN          NaN
60            morïky          NaN               NaN          NaN
61            morïky          fbd          bokokohï          NaN
62            morïky          fbd          bokokohï        False
63            morïky          fbd          bokokohï          NaN
64            morïky          fbd          bokokohï          NaN

   button_number trial_index time_elapsed    rt
58             1         159       439782  6024
59             3         160       445492  5709
60             1         161       446660  1167
61             0         162       456356  9695
62             2         163       458266  1909
63             0         164       460200  1933
64             2         165       462435  2234

[7 rows x 24 columns]
     random_id condition  block  system trial_type selectee selection  \
42  9r62k0regr      mfgb      6       3   critical      fzs      azuf
43  9r62k0regr      mfgb      6       3   critical      fbd    agivud
44  9r62k0regr      mfgb      6       3      catch      mbd      ilug
45  9r62k0regr      mfgb      6       3   critical      fbs    ulywaf
46  9r62k0regr      mfgb      6       3   critical      mbs    ulywaf
47  9r62k0regr      mfgb      6       3   critical      mzs      azuf
48  9r62k0regr      mfgb      6       3   critical      fzd    ulywaf

   expected  correct  undo  ...  generaliser2_term generaliser3  \
42     ilug        0     0  ...             ulywaf          fzs
43   ulywaf        0     0  ...             ulywaf          fzs
44     ilug        1     0  ...             ulywaf          fzs
45   ulywaf        1     0  ...             ulywaf          fzs
46     ilug        0     0  ...             ulywaf          fzs
47   ulywaf        0     0  ...             ulywaf          fzs
48     ilug        0     0  ...             ulywaf          fzs

   generaliser3_term generaliser4 generaliser4_term catch_failed  \
42              azuf          NaN               NaN          NaN
43              azuf          NaN               NaN          NaN
44              azuf          NaN               NaN        False
45              azuf          NaN               NaN          NaN
46              azuf          NaN               NaN          NaN
47              azuf          mzs              azuf          NaN
48              azuf          mzs              azuf          NaN

   button_number trial_index time_elapsed    rt
42             2         121       357383  8302
43             0         122       362049  4665
44             1         123       363789  1739
45             3         124       372305  8515
46             3         125       374687  2381
47             2         126       379808  5120
48             3         127       386201  6392

[7 rows x 24 columns]
    random_id condition  block  system trial_type selectee selection  \
0  9r62k0regr      mfgb      1       4   critical      fbs    ømenad
1  9r62k0regr      mfgb      1       4   critical      mbd  içiqusem
2  9r62k0regr      mfgb      1       4      catch      fbd    ømenad
3  9r62k0regr      mfgb      1       4   critical      mbs  içiqusem
4  9r62k0regr      mfgb      1       4   critical      mzs    ømenad
5  9r62k0regr      mfgb      1       4   critical      fzd  içiqusem
6  9r62k0regr      mfgb      1       4   critical      mzd    ømenad

   expected  correct  undo  ...  generaliser2_term generaliser3  \
0    ømenad        1     0  ...           içiqusem          NaN
1  içiqusem        1     0  ...           içiqusem          NaN
2    ømenad        1     0  ...           içiqusem          NaN
3  içiqusem        1     0  ...           içiqusem          NaN
4  içiqusem        0     0  ...           içiqusem          NaN
5  içiqusem        1     0  ...           içiqusem          NaN
6  içiqusem        0     0  ...           içiqusem          NaN

  generaliser3_term generaliser4 generaliser4_term catch_failed button_number  \
0               NaN          NaN               NaN          NaN             1
1               NaN          NaN               NaN          NaN             0
2               NaN          NaN               NaN        False             1
3               NaN          NaN               NaN          NaN             0
4               NaN          NaN               NaN          NaN             1
5               NaN          NaN               NaN          NaN             0
6               NaN          NaN               NaN          NaN             1

  trial_index time_elapsed     rt
0          26        81201   5669
1          27        91492  10289
2          28        96483   4990
3          29       106017   9533
4          30       112457   6439
5          31       117248   4790
6          32       118890   1641

[7 rows x 24 columns]
     random_id condition  block  system trial_type selectee selection  \
50  9r62k0regr      mfgb      7       5   critical      fzd     vbāžo
51  9r62k0regr      mfgb      7       5   critical      mbs     pžicā
52  9r62k0regr      mfgb      7       5   critical      mzd     vbāžo
53  9r62k0regr      mfgb      7       5   critical      mzs    ngcāžo
54  9r62k0regr      mfgb      7       5   critical      fbs     pžicā
55  9r62k0regr      mfgb      7       5      catch      mbd     pžicā
56  9r62k0regr      mfgb      7       5   critical      fbd     pžicā

   expected  correct  undo  ...  generaliser2_term generaliser3  \
50   ngcāžo        0     0  ...              pžicā          fzd
51    pžicā        1     0  ...              pžicā          fzd
52    pžicā        0     0  ...              pžicā          fzd
53    pžicā        0     0  ...              pžicā          fzd
54    pžicā        1     0  ...              pžicā          fzd
55    pžicā        1     0  ...              pžicā          fzd
56    pžicā        1     0  ...              pžicā          fzd

   generaliser3_term generaliser4 generaliser4_term catch_failed  \
50             vbāžo          NaN               NaN          NaN
51             vbāžo          NaN               NaN          NaN
52             vbāžo          NaN               NaN          NaN
53             vbāžo          NaN               NaN          NaN
54             vbāžo          NaN               NaN          NaN
55             vbāžo          NaN               NaN        False
56             vbāžo          NaN               NaN          NaN

   button_number trial_index time_elapsed    rt
50             1         140       399948  7680
51             3         141       408675  8726
52             1         142       417231  8555
53             0         143       419749  2517
54             3         144       423514  3764
55             3         145       425212  1697
56             3         146       426666  1453

[7 rows x 24 columns]
     random_id condition  block  system trial_type selectee selection  \
26  9r62k0regr      mfgb      4       6   critical      mzd  canšuehu
27  9r62k0regr      mfgb      4       6   critical      fbd  beiguumu
28  9r62k0regr      mfgb      4       6   critical      fbs  canšuehu
29  9r62k0regr      mfgb      4       6   critical      fzd  canšuehu
30  9r62k0regr      mfgb      4       6   critical      mzs  šaaqaude
31  9r62k0regr      mfgb      4       6      catch      fzs  šaaqaude
32  9r62k0regr      mfgb      4       6   critical      mbd  canšuehu

    expected  correct  undo  ...  generaliser2_term generaliser3  \
26  šaaqaude        0     0  ...           šaaqaude          NaN
27  šaaqaude        0     0  ...           šaaqaude          fbd
28  šaaqaude        0     0  ...           šaaqaude          fbd
29  šaaqaude        0     0  ...           šaaqaude          fbd
30  šaaqaude        1     0  ...           šaaqaude          fbd
31  šaaqaude        1     0  ...           šaaqaude          fbd

      random_id condition  block  system trial_type selectee  selection  \
476  xxzu4htn68      mfbg      7       0   critical      mbs  powisunge
477  xxzu4htn68      mfbg      7       0   critical      mzd       wupu
478  xxzu4htn68      mfbg      7       0   critical      fzs     pygele
479  xxzu4htn68      mfbg      7       0   critical      fzd     pygele
480  xxzu4htn68      mfbg      7       0   critical      mzs       wupu
481  xxzu4htn68      mfbg      7       0   critical        z    popingi
482  xxzu4htn68      mfbg      7       0   critical      fbs     pygele
483  xxzu4htn68      mfbg      7       0   critical      fbd     pygele
484  xxzu4htn68      mfbg      7       0      catch        b    popingi

      expected  correct  undo  ...  generaliser2_term generaliser3  \
476  powisunge        1     0  ...            popingi          NaN
477  powisunge        0     0  ...            popingi          mzd
478  powisunge        0     0  ...            popingi          mzd
479  powisunge        0     0  ...            popingi          mzd
480  powisunge        0     0  ...            popingi          mzd
481    popingi        1     0  ...            popingi          mzd
482  powisunge        0     0  ...            popingi          mzd
483  powisunge        0     0  ...            popingi          mzd
484    popingi        1     0  ...            popingi          mzd

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
476               NaN          NaN               NaN          NaN
477              wupu          NaN               NaN          NaN
478              wupu          fzs            pygele          NaN
479              wupu          fzs            pygele          NaN
480              wupu          fzs            pygele          NaN
481              wupu          fzs            pygele          NaN
482              wupu          fzs            pygele          NaN
483              wupu          fzs            pygele          NaN
484              wupu          fzs            pygele        False

    button_number trial_index time_elapsed     rt
476             1         142      1687744  19730
477             0         143      1695209   7462
478             3         144      1710413  15201
479             3         145      1715787   5371
480             0         146      1721472   5683
481             2         147      1730095   8621
482             3         148      1746259  16161
483             3         149      1746931    670
484             2         150      1754024   7091

[9 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
468  xxzu4htn68      mfbg      6       1   critical      mbd      øqoç
469  xxzu4htn68      mfbg      6       1   critical      mzd      øqoç
470  xxzu4htn68      mfbg      6       1   critical      fzs    adeçim
471  xxzu4htn68      mfbg      6       1   critical      fbd  orinoçim
472  xxzu4htn68      mfbg      6       1      catch      mzs    ømenad
473  xxzu4htn68      mfbg      6       1   critical      fzd  orinoçim
474  xxzu4htn68      mfbg      6       1   critical      mbs    ømenad

    expected  correct  undo  ...  generaliser2_term generaliser3  \
468   ømenad        0     0  ...             ømenad          mbd
469   ømenad        0     0  ...             ømenad          mbd
470   adeçim        1     0  ...             ømenad          mbd
471   adeçim        0     0  ...             ømenad          mbd
472   ømenad        1     0  ...             ømenad          mbd
473   adeçim        0     0  ...             ømenad          mbd
474   ømenad        1     0  ...             ømenad          mbd

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
468              øqoç          NaN               NaN          NaN
469              øqoç          mzd              øqoç          NaN
470              øqoç          mzd              øqoç          NaN
471              øqoç          mzd              øqoç          NaN
472              øqoç          mzd              øqoç        False
473              øqoç          mzd              øqoç          NaN
474              øqoç          mzd              øqoç          NaN

    button_number trial_index time_elapsed     rt
468             1         125      1595819  36362
469             1         126      1606741  10919
470             0         127      1611331   4588
471             2         128      1624007  12674
472             3         129      1632727   8718
473             2         130      1635515   2785
474             3         131      1641810   6294

[7 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
424  xxzu4htn68      mfbg      1       2   critical      mzs  vropcāre
425  xxzu4htn68      mfbg      1       2   critical      mbs  rbāranžā
426  xxzu4htn68      mfbg      1       2   critical      mbd     pžicā
427  xxzu4htn68      mfbg      1       2      catch      fbs  rbāranžā
428  xxzu4htn68      mfbg      1       2   critical      mzd    cžunge
429  xxzu4htn68      mfbg      1       2   critical      fzd    cžunge
430  xxzu4htn68      mfbg      1       2   critical      fbd     pžicā

     expected  correct  undo  ...  generaliser2_term generaliser3  \
424  vropcāre        1     0  ...           vropcāre          NaN
425  rbāranžā        1     0  ...           vropcāre          NaN
426  rbāranžā        0     0  ...           vropcāre          mbd
427  rbāranžā        1     0  ...           vropcāre          mbd
428  vropcāre        0     0  ...           vropcāre          mbd
429  vropcāre        0     0  ...           vropcāre          mbd
430  rbāranžā        0     0  ...           vropcāre          mbd

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
424               NaN          NaN               NaN          NaN
425               NaN          NaN               NaN          NaN
426             pžicā          NaN               NaN          NaN
427             pžicā          NaN               NaN        False
428             pžicā          NaN               NaN          NaN
429             pžicā          NaN               NaN          NaN
430             pžicā          fbd             pžicā          NaN

    button_number trial_index time_elapsed     rt
424             1          26       617116  25531
425             0          27       637912  20793
426             3          28       665044  27129
427             0          29       677314  12267
428             2          30       729521  52205
429             2          31       756544  27020
430             3          32       764040   7493

[7 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
460  xxzu4htn68      mfbg      5       3      catch      mbd    niuhiê
461  xxzu4htn68      mfbg      5       3   critical      fzd    niuhiê
462  xxzu4htn68      mfbg      5       3   critical      mzd    nyumuo
463  xxzu4htn68      mfbg      5       3   critical      mbs    goozăi
464  xxzu4htn68      mfbg      5       3   critical      mzs    hyonăo
465  xxzu4htn68      mfbg      5       3   critical      fzs    goozăi
466  xxzu4htn68      mfbg      5       3   critical      fbs    hyonăo

    expected  correct  undo  ...  generaliser2_term generaliser3  \
460   niuhiê        1     0  ...             nyumuo          NaN
461   niuhiê        1     0  ...             nyumuo          NaN
462   nyumuo        1     0  ...             nyumuo          NaN
463   niuhiê        0     0  ...             nyumuo          mbs
464   nyumuo        0     0  ...             nyumuo          mbs
465   niuhiê        0     0  ...             nyumuo          mbs
466   nyumuo        0     0  ...             nyumuo          mbs

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
460               NaN          NaN               NaN        False
461               NaN          NaN               NaN          NaN
462               NaN          NaN               NaN          NaN
463            goozăi          NaN               NaN          NaN
464            goozăi          NaN               NaN          NaN
465            goozăi          fzs            goozăi          NaN
466            goozăi          fzs            goozăi          NaN

    button_number trial_index time_elapsed     rt
460             3         106      1394815   5723
461             3         107      1436811  41994
462             2         108      1448732  11918
463             0         109      1467683  18948
464             1         110      1473793   6108
465             0         111      1509615  35819
466             1         112      1519021   9403

[7 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
444  xxzu4htn68      mfbg      3       4   critical      mbs     töeqo
445  xxzu4htn68      mfbg      3       4   critical      mbd     töeqo
446  xxzu4htn68      mfbg      3       4   critical      fzd     yaöpe
447  xxzu4htn68      mfbg      3       4   critical      mzs     töeqo
448  xxzu4htn68      mfbg      3       4   critical      mzd     töeqo
449  xxzu4htn68      mfbg      3       4      catch      fzs     töeqo
450  xxzu4htn68      mfbg      3       4   critical      fbd     yaöpe

    expected  correct  undo  ...  generaliser2_term generaliser3  \
444    töeqo        1     0  ...              töeqo          NaN
445    töeqo        1     0  ...              töeqo          NaN
446    töeqo        0     0  ...              töeqo          fzd
447    töeqo        1     0  ...              töeqo          fzd
448    töeqo        1     0  ...              töeqo          fzd
449    töeqo        1     0  ...              töeqo          fzd
450    nuubö        0     0  ...              töeqo          fzd

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
444               NaN          NaN               NaN          NaN
445               NaN          NaN               NaN          NaN
446             yaöpe          NaN               NaN          NaN
447             yaöpe          NaN               NaN          NaN
448             yaöpe          NaN               NaN          NaN
449             yaöpe          NaN               NaN        False
450             yaöpe          NaN               NaN          NaN

    button_number trial_index time_elapsed     rt
444             2          68      1130180  17654
445             2          69      1154481  24298
446             3          70      1169623  15140
447             2          71      1178010   8384
448             2          72      1179639   1627
449             2          73      1187292   7651
450             3          74      1194634   7338

[7 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
452  xxzu4htn68      mfbg      4       5   critical      mbd  tsåvvses
453  xxzu4htn68      mfbg      4       5   critical      fbd  tsåvvses
454  xxzu4htn68      mfbg      4       5   critical      fzs      rhåv
455  xxzu4htn68      mfbg      4       5   critical      mbs   sfêvdok
456  xxzu4htn68      mfbg      4       5      catch      fzd      rhåv
457  xxzu4htn68      mfbg      4       5   critical      mzd  tsåvvses
458  xxzu4htn68      mfbg      4       5   critical      fbs      rhåv

    expected  correct  undo  ...  generaliser2_term generaliser3  \
452  sfêvdok        0     0  ...            sfêvdok          mbd
453  sfêvdok        0     0  ...            sfêvdok          mbd
454     rhåv        1     0  ...            sfêvdok          mbd
455  sfêvdok        1     0  ...            sfêvdok          mbd
456     rhåv        1     0  ...            sfêvdok          mbd
457  sfêvdok        0     0  ...            sfêvdok          mbd
458  sfêvdok        0     0  ...            sfêvdok          mbd

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
452          tsåvvses          NaN               NaN          NaN
453          tsåvvses          fbd          tsåvvses          NaN
454          tsåvvses          fbd          tsåvvses          NaN
455          tsåvvses          fbd          tsåvvses          NaN
456          tsåvvses          fbd          tsåvvses        False
457          tsåvvses          fbd          tsåvvses          NaN
458          tsåvvses          fbd          tsåvvses          NaN

    button_number trial_index time_elapsed     rt
452             0          87      1249272  15453
453             0          88      1255905   6630
454             2          89      1264231   8324
455             1          90      1269881   5647
456             2          91      1280684  10801
457             0          92      1294474  13788
458             2          93      1300074   5598

[7 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
486  xxzu4htn68      mfbg      8       6   critical      fbd    agivud
487  xxzu4htn68      mfbg      8       6      catch      fzd    agivud
488  xxzu4htn68      mfbg      8       6   critical      fbs      ilug
489  xxzu4htn68      mfbg      8       6   critical      fzs      ilug
490  xxzu4htn68      mfbg      8       6   critical      mbs    awupav
491  xxzu4htn68      mfbg      8       6   critical      mzd      azuf
492  xxzu4htn68      mfbg      8       6   critical      mzs    awupav

    expected  correct  undo  ...  generaliser2_term generaliser3  \
486   agivud        1     0  ...             agivud          NaN
487   agivud        1     0  ...             agivud          NaN
488   agivud        0     0  ...             agivud          fbs
489   agivud        0     0  ...             agivud          fbs
490     azuf        0     0  ...             agivud          fbs
491   agivud        0     0  ...             agivud          fbs
492   agivud        0     0  ...             agivud          fbs

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
486               NaN          NaN               NaN          NaN
487               NaN          NaN               NaN        False
488              ilug          NaN               NaN          NaN
489              ilug          NaN               NaN          NaN
490              ilug          mbs            awupav          NaN
491              ilug          mbs            awupav          NaN
492              ilug          mbs            awupav          NaN

    button_number trial_index time_elapsed     rt
486             1         163      1803114  21502
487             1         164      1806436   3320
488             0         165      1813370   6931
489             0         166      1814775   1403
490             3         167      1825752  10974
491             2         168      1830318   4564
492             3         169      1832372   2051

[7 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
432  xxzu4htn68      mfbg      2       7   critical      fbd      bybï
433  xxzu4htn68      mfbg      2       7   critical      fzd      bybï
434  xxzu4htn68      mfbg      2       7      catch      mbd      bybï
437  xxzu4htn68      mfbg      2       7   critical      fbd  bokokohï
438  xxzu4htn68      mfbg      2       7   critical      fzd  bokokohï
439  xxzu4htn68      mfbg      2       7   critical      fbs    zuvewu
440  xxzu4htn68      mfbg      2       7   critical      mbs  lobowaby
441  xxzu4htn68      mfbg      2       7   critical      fzs    zuvewu
442  xxzu4htn68      mfbg      2       7   critical      mzd      bybï

     expected  correct  undo  ...  generaliser2_term generaliser3  \
432      bybï        1     0  ...               bybï          NaN
433      bybï        1     0  ...               bybï          NaN
434      bybï        1     0  ...               bybï          NaN
437      bybï        0     0  ...               bybï          fbd
438      bybï        0     0  ...               bybï          fbd
439      bybï        0     0  ...               bybï          fbd
440      bybï        0     0  ...               bybï          fbd
441      bybï        0     0  ...               bybï          fbd
442  lobowaby        0     0  ...               bybï          fbd

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
432               NaN          NaN               NaN          NaN
433               NaN          NaN               NaN          NaN
434               NaN          NaN               NaN        False
437          bokokohï          NaN               NaN          NaN
438          bokokohï          NaN               NaN          NaN
439          bokokohï          fbs            zuvewu          NaN
440          bokokohï          fbs            zuvewu          NaN
441          bokokohï          fbs            zuvewu          NaN
442          bokokohï          fbs            zuvewu          NaN

    button_number trial_index time_elapsed     rt
432             2          45       866429  18923
433             2          46       892744  26312
434             2          47       920006  27259
437             1          50      1032454  42195
438             1          51      1036807   4350
439             3          52      1042803   5993
440             0          53      1048241   5435
441             3          54      1052520   4276
442             2          55      1054896   2374

[9 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2667  9drp8p96ut      mfbg      7       0   critical      fbs      bybï
2668  9drp8p96ut      mfbg      7       0   critical        b      bybï
2669  9drp8p96ut      mfbg      7       0      catch      mbd      bybï
2670  9drp8p96ut      mfbg      7       0   critical      mbs      bybï
2671  9drp8p96ut      mfbg      7       0   critical      mzd      bybï
2672  9drp8p96ut      mfbg      7       0   critical      fbd      bybï
2673  9drp8p96ut      mfbg      7       0   critical      fzs      bybï
2674  9drp8p96ut      mfbg      7       0   critical      mzs      bybï
2675  9drp8p96ut      mfbg      7       0   critical      fzd      bybï

      expected  correct  undo  ...  generaliser2_term generaliser3  \
2667      bybï        1     0  ...           bokokohï          NaN
2668  bokokohï        0     0  ...           bokokohï          NaN
2669      bybï        1     0  ...           bokokohï          NaN
2670      bybï        1     0  ...           bokokohï          NaN
2671      bybï        1     0  ...           bokokohï          NaN
2672      bybï        1     0  ...           bokokohï          NaN
2673      bybï        1     0  ...           bokokohï          NaN
2674      bybï        1     0  ...           bokokohï          NaN
2675      bybï        1     0  ...           bokokohï          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2667               NaN          NaN               NaN          NaN
2668               NaN          NaN               NaN          NaN
2669               NaN          NaN               NaN        False
2670               NaN          NaN               NaN          NaN
2671               NaN          NaN               NaN          NaN
2672               NaN          NaN               NaN          NaN
2673               NaN          NaN               NaN          NaN
2674               NaN          NaN               NaN          NaN
2675               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed    rt
2667             2         138       461854  4471
2668             2         139       463196  1341
2669             2         140       464770  1573
2670             2         141       466242  1470
2671             2         142       470548  4305
2672             2         143       472024  1474
2673             2         144       473334  1308
2674             2         145       473990   655

       random_id condition  block  system trial_type selectee selection  \
2677  9drp8p96ut      mfbg      8       6   critical      mzd   sfêvdok
2678  9drp8p96ut      mfbg      8       6   critical      mzs   sfêvdok
2679  9drp8p96ut      mfbg      8       6   critical      fzd   sfêvdok
2680  9drp8p96ut      mfbg      8       6   critical      mbs  kvurddåh
2681  9drp8p96ut      mfbg      8       6   critical      fzs   sfêvdok
2682  9drp8p96ut      mfbg      8       6      catch      fbs   sfêvdok
2683  9drp8p96ut      mfbg      8       6   critical      fbd   sfêvdok

      expected  correct  undo  ...  generaliser2_term generaliser3  \
2677   sfêvdok        1     0  ...            sfêvdok          NaN
2678   sfêvdok        1     0  ...            sfêvdok          NaN
2679   sfêvdok        1     0  ...            sfêvdok          NaN
2680  kvurddåh        1     0  ...            sfêvdok          NaN
2681   sfêvdok        1     0  ...            sfêvdok          NaN
2682   sfêvdok        1     0  ...            sfêvdok          NaN
2683   sfêvdok        1     0  ...            sfêvdok          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2677               NaN          NaN               NaN          NaN
2678               NaN          NaN               NaN          NaN
2679               NaN          NaN               NaN          NaN
2680               NaN          NaN               NaN          NaN
2681               NaN          NaN               NaN          NaN
2682               NaN          NaN               NaN        False
2683               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed    rt
2677             0         159       506814  7375
2678             0         160       508424  1609
2679             0         161       510430  2005
2680             1         162       512132  1700
2681             0         163       514562  2429
2682             0         164       515800  1237
2683             0         165       516256   455

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2643  9drp8p96ut      mfbg      4       7   critical      fzd    pygele
2644  9drp8p96ut      mfbg      4       7   critical      mbd    pygele
2645  9drp8p96ut      mfbg      4       7   critical      fbs    pygele
2646  9drp8p96ut      mfbg      4       7   critical      mzd    goviku
2647  9drp8p96ut      mfbg      4       7      catch      mbs    pygele
2648  9drp8p96ut      mfbg      4       7   critical      fbd    pygele
2649  9drp8p96ut      mfbg      4       7   critical      fzs    pygele

     expected  correct  undo  ...  generaliser2_term generaliser3  \
2643   pygele        1     0  ...             pygele          NaN
2644   pygele        1     0  ...             pygele          NaN
2645   pygele        1     0  ...             pygele          NaN
2646   goviku        1     0  ...             pygele          NaN
2647   pygele        1     0  ...             pygele          NaN
2648   pygele        1     0  ...             pygele          NaN
2649   pygele        1     0  ...             pygele          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2643               NaN          NaN               NaN          NaN
2644               NaN          NaN               NaN          NaN
2645               NaN          NaN               NaN          NaN
2646               NaN          NaN               NaN          NaN
2647               NaN          NaN               NaN        False
2648               NaN          NaN               NaN          NaN
2649               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed     rt
2643             3          83       329818   6207
2644             3          84       342639  12820
2645             3          85       344557   1917
2646             1          86       347643   3085
2647             3          87       349649   2005
2648             3          88       351473   1823
2649             3          89       352209    735

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1142  rxzy9xwpkp      fmbg      7       0   critical      fbd    baumiă
1143  rxzy9xwpkp      fmbg      7       0   critical      fbs    baumiă
1144  rxzy9xwpkp      fmbg      7       0   critical      mzs    baumiă
1145  rxzy9xwpkp      fmbg      7       0   critical      fzd    baumiă
1146  rxzy9xwpkp      fmbg      7       0   critical      fzs    baumiă
1147  rxzy9xwpkp      fmbg      7       0   critical      mbd    baumiă
1148  rxzy9xwpkp      fmbg      7       0   critical        z    baumiă
1149  rxzy9xwpkp      fmbg      7       0   critical      mzd    baumiă
1150  rxzy9xwpkp      fmbg      7       0      catch      mbs    baumiă

     expected  correct  undo  ...  generaliser2_term generaliser3  \
1142   baumiă        1     0  ...             nyumuo          NaN
1143   baumiă        1     0  ...             nyumuo          NaN
1144   baumiă        1     0  ...             nyumuo          NaN
1145   baumiă        1     0  ...             nyumuo          NaN
1146   baumiă        1     0  ...             nyumuo          NaN
1147   baumiă        1     0  ...             nyumuo          NaN
1148   nyumuo        0     0  ...             nyumuo          NaN
1149   baumiă        1     0  ...             nyumuo          NaN
1150   baumiă        1     0  ...             nyumuo          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1142               NaN          NaN               NaN          NaN
1143               NaN          NaN               NaN          NaN
1144               NaN          NaN               NaN          NaN
1145               NaN          NaN               NaN          NaN
1146               NaN          NaN               NaN          NaN
1147               NaN          NaN               NaN          NaN
1148               NaN          NaN               NaN          NaN
1149               NaN          NaN               NaN          NaN
1150               NaN          NaN               NaN        False

     button_number trial_index time_elapsed     rt
1142             1         174      1203512  13816
1143             1         175      1208199   4686
1144             1         176      1209000    799
1145             1         177      1209488    488
1146             1         178      1211272   1783
1147             1         179      1211968    695
1148             1         180      1212632    663
1149             1         181      1213231    598
1150             1         182      1220087   6855

[9 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1098  rxzy9xwpkp      fmbg      4       1   critical      fzd    uquçun
1099  rxzy9xwpkp      fmbg      4       1   critical      mbd  orinoçim
1100  rxzy9xwpkp      fmbg      4       1      catch      mbs  orinoçim
1101  rxzy9xwpkp      fmbg      4       1   critical      mzd  orinoçim
1102  rxzy9xwpkp      fmbg      4       1   critical      fzs    uquçun
1103  rxzy9xwpkp      fmbg      4       1   critical      mzs  orinoçim
1104  rxzy9xwpkp      fmbg      4       1   critical      fbd    uquçun

      expected  correct  undo  ...  generaliser2_term generaliser3  \
1098    uquçun        1     0  ...           orinoçim          NaN
1099  orinoçim        1     0  ...           orinoçim          NaN
1100  orinoçim        1     0  ...           orinoçim          NaN
1101  orinoçim        1     0  ...           orinoçim          NaN
1102    uquçun        1     0  ...           orinoçim          NaN
1103  orinoçim        1     0  ...           orinoçim          NaN
1104    uquçun        1     0  ...           orinoçim          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1098               NaN          NaN               NaN          NaN
1099               NaN          NaN               NaN          NaN
1100               NaN          NaN               NaN        False
1101               NaN          NaN               NaN          NaN
1102               NaN          NaN               NaN          NaN
1103               NaN          NaN               NaN          NaN
1104               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed     rt
1098             0          99       955760  18455
1099             2         100       958160   2399
1100             2         101       960016   1855
1101             2         102       961688   1671
1102             0         103       965080   3391
1103             2         104       966736   1656
1104             0         105       970688   3951

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1086  rxzy9xwpkp      fmbg      3       2   critical      mzs    morïky
1087  rxzy9xwpkp      fmbg      3       2   critical      fbs    morïky
1088  rxzy9xwpkp      fmbg      3       2      catch      fzd      kïmy
1089  rxzy9xwpkp      fmbg      3       2   critical      fbd      kïmy
1090  rxzy9xwpkp      fmbg      3       2   critical      mbd      kïmy
1091  rxzy9xwpkp      fmbg      3       2   critical      mzd      kïmy
1094  rxzy9xwpkp      fmbg      3       2   critical      mbd    hïlaki
1095  rxzy9xwpkp      fmbg      3       2   critical      mzd    hïlaki
1096  rxzy9xwpkp      fmbg      3       2   critical      fzs    hïlaki

     expected  correct  undo  ...  generaliser2_term generaliser3  \
1086     kïmy        0     0  ...               kïmy          NaN
1087   morïky        1     0  ...               kïmy          NaN
1088     kïmy        1     0  ...               kïmy          NaN
1089   morïky        0     0  ...               kïmy          NaN
1090   morïky        0     0  ...               kïmy          NaN
1091     kïmy        1     0  ...               kïmy          NaN
1094   morïky        0     0  ...               kïmy          mbd
1095     kïmy        0     0  ...               kïmy          mbd
1096     kïmy        0     0  ...               kïmy          mbd

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1086               NaN          NaN               NaN          NaN
1087               NaN          NaN               NaN          NaN
1088               NaN          NaN               NaN        False
1089               NaN          NaN               NaN          NaN
1090               NaN          NaN               NaN          NaN
1091               NaN          NaN               NaN          NaN
1094            hïlaki          NaN               NaN          NaN
1095            hïlaki          NaN               NaN          NaN
1096            hïlaki          NaN               NaN          NaN

     button_number trial_index time_elapsed     rt
1086             3          76       896817  12319
1087             3          77       899185   2367
1088             2          78       905322   6136
1089             2          79       908081   2758
1090             2          80       910657   2575
1091             2          81       912209   1552
1094             0          84       921944   4062
1095             0          85       923603   1657
1096             0          86       924848   1245

[9 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1152  rxzy9xwpkp      fmbg      8       3   critical      mbd    agivud
1153  rxzy9xwpkp      fmbg      8       3   critical      mzd    agivud
1154  rxzy9xwpkp      fmbg      8       3   critical      fbd  egezalat
1155  rxzy9xwpkp      fmbg      8       3   critical      fzd  egezalat
1156  rxzy9xwpkp      fmbg      8       3      catch      mbs    etupol
1157  rxzy9xwpkp      fmbg      8       3   critical      mzs    etupol
1158  rxzy9xwpkp      fmbg      8       3   critical      fzs  idanuluf

      expected  correct  undo  ...  generaliser2_term generaliser3  \
1152    etupol        0     0  ...           idanuluf          mbd
1153  idanuluf        0     0  ...           idanuluf          mbd
1154  idanuluf        0     0  ...           idanuluf          mbd
1155    etupol        0     0  ...           idanuluf          mbd
1156    etupol        1     0  ...           idanuluf          mbd
1157  idanuluf        0     0  ...           idanuluf          mbd
1158    etupol        0     0  ...           idanuluf          mbd

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1152            agivud          NaN               NaN          NaN
1153            agivud          NaN               NaN          NaN
1154            agivud          fbd          egezalat          NaN
1155            agivud          fbd          egezalat          NaN
1156            agivud          fbd          egezalat        False
1157            agivud          fbd          egezalat          NaN
1158            agivud          fbd          egezalat          NaN

     button_number trial_index time_elapsed     rt
1152             1         195      1250943  12831
1153             1         196      1252999   2055
1154             3         197      1255263   2264
1155             3         198      1256711   1447
1156             0         199      1261239   4527
1157             0         200      1269519   8279
1158             2         201      1272687   3168

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1058  rxzy9xwpkp      fmbg      1       4      catch      fzd  rhymsvåd
1059  rxzy9xwpkp      fmbg      1       4   critical      fzs  rhymsvåd
1060  rxzy9xwpkp      fmbg      1       4   critical      mbd  rhymsvåd
1061  rxzy9xwpkp      fmbg      1       4   critical      fbs  smêvskêv
1062  rxzy9xwpkp      fmbg      1       4   critical      mbs  rhymsvåd
1063  rxzy9xwpkp      fmbg      1       4   critical      mzs  rhymsvåd
1064  rxzy9xwpkp      fmbg      1       4   critical      mzd  rhymsvåd

      expected  correct  undo  ...  generaliser2_term generaliser3  \
1058  rhymsvåd        1     0  ...           rhymsvåd          NaN
1059  rhymsvåd        1     0  ...           rhymsvåd          NaN
1060  rhymsvåd        1     0  ...           rhymsvåd          NaN
1061  smêvskêv        1     0  ...           rhymsvåd          NaN
1062  rhymsvåd        1     0  ...           rhymsvåd          NaN
1063  rhymsvåd        1     0  ...           rhymsvåd          NaN
1064  rhymsvåd        1     0  ...           rhymsvåd          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1058               NaN          NaN               NaN        False
1059               NaN          NaN               NaN          NaN
1060               NaN          NaN               NaN          NaN
1061               NaN          NaN               NaN          NaN
1062               NaN          NaN               NaN          NaN
1063               NaN          NaN               NaN          NaN
1064               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed     rt
1058             0          26       685801  15607
1059             0          27       702713  16910
1060             0          28       721777  19063
1061             2          29       730811   9033
1062             0          30       732713   1901
1063             0          31       736961   4247
1064             0          32       738281   1319

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1106  rxzy9xwpkp      fmbg      5       5   critical      fbs     pžicā
1107  rxzy9xwpkp      fmbg      5       5   critical      mzs  vropcāre
1108  rxzy9xwpkp      fmbg      5       5   critical      mbs     pžicā
1109  rxzy9xwpkp      fmbg      5       5   critical      fbd  vropcāre
1110  rxzy9xwpkp      fmbg      5       5      catch      mbd  vropcāre
1111  rxzy9xwpkp      fmbg      5       5   critical      mzd     pžicā
1112  rxzy9xwpkp      fmbg      5       5   critical      fzs     pžicā
1115  rxzy9xwpkp      fmbg      5       5   critical      mzd  vropcāre
1116  rxzy9xwpkp      fmbg      5       5   critical      fzs     pžicā

      expected  correct  undo  ...  generaliser2_term generaliser3  \
1106  vropcāre        0     0  ...           vropcāre          NaN
1107  vropcāre        1     0  ...           vropcāre          NaN
1108  vropcāre        0     0  ...           vropcāre          NaN
1109  vropcāre        1     0  ...           vropcāre          NaN
1110  vropcāre        1     0  ...           vropcāre          NaN
1111  vropcāre        0     0  ...           vropcāre          NaN
1112     pžicā        1     0  ...           vropcāre          NaN
1115  vropcāre        1     0  ...           vropcāre          NaN
1116     pžicā        1     0  ...           vropcāre          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1106               NaN          NaN               NaN          NaN
1107               NaN          NaN               NaN          NaN
1108               NaN          NaN               NaN          NaN
1109               NaN          NaN               NaN          NaN
1110               NaN          NaN               NaN        False
1111               NaN          NaN               NaN          NaN
1112               NaN          NaN               NaN          NaN
1115               NaN          NaN               NaN          NaN
1116               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed    rt
1106             1         118       989568  6471
1107             0         119       992977  3407
1108             1         120       997408  4431
1109             0         121       999608  2199
1110             0         122      1003992  4383
1111             1         123      1007320  3327
1112             1         124      1010529  3207
1115             0         127      1033144  8926
1116             1         128      1036601  3455

[9 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1066  rxzy9xwpkp      fmbg      2       6   critical      fbs    goviku
1067  rxzy9xwpkp      fmbg      2       6   critical      mbs      luge
1068  rxzy9xwpkp      fmbg      2       6   critical      fzd    goviku
1069  rxzy9xwpkp      fmbg      2       6      catch      mbd      luge
1070  rxzy9xwpkp      fmbg      2       6   critical      mzs      wupu
1071  rxzy9xwpkp      fmbg      2       6   critical      fbd      wupu
1074  rxzy9xwpkp      fmbg      2       6   critical      mzs    goviku
1075  rxzy9xwpkp      fmbg      2       6   critical      fbd    goviku
1078  rxzy9xwpkp      fmbg      2       6   critical      mzs      luge
1079  rxzy9xwpkp      fmbg      2       6   critical      fbd      luge
1081  rxzy9xwpkp      fmbg      2       6   critical      fbd      wupu
1083  rxzy9xwpkp      fmbg      2       6   critical      fbd    goviku
1084  rxzy9xwpkp      fmbg      2       6   critical      mzd      wupu

     expected  correct  undo  ...  generaliser2_term generaliser3  \
1066   goviku        1     0  ...             goviku          NaN
1067     luge        1     0  ...             goviku          NaN
1068   goviku        1     0  ...             goviku          NaN
1069     luge        1     0  ...             goviku          NaN
1070   goviku        0     0  ...             goviku          mzs
1071   goviku        0     0  ...             goviku          mzs
1074   goviku        1     0  ...             goviku          mzs
1075   goviku        1     0  ...             goviku          mzs
1078   goviku        0     0  ...             goviku          mzs
1079   goviku        0     0  ...             goviku          mzs

       random_id condition  block  system trial_type selectee selection  \
1242  3efko77scp      fmgb      3       1   critical      fzd     žbodu
1243  3efko77scp      fmgb      3       1   critical      mbs     nžodo
1244  3efko77scp      fmgb      3       1   critical      fbd     žbodu
1245  3efko77scp      fmgb      3       1   critical      mzs     nžodo
1246  3efko77scp      fmgb      3       1   critical      fbs     nžodo
1247  3efko77scp      fmgb      3       1      catch      mzd     žbodu
1248  3efko77scp      fmgb      3       1   critical      mbd     žbodu

     expected  correct  undo  ...  generaliser2_term generaliser3  \
1242    nžodo        0     0  ...              žbodu          NaN
1243    žbodu        0     0  ...              žbodu          NaN
1244    nžodo        0     0  ...              žbodu          NaN
1245    žbodu        0     0  ...              žbodu          NaN
1246    nžodo        1     0  ...              žbodu          NaN
1247    žbodu        1     0  ...              žbodu          NaN
1248    žbodu        1     0  ...              žbodu          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1242               NaN          NaN               NaN          NaN
1243               NaN          NaN               NaN          NaN
1244               NaN          NaN               NaN          NaN
1245               NaN          NaN               NaN          NaN
1246               NaN          NaN               NaN          NaN
1247               NaN          NaN               NaN        False
1248               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed     rt
1242             1          64       378247  18742
1243             3          65       382121   3871
1244             1          66       386631   4508
1245             3          67       392889   6255
1246             3          68       395271   2380
1247             1          69       400086   4813
1248             1          70       402494   2406

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1266  3efko77scp      fmgb      6       2   critical      mbs     möïtu
1267  3efko77scp      fmgb      6       2   critical      mbd     töeqo
1268  3efko77scp      fmgb      6       2   critical      fzs     yaöpe
1269  3efko77scp      fmgb      6       2      catch      fbd  canšuehu
1270  3efko77scp      fmgb      6       2   critical      mzs     möïtu
1271  3efko77scp      fmgb      6       2   critical      fzd  canšuehu
1272  3efko77scp      fmgb      6       2   critical      fbs     yaöpe

      expected  correct  undo  ...  generaliser2_term generaliser3  \
1266  canšuehu        0     0  ...              töeqo          mbs
1267  canšuehu        0     0  ...              töeqo          mbs
1268     töeqo        0     0  ...              töeqo          mbs
1269  canšuehu        1     0  ...              töeqo          mbs
1270     töeqo        0     0  ...              töeqo          mbs
1271     töeqo        0     0  ...              töeqo          mbs
1272  canšuehu        0     0  ...              töeqo          mbs

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1266             möïtu          NaN               NaN          NaN
1267             möïtu          NaN               NaN          NaN
1268             möïtu          fzs             yaöpe          NaN
1269             möïtu          fzs             yaöpe        False
1270             möïtu          fzs             yaöpe          NaN
1271             möïtu          fzs             yaöpe          NaN
1272             möïtu          fzs             yaöpe          NaN

     button_number trial_index time_elapsed     rt
1266             1         121       548515  23226
1267             0         122       550796   2278
1268             3         123       556454   5656
1269             2         124       558581   2125
1270             1         125       561385   2801
1271             2         126       564302   2915
1272             3         127       566850   2546

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1226  3efko77scp      fmgb      1       3      catch      mzs    ømenad
1227  3efko77scp      fmgb      1       3   critical      mbd    adeçim
1228  3efko77scp      fmgb      1       3   critical      fbs    ømenad
1229  3efko77scp      fmgb      1       3   critical      fzs    adeçim
1230  3efko77scp      fmgb      1       3   critical      fbd      iqur
1231  3efko77scp      fmgb      1       3   critical      mbs    uquçun
1232  3efko77scp      fmgb      1       3   critical      mzd      iqur

     expected  correct  undo  ...  generaliser2_term generaliser3  \
1226   ømenad        1     0  ...             ømenad          NaN
1227   uquçun        0     0  ...             ømenad          mbd
1228   ømenad        1     0  ...             ømenad          mbd
1229   uquçun        0     0  ...             ømenad          mbd
1230   ømenad        0     0  ...             ømenad          mbd
1231   uquçun        1     0  ...             ømenad          mbd
1232   ømenad        0     0  ...             ømenad          mbd

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1226               NaN          NaN               NaN        False
1227            adeçim          NaN               NaN          NaN
1228            adeçim          NaN               NaN          NaN
1229            adeçim          fzs            adeçim          NaN
1230            adeçim          fzs            adeçim          NaN
1231            adeçim          fzs            adeçim          NaN
1232            adeçim          fzs            adeçim          NaN

     button_number trial_index time_elapsed     rt
1226             1          26       199599   9939
1227             2          27       232900  33297
1228             1          28       244816  11913
1229             2          29       253482   8663
1230             0          30       263065   9581
1231             3          31       267499   4432
1232             0          32       270023   2521

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1250  3efko77scp      fmgb      4       4   critical      mbd    nyumuo
1251  3efko77scp      fmgb      4       4   critical      fzd    nyumuo
1252  3efko77scp      fmgb      4       4      catch      fbs       qăo
1253  3efko77scp      fmgb      4       4   critical      fbd    nyumuo
1254  3efko77scp      fmgb      4       4   critical      mbs       qăo
1255  3efko77scp      fmgb      4       4   critical      fzs       qăo
1256  3efko77scp      fmgb      4       4   critical      mzs       qăo

     expected  correct  undo  ...  generaliser2_term generaliser3  \
1250   nyumuo        1     0  ...             nyumuo          NaN
1251   nyumuo        1     0  ...             nyumuo          NaN
1252      qăo        1     0  ...             nyumuo          NaN
1253      qăo        0     0  ...             nyumuo          NaN
1254   nyumuo        0     0  ...             nyumuo          NaN
1255   nyumuo        0     0  ...             nyumuo          NaN
1256   nyumuo        0     0  ...             nyumuo          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1250               NaN          NaN               NaN          NaN
1251               NaN          NaN               NaN          NaN
1252               NaN          NaN               NaN        False
1253               NaN          NaN               NaN          NaN
1254               NaN          NaN               NaN          NaN
1255               NaN          NaN               NaN          NaN
1256               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed     rt
1250             3          83       429406  15009
1251             3          84       433126   3718
1252             0          85       436057   2928
1253             3          86       440580   4521
1254             0          87       444454   3872
1255             0          88       445906   1450
1256             0          89       446951   1042

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1284  3efko77scp      fmgb      8       5   critical      fzd    ryvïri
1285  3efko77scp      fmgb      8       5   critical      mbd  męwaqïfe
1286  3efko77scp      fmgb      8       5   critical      mzd  męwaqïfe
1287  3efko77scp      fmgb      8       5   critical      fbd    ryvïri
1288  3efko77scp      fmgb      8       5   critical      mzs  męwaqïfe
1289  3efko77scp      fmgb      8       5      catch      mbs  męwaqïfe
1290  3efko77scp      fmgb      8       5   critical      fbs    ryvïri

      expected  correct  undo  ...  generaliser2_term generaliser3  \
1284    ryvïri        1     0  ...           męwaqïfe          NaN
1285  męwaqïfe        1     0  ...           męwaqïfe          NaN
1286  męwaqïfe        1     0  ...           męwaqïfe          NaN
1287  męwaqïfe        0     0  ...           męwaqïfe          NaN
1288  męwaqïfe        1     0  ...           męwaqïfe          NaN
1289  męwaqïfe        1     0  ...           męwaqïfe          NaN
1290  męwaqïfe        0     0  ...           męwaqïfe          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1284               NaN          NaN               NaN          NaN
1285               NaN          NaN               NaN          NaN
1286               NaN          NaN               NaN          NaN
1287               NaN          NaN               NaN          NaN
1288               NaN          NaN               NaN          NaN
1289               NaN          NaN               NaN        False
1290               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed    rt
1284             2         159       647020  6050
1285             0         160       650435  3412
1286             0         161       652232  1795
1287             2         162       655152  2917
1288             0         163       657266  2112
1289             0         164       657369   101
1290             2         165       659980  2608

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1258  3efko77scp      fmgb      5       6   critical      fbd      svik
1259  3efko77scp      fmgb      5       6   critical      fbs  ktåvrhus
1260  3efko77scp      fmgb      5       6   critical      mzs   sfêvdok
1261  3efko77scp      fmgb      5       6   critical      mbd  rhymsvåd
1262  3efko77scp      fmgb      5       6      catch      mbs   sfêvdok
1263  3efko77scp      fmgb      5       6   critical      fzd      svik
1264  3efko77scp      fmgb      5       6   critical      mzd  rhymsvåd

      expected  correct  undo  ...  generaliser2_term generaliser3  \
1258  ktåvrhus        0     0  ...           ktåvrhus          fbd
1259  ktåvrhus        1     0  ...           ktåvrhus          fbd
1260  ktåvrhus        0     0  ...           ktåvrhus          fbd
1261   sfêvdok        0     0  ...           ktåvrhus          fbd
1262   sfêvdok        1     0  ...           ktåvrhus          fbd
1263  ktåvrhus        0     0  ...           ktåvrhus          fbd
1264  ktåvrhus        0     0  ...           ktåvrhus          fbd

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1258              svik          NaN               NaN          NaN
1259              svik          NaN               NaN          NaN
1260              svik          NaN               NaN          NaN
1261              svik          mbd          rhymsvåd          NaN
1262              svik          mbd          rhymsvåd        False
1263              svik          mbd          rhymsvåd          NaN
1264              svik          mbd          rhymsvåd          NaN

     button_number trial_index time_elapsed     rt
1258             2         102       491969  28693
1259             0         103       494390   2418
1260             3         104       499167   4775
1261             1         105       506494   7324
1262             3         106       509437   2941
1263             2         107       512075   2635
1264             1         108       514445   2367

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1234  3efko77scp      fmgb      2       7   critical      fzs      ilug
1235  3efko77scp      fmgb      2       7   critical      mzs      otev
1236  3efko77scp      fmgb      2       7   critical      mbs      ilug
1237  3efko77scp      fmgb      2       7   critical      mbd      ilug
1238  3efko77scp      fmgb      2       7   critical      fbd      otev
1239  3efko77scp      fmgb      2       7      catch      fzd      ilug
1240  3efko77scp      fmgb      2       7   critical      fbs      otev

     expected  correct  undo  ...  generaliser2_term generaliser3  \
1234     ilug        1     0  ...               ilug          NaN
1235     otev        1     0  ...               ilug          NaN
1236     ilug        1     0  ...               ilug          NaN
1237     ilug        1     0  ...               ilug          NaN
1238     ilug        0     0  ...               ilug          NaN
1239     ilug        1     0  ...               ilug          NaN
1240     ilug        0     0  ...               ilug          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1234               NaN          NaN               NaN          NaN
1235               NaN          NaN               NaN          NaN
1236               NaN          NaN               NaN          NaN
1237               NaN          NaN               NaN          NaN
1238               NaN          NaN               NaN          NaN
1239               NaN          NaN               NaN        False
1240               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed    rt
1234             1          45       312076  2663
1235             0          46       316472  4394
1236             1          47       319249  2775
1237             1          48       319950   698
1238             0          49       321925  1973
1239             1          50       328016  6089
1240             0          51       335395  7377

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1766  0q8bzdvgxy      mfgb      6       0   critical        z     möïtu
1767  0q8bzdvgxy      mfgb      6       0   critical      fbd     yaöpe
1768  0q8bzdvgxy      mfgb      6       0   critical      fzd     yaöpe
1769  0q8bzdvgxy      mfgb      6       0      catch      mzd     yaöpe
1770  0q8bzdvgxy      mfgb      6       0   critical      fzs  šaaqaude
1771  0q8bzdvgxy      mfgb      6       0   critical      mbd     yaöpe
1772  0q8bzdvgxy      mfgb      6       0   critical      mzs  šaaqaude
1773  0q8bzdvgxy      mfgb      6       0   critical      mbs  šaaqaude
1774  0q8bzdvgxy      mfgb      6       0   critical      fbs  šaaqaude

     expected  correct  undo  ...  generaliser2_term generaliser3  \
1766    möïtu        1     0  ...              möïtu          NaN
1767    yaöpe        1     0  ...              möïtu          NaN
1768    yaöpe        1     0  ...              möïtu          NaN
1769    yaöpe        1     0  ...              möïtu          NaN
1770    yaöpe        0     0  ...              möïtu          fzs
1771    yaöpe        1     0  ...              möïtu          fzs
1772    yaöpe        0     0  ...              möïtu          fzs
1773    yaöpe        0     0  ...              möïtu          fzs
1774    yaöpe        0     0  ...              möïtu          fzs

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1766               NaN          NaN               NaN          NaN
1767               NaN          NaN               NaN          NaN
1768               NaN          NaN               NaN          NaN
1769               NaN          NaN               NaN        False
1770          šaaqaude          NaN               NaN          NaN
1771          šaaqaude          NaN               NaN          NaN
1772          šaaqaude          NaN               NaN          NaN
1773          šaaqaude          NaN               NaN          NaN
1774          šaaqaude          NaN               NaN          NaN

     button_number trial_index time_elapsed     rt
1766             0         129       941844  19421
1767             2         130       948925   7079
1768             2         131       951081   2154
1769             2         132       952808   1725
1770             3         133       954209   1398
1771             2         134       955285   1074
1772             3         135       956332   1045
1773             3         136       957045    711
1774             3         137       957764    717

[9 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1776  0q8bzdvgxy      mfgb      7       1   critical      fbs     byure
1777  0q8bzdvgxy      mfgb      7       1   critical      fzd    cžunge
1778  0q8bzdvgxy      mfgb      7       1   critical      fbd    cžunge
1779  0q8bzdvgxy      mfgb      7       1   critical      mbs     vbāžo
1780  0q8bzdvgxy      mfgb      7       1      catch      mzs     vbāžo
1781  0q8bzdvgxy      mfgb      7       1   critical      mbd  rbāranžā
1782  0q8bzdvgxy      mfgb      7       1   critical      mzd  rbāranžā

     expected  correct  undo  ...  generaliser2_term generaliser3  \
1776    byure        1     0  ...              vbāžo          NaN
1777    byure        0     0  ...              vbāžo          fzd
1778    byure        0     0  ...              vbāžo          fzd
1779    vbāžo        1     0  ...              vbāžo          fzd
1780    vbāžo        1     0  ...              vbāžo          fzd
1781    vbāžo        0     0  ...              vbāžo          fzd
1782    vbāžo        0     0  ...              vbāžo          fzd

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1776               NaN          NaN               NaN          NaN
1777            cžunge          NaN               NaN          NaN
1778            cžunge          NaN               NaN          NaN
1779            cžunge          NaN               NaN          NaN
1780            cžunge          NaN               NaN        False
1781            cžunge          mbd          rbāranžā          NaN
1782            cžunge          mbd          rbāranžā          NaN

     button_number trial_index time_elapsed     rt
1776             2         150       983684  11449
1777             0         151       995497  11811
1778             0         152       997688   2189
1779             1         153      1000184   2494
1780             1         154      1003022   2837
1781             3         155      1010402   7378
1782             3         156      1010991    588

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1724  0q8bzdvgxy      mfgb      2       2   critical      mbs    baumiă
1725  0q8bzdvgxy      mfgb      2       2   critical      mbd    nyumuo
1726  0q8bzdvgxy      mfgb      2       2   critical      fzs    baumiă
1727  0q8bzdvgxy      mfgb      2       2      catch      fbd       gêă
1728  0q8bzdvgxy      mfgb      2       2   critical      mzs    baumiă
1729  0q8bzdvgxy      mfgb      2       2   critical      fzd       gêă
1731  0q8bzdvgxy      mfgb      2       2   critical      fzd       gêă
1733  0q8bzdvgxy      mfgb      2       2   critical      fzd    nyumuo
1734  0q8bzdvgxy      mfgb      2       2   critical      fbs    baumiă


       random_id condition  block  system trial_type selectee selection  \
1744  0q8bzdvgxy      mfgb      4       5      catch      mbd    etupol
1745  0q8bzdvgxy      mfgb      4       5   critical      mbs    ozatof
1747  0q8bzdvgxy      mfgb      4       5   critical      mbs    awupav
1749  0q8bzdvgxy      mfgb      4       5   critical      mbs    ozatof
1751  0q8bzdvgxy      mfgb      4       5   critical      mbs    awupav
1752  0q8bzdvgxy      mfgb      4       5   critical      fbs    awupav
1753  0q8bzdvgxy      mfgb      4       5   critical      mzd    etupol
1754  0q8bzdvgxy      mfgb      4       5   critical      fbd    etupol
1755  0q8bzdvgxy      mfgb      4       5   critical      fzd  egezalat
1756  0q8bzdvgxy      mfgb      4       5   critical      mzs    awupav

     expected  correct  undo  ...  generaliser2_term generaliser3  \
1744   etupol        1     0  ...             etupol          NaN
1745   etupol        0     0  ...             etupol          NaN
1747   etupol        0     0  ...             etupol          mbs
1749   etupol        0     0  ...             etupol          mbs
1751   etupol        0     0  ...             etupol          mbs
1752   etupol        0     0  ...             etupol          mbs
1753   etupol        1     0  ...             etupol          mbs
1754   etupol        1     0  ...             etupol          mbs
1755   ozatof        0     0  ...             etupol          mbs
1756   etupol        0     0  ...             etupol          mbs

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1744               NaN          NaN               NaN        False
1745               NaN          NaN               NaN          NaN
1747            awupav          NaN               NaN          NaN
1749            awupav          NaN               NaN          NaN
1751            awupav          mbs            awupav          NaN
1752            awupav          mbs            awupav          NaN
1753            awupav          mbs            awupav          NaN
1754            awupav          mbs            awupav          NaN
1755            awupav          mbs            awupav          NaN
1756            awupav          mbs            awupav          NaN

     button_number trial_index time_elapsed     rt
1744             3          87       757338   5805
1745             1          88       766140   8799
1747             2          90       787054  11374
1749             1          92       811906  18573
1751             2          94       825615   6028
1752             2          95       828172   2555
1753             3          96       831239   3064
1754             3          97       834029   2789
1755             0          98       839884   5852
1756             2          99       847690   7804

[10 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1784  0q8bzdvgxy      mfgb      8       6   critical      fbs  kvurddåh
1785  0q8bzdvgxy      mfgb      8       6      catch      fzd  ktåvrhus
1786  0q8bzdvgxy      mfgb      8       6   critical      mzs  kvurddåh
1787  0q8bzdvgxy      mfgb      8       6   critical      fbd  ktåvrhus
1788  0q8bzdvgxy      mfgb      8       6   critical      fzs  kvurddåh
1789  0q8bzdvgxy      mfgb      8       6   critical      mbd  ktåvrhus
1790  0q8bzdvgxy      mfgb      8       6   critical      mzd  ktåvrhus

      expected  correct  undo  ...  generaliser2_term generaliser3  \
1784  ktåvrhus        0     0  ...           ktåvrhus          NaN
1785  ktåvrhus        1     0  ...           ktåvrhus          NaN
1786  ktåvrhus        0     0  ...           ktåvrhus          NaN
1787  ktåvrhus        1     0  ...           ktåvrhus          NaN
1788  ktåvrhus        0     0  ...           ktåvrhus          NaN
1789  kvurddåh        0     0  ...           ktåvrhus          NaN
1790  ktåvrhus        1     0  ...           ktåvrhus          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1784               NaN          NaN               NaN          NaN
1785               NaN          NaN               NaN        False
1786               NaN          NaN               NaN          NaN
1787               NaN          NaN               NaN          NaN
1788               NaN          NaN               NaN          NaN
1789               NaN          NaN               NaN          NaN
1790               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed     rt
1784             0         169      1069044  31235
1785             2         170      1071086   2039
1786             0         171      1074514   3426
1787             2         172      1076894   2377
1788             0         173      1078356   1461
1789             2         174      1086739   8381
1790             2         175      1087674    932

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1716  0q8bzdvgxy      mfgb      1       7      catch      mzs   ngapapu
1717  0q8bzdvgxy      mfgb      1       7   critical      mbs   ngapapu
1718  0q8bzdvgxy      mfgb      1       7   critical      mbd      wupu
1719  0q8bzdvgxy      mfgb      1       7   critical      mzd      wupu
1720  0q8bzdvgxy      mfgb      1       7   critical      fzd   ngapapu
1721  0q8bzdvgxy      mfgb      1       7   critical      fbd   ngapapu
1722  0q8bzdvgxy      mfgb      1       7   critical      fbs   ngapapu

     expected  correct  undo  ...  generaliser2_term generaliser3  \
1716  ngapapu        1     0  ...               wupu          NaN
1717     wupu        0     0  ...               wupu          NaN
1718     wupu        1     0  ...               wupu          NaN
1719  ngapapu        0     0  ...               wupu          NaN
1720     wupu        0     0  ...               wupu          NaN
1721     wupu        0     0  ...               wupu          NaN
1722     wupu        0     0  ...               wupu          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1716               NaN          NaN               NaN        False
1717               NaN          NaN               NaN          NaN
1718               NaN          NaN               NaN          NaN
1719               NaN          NaN               NaN          NaN
1720               NaN          NaN               NaN          NaN
1721               NaN          NaN               NaN          NaN
1722               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed     rt
1716             0          26       440604   8433
1717             0          27       465189  24582
1718             2          28       477939  12749
1719             2          29       483229   5289
1720             0          30       490314   7084
1721             0          31       491664   1348
1722             0          32       493077   1412

[7 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
374  so2ywkynjc      fmgb      3       0   critical      fzd     vbāžo
375  so2ywkynjc      fmgb      3       0   critical        b    cžunge
376  so2ywkynjc      fmgb      3       0   critical      mbd     vbāžo
377  so2ywkynjc      fmgb      3       0   critical      fbd     vbāžo
378  so2ywkynjc      fmgb      3       0      catch        z     vbāžo
379  so2ywkynjc      fmgb      3       0   critical      mzd     vbāžo
380  so2ywkynjc      fmgb      3       0   critical      mbs     vbāžo
381  so2ywkynjc      fmgb      3       0   critical      mzs     vbāžo
382  so2ywkynjc      fmgb      3       0   critical      fzs     vbāžo

    expected  correct  undo  ...  generaliser2_term generaliser3  \
374    vbāžo        1     0  ...             cžunge          NaN
375   cžunge        1     0  ...             cžunge          NaN
376    vbāžo        1     0  ...             cžunge          NaN
377    vbāžo        1     0  ...             cžunge          NaN
378   cžunge        0     0  ...             cžunge          NaN
379    vbāžo        1     0  ...             cžunge          NaN
380    vbāžo        1     0  ...             cžunge          NaN
381    vbāžo        1     0  ...             cžunge          NaN
382    vbāžo        1     0  ...             cžunge          NaN

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
374               NaN          NaN               NaN          NaN
375               NaN          NaN               NaN          NaN
376               NaN          NaN               NaN          NaN
377               NaN          NaN               NaN          NaN
378               NaN          NaN               NaN         True
379               NaN          NaN               NaN          NaN
380               NaN          NaN               NaN          NaN
381               NaN          NaN               NaN          NaN
382               NaN          NaN               NaN          NaN

    button_number trial_index time_elapsed     rt
374             2          62       325127  10327
375             1          63       330130   5001
376             2          64       333750   3616
377             2          65       334183    430
378             2          66       334482    297
379             2          67       334932    448
380             2          68       335716    782
381             2          69       336463    746
382             2          70       337784   1320

[9 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
384  so2ywkynjc      fmgb      4       1   critical      fbs   tuumïhu
385  so2ywkynjc      fmgb      4       1   critical      mzs     töeqo
386  so2ywkynjc      fmgb      4       1   critical      mbd     töeqo
387  so2ywkynjc      fmgb      4       1   critical      fzd   tuumïhu
388  so2ywkynjc      fmgb      4       1   critical      fzs   tuumïhu
389  so2ywkynjc      fmgb      4       1      catch      fbd   tuumïhu
390  so2ywkynjc      fmgb      4       1   critical      mbs     töeqo

    expected  correct  undo  ...  generaliser2_term generaliser3  \
384  tuumïhu        1     0  ...              töeqo          NaN
385    töeqo        1     0  ...              töeqo          NaN
386    töeqo        1     0  ...              töeqo          NaN
387  tuumïhu        1     0  ...              töeqo          NaN
388  tuumïhu        1     0  ...              töeqo          NaN
389  tuumïhu        1     0  ...              töeqo          NaN
390    töeqo        1     0  ...              töeqo          NaN

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
384               NaN          NaN               NaN          NaN
385               NaN          NaN               NaN          NaN
386               NaN          NaN               NaN          NaN
387               NaN          NaN               NaN          NaN
388               NaN          NaN               NaN          NaN
389               NaN          NaN               NaN        False
390               NaN          NaN               NaN          NaN

    button_number trial_index time_elapsed     rt
384             1          83       358587  10307
385             2          84       363589   5002
386             2          85       365490   1899
387             1          86       367940   2449
388             1          87       368542    599
389             1          88       373813   5269
390             2          89       375748   1935

[7 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
416  so2ywkynjc      fmgb      8       2   critical      fzd    agivud
417  so2ywkynjc      fmgb      8       2   critical      fbs      azuf
418  so2ywkynjc      fmgb      8       2   critical      mzs    agivud
419  so2ywkynjc      fmgb      8       2      catch      fzs    agivud
420  so2ywkynjc      fmgb      8       2   critical      fbd      azuf
421  so2ywkynjc      fmgb      8       2   critical      mbd      azuf
422  so2ywkynjc      fmgb      8       2   critical      mzd    agivud

    expected  correct  undo  ...  generaliser2_term generaliser3  \
416   agivud        1     0  ...             agivud          NaN
417     azuf        1     0  ...             agivud          NaN
418   agivud        1     0  ...             agivud          NaN
419   agivud        1     0  ...             agivud          NaN
420     azuf        1     0  ...             agivud          NaN
421     azuf        1     0  ...             agivud          NaN
422   agivud        1     0  ...             agivud          NaN

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
416               NaN          NaN               NaN          NaN
417               NaN          NaN               NaN          NaN
418               NaN          NaN               NaN          NaN
419               NaN          NaN               NaN        False
420               NaN          NaN               NaN          NaN
421               NaN          NaN               NaN          NaN
422               NaN          NaN               NaN          NaN

    button_number trial_index time_elapsed     rt
416             1         159       528353  22967
417             2         160       533941   5584
418             1         161       537810   3867
419             1         162       539894   2082
420             2         163       541280   1385
421             2         164       542329   1047
422             1         165       543281    950

[7 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
400  so2ywkynjc      fmgb      6       3   critical      fbs    nyumuo
401  so2ywkynjc      fmgb      6       3      catch      fbd    nyumuo
402  so2ywkynjc      fmgb      6       3   critical      fzd    nyumuo
403  so2ywkynjc      fmgb      6       3   critical      mzs    nyumuo
404  so2ywkynjc      fmgb      6       3   critical      mzd    nyumuo
405  so2ywkynjc      fmgb      6       3   critical      mbs    nyumuo
406  so2ywkynjc      fmgb      6       3   critical      fzs    nyumuo

    expected  correct  undo  ...  generaliser2_term generaliser3  \
400   nyumuo        1     0  ...             nyumuo          NaN
401   nyumuo        1     0  ...             nyumuo          NaN
402   nyumuo        1     0  ...             nyumuo          NaN
403   nyumuo        1     0  ...             nyumuo          NaN
404   nyumuo        1     0  ...             nyumuo          NaN
405   nyumuo        1     0  ...             nyumuo          NaN
406   nyumuo        1     0  ...             nyumuo          NaN

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
400               NaN          NaN               NaN          NaN
401               NaN          NaN               NaN        False
402               NaN          NaN               NaN          NaN
403               NaN          NaN               NaN          NaN
404               NaN          NaN               NaN          NaN
405               NaN          NaN               NaN          NaN
406               NaN          NaN               NaN          NaN

    button_number trial_index time_elapsed     rt
400             1         121       448487  27887
401             1         122       450488   1999
402             1         123       451522   1032
403             1         124       452222    697
404             1         125       452656    431
405             1         126       453157    499
406             1         127       453707    548

[7 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
408  so2ywkynjc      fmgb      7       4   critical      mzs    morïky
409  so2ywkynjc      fmgb      7       4   critical      mzd  bokokohï
410  so2ywkynjc      fmgb      7       4   critical      fzs    morïky
411  so2ywkynjc      fmgb      7       4   critical      fbs    morïky
412  so2ywkynjc      fmgb      7       4   critical      mbd  bokokohï
413  so2ywkynjc      fmgb      7       4   critical      fzd  bokokohï
414  so2ywkynjc      fmgb      7       4      catch      mbs    morïky

     expected  correct  undo  ...  generaliser2_term generaliser3  \
408    morïky        1     0  ...             morïky          NaN
409    morïky        0     0  ...             morïky          NaN
410    morïky        1     0  ...             morïky          NaN
411  bokokohï        0     0  ...             morïky          NaN
412    morïky        0     0  ...             morïky          NaN
413    morïky        0     0  ...             morïky          NaN
414    morïky        1     0  ...             morïky          NaN

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
408               NaN          NaN               NaN          NaN
409               NaN          NaN               NaN          NaN
410               NaN          NaN               NaN          NaN
411               NaN          NaN               NaN          NaN
412               NaN          NaN               NaN          NaN
413               NaN          NaN               NaN          NaN
414               NaN          NaN               NaN        False

    button_number trial_index time_elapsed     rt
408             2         140       475475  12308
409             0         141       484441   8963
410             2         142       486317   1875
411             2         143       491406   5086
412             0         144       493390   1981
413             0         145       493891    498
414             2         146       496410   2516

[7 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
392  so2ywkynjc      fmgb      5       5   critical      fzs  ktåvrhus
393  so2ywkynjc      fmgb      5       5   critical      fbd      ktot
394  so2ywkynjc      fmgb      5       5      catch      fzd  ktåvrhus
395  so2ywkynjc      fmgb      5       5   critical      mbs      ktot
396  so2ywkynjc      fmgb      5       5   critical      mzd      ktot
397  so2ywkynjc      fmgb      5       5   critical      mzs      ktot
398  so2ywkynjc      fmgb      5       5   critical      mbd      ktot

     expected  correct  undo  ...  generaliser2_term generaliser3  \
392  ktåvrhus        1     0  ...               ktot          NaN
393      ktot        1     0  ...               ktot          NaN
394  ktåvrhus        1     0  ...               ktot          NaN
395      ktot        1     0  ...               ktot          NaN
396      ktot        1     0  ...               ktot          NaN
397      ktot        1     0  ...               ktot          NaN
398      ktot        1     0  ...               ktot          NaN

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
392               NaN          NaN               NaN          NaN
393               NaN          NaN               NaN          NaN
394               NaN          NaN               NaN        False
395               NaN          NaN               NaN          NaN
396               NaN          NaN               NaN          NaN
397               NaN          NaN               NaN          NaN
398               NaN          NaN               NaN          NaN

    button_number trial_index time_elapsed     rt
392             0         102       401399  14556
393             3         103       403683   2281
394             0         104       406802   3118
395             3         105       409105   2301
396             3         106       409471    364
397             3         107       409921    447
398             3         108       410123    200

[7 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
358  so2ywkynjc      fmgb      1       6   critical      fbd      aweh

       random_id condition  block  system trial_type selectee selection  \
2128  fmxtqnjbuc      mfgb      6       5   critical      mzd   cöahido
2129  fmxtqnjbuc      mfgb      6       5   critical      fzs  beiguumu
2130  fmxtqnjbuc      mfgb      6       5   critical      mbd   cöahido
2131  fmxtqnjbuc      mfgb      6       5      catch      fzd   cöahido
2132  fmxtqnjbuc      mfgb      6       5   critical      mbs  beiguumu
2133  fmxtqnjbuc      mfgb      6       5   critical      mzs  beiguumu
2134  fmxtqnjbuc      mfgb      6       5   critical      fbd   cöahido

      expected  correct  undo  ...  generaliser2_term generaliser3  \
2128  beiguumu        0     0  ...           beiguumu          NaN
2129   cöahido        0     0  ...           beiguumu          NaN
2130  beiguumu        0     0  ...           beiguumu          NaN
2131   cöahido        1     0  ...           beiguumu          NaN
2132  beiguumu        1     0  ...           beiguumu          NaN
2133  beiguumu        1     0  ...           beiguumu          NaN
2134  beiguumu        0     0  ...           beiguumu          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2128               NaN          NaN               NaN          NaN
2129               NaN          NaN               NaN          NaN
2130               NaN          NaN               NaN          NaN
2131               NaN          NaN               NaN        False
2132               NaN          NaN               NaN          NaN
2133               NaN          NaN               NaN          NaN
2134               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed    rt
2128             1         121       981104  4816
2129             3         122       986248  5138
2130             1         123       989088  2833
2131             1         124       995151  6058
2132             3         125      1000020  4862
2133             3         126      1002804  2777
2134             1         127      1005744  2933

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee  selection  \
2088  fmxtqnjbuc      mfgb      1       6   critical      fbd     lepego
2089  fmxtqnjbuc      mfgb      1       6   critical      mzs  powisunge
2090  fmxtqnjbuc      mfgb      1       6   critical      mbs  powisunge
2091  fmxtqnjbuc      mfgb      1       6      catch      fzd     lepego
2092  fmxtqnjbuc      mfgb      1       6   critical      mzd  powisunge
2093  fmxtqnjbuc      mfgb      1       6   critical      fbs     lepego
2094  fmxtqnjbuc      mfgb      1       6   critical      fzs     lepego

       expected  correct  undo  ...  generaliser2_term generaliser3  \
2088     lepego        1     0  ...             lepego          NaN
2089     lepego        0     0  ...             lepego          NaN
2090  powisunge        1     0  ...             lepego          NaN
2091     lepego        1     0  ...             lepego          NaN
2092     lepego        0     0  ...             lepego          NaN
2093     lepego        1     0  ...             lepego          NaN
2094     lepego        1     0  ...             lepego          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2088               NaN          NaN               NaN          NaN
2089               NaN          NaN               NaN          NaN
2090               NaN          NaN               NaN          NaN
2091               NaN          NaN               NaN        False
2092               NaN          NaN               NaN          NaN
2093               NaN          NaN               NaN          NaN
2094               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed     rt
2088             1          26       455755  41327
2089             2          27       477802  22037
2090             2          28       497918  20109
2091             1          29       513445  15521
2092             2          30       531842  18389
2093             1          31       542462  10614
2094             1          32       551054   8584

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2096  fmxtqnjbuc      mfgb      2       7   critical      mzd       gêă
2097  fmxtqnjbuc      mfgb      2       7      catch      mbs    huanăa
2098  fmxtqnjbuc      mfgb      2       7   critical      fzd    huanăa
2099  fmxtqnjbuc      mfgb      2       7   critical      mbd    huanăa
2100  fmxtqnjbuc      mfgb      2       7   critical      fbs    huanăa
2101  fmxtqnjbuc      mfgb      2       7   critical      fbd    huanăa
2102  fmxtqnjbuc      mfgb      2       7   critical      fzs    huanăa

     expected  correct  undo  ...  generaliser2_term generaliser3  \
2096      gêă        1     0  ...             huanăa          NaN
2097   huanăa        1     0  ...             huanăa          NaN
2098   huanăa        1     0  ...             huanăa          NaN
2099   huanăa        1     0  ...             huanăa          NaN
2100   huanăa        1     0  ...             huanăa          NaN
2101   huanăa        1     0  ...             huanăa          NaN
2102   huanăa        1     0  ...             huanăa          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2096               NaN          NaN               NaN          NaN
2097               NaN          NaN               NaN        False
2098               NaN          NaN               NaN          NaN
2099               NaN          NaN               NaN          NaN
2100               NaN          NaN               NaN          NaN
2101               NaN          NaN               NaN          NaN
2102               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed     rt
2096             1          45       636573  24211
2097             2          46       644570   7989
2098             2          47       680301  35725
2099             2          48       684017   3709
2100             2          49       690561   6537
2101             2          50       692921   2353
2102             2          51       696081   3153

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2154  0j6k161n6d      fmgb      1       2   critical      mzd  egezalat
2155  0j6k161n6d      fmgb      1       2      catch      mbs      otev
2156  0j6k161n6d      fmgb      1       2   critical      fzs      ilug
2157  0j6k161n6d      fmgb      1       2   critical      mbd      otev
2158  0j6k161n6d      fmgb      1       2   critical      fbs  egezalat
2159  0j6k161n6d      fmgb      1       2   critical      fbd  idanuluf
2160  0j6k161n6d      fmgb      1       2   critical      fzd  egezalat

      expected  correct  undo  ...  generaliser2_term generaliser3  \
2154      otev        0     0  ...               otev          NaN
2155  egezalat        0     0  ...               otev          NaN
2156      otev        0     0  ...               otev          fzs
2157  egezalat        0     0  ...               otev          fzs
2158  egezalat        1     0  ...               otev          fzs
2159  egezalat        0     0  ...               otev          fzs
2160      otev        0     0  ...               otev          fzs

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2154               NaN          NaN               NaN          NaN
2155               NaN          NaN               NaN         True
2156              ilug          NaN               NaN          NaN
2157              ilug          NaN               NaN          NaN
2158              ilug          NaN               NaN          NaN
2159              ilug          fbd          idanuluf          NaN
2160              ilug          fbd          idanuluf          NaN

     button_number trial_index time_elapsed    rt
2154             2          26        15728   885
2155             1          27        16169   435
2156             0          28        16636   461
2157             1          29        17085   444
2158             2          30        17705   616
2159             3          31        18311   600
2160             2          32        19322  1006

[7 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
842  m9q6e0oj7a      fmbg      5       0   critical      mzd     vruži
843  m9q6e0oj7a      fmbg      5       0   critical      fbs    ngcāžo
844  m9q6e0oj7a      fmbg      5       0   critical      mbs    ngcāžo
845  m9q6e0oj7a      fmbg      5       0   critical        b    ngcāžo
846  m9q6e0oj7a      fmbg      5       0   critical      fzd     vruži
847  m9q6e0oj7a      fmbg      5       0      catch      fzs    ngcāžo
848  m9q6e0oj7a      fmbg      5       0   critical      fbd     vruži
849  m9q6e0oj7a      fmbg      5       0   critical      mbd     vruži
850  m9q6e0oj7a      fmbg      5       0   critical      mzs    ngcāžo

    expected  correct  undo  ...  generaliser2_term generaliser3  \
842   ngcāžo        0     0  ...              vruži          NaN
843   ngcāžo        1     0  ...              vruži          NaN
844   ngcāžo        1     0  ...              vruži          NaN
845    vruži        0     0  ...              vruži          NaN
846   ngcāžo        0     0  ...              vruži          NaN
847   ngcāžo        1     0  ...              vruži          NaN
848   ngcāžo        0     0  ...              vruži          NaN
849   ngcāžo        0     0  ...              vruži          NaN
850   ngcāžo        1     0  ...              vruži          NaN

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
842               NaN          NaN               NaN          NaN
843               NaN          NaN               NaN          NaN
844               NaN          NaN               NaN          NaN
845               NaN          NaN               NaN          NaN
846               NaN          NaN               NaN          NaN
847               NaN          NaN               NaN        False
848               NaN          NaN               NaN          NaN
849               NaN          NaN               NaN          NaN
850               NaN          NaN               NaN          NaN

    button_number trial_index time_elapsed     rt
842             1         106      1044613   6829
843             3         107      1076169  31552
844             3         108      1078713   2539
845             3         109      1084216   5499
846             1         110      1101301  17083
847             3         111      1103401   2097
848             1         112      1106828   3424
849             1         113      1109611   2782
850             3         114      1119265   9651

[9 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
804  m9q6e0oj7a      fmbg      1       1   critical      mbs  šaaqaude
805  m9q6e0oj7a      fmbg      1       1   critical      fzd     yaöpe
806  m9q6e0oj7a      fmbg      1       1      catch      fbs  šaaqaude
807  m9q6e0oj7a      fmbg      1       1   critical      fzs  šaaqaude
808  m9q6e0oj7a      fmbg      1       1   critical      mzs  šaaqaude
809  m9q6e0oj7a      fmbg      1       1   critical      mbd     yaöpe
810  m9q6e0oj7a      fmbg      1       1   critical      fbd     yaöpe

     expected  correct  undo  ...  generaliser2_term generaliser3  \
804     yaöpe        0     0  ...              yaöpe          NaN
805  šaaqaude        0     0  ...              yaöpe          NaN
806  šaaqaude        1     0  ...              yaöpe          NaN
807  šaaqaude        1     0  ...              yaöpe          NaN
808     yaöpe        0     0  ...              yaöpe          NaN
809     yaöpe        1     0  ...              yaöpe          NaN
810  šaaqaude        0     0  ...              yaöpe          NaN

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
804               NaN          NaN               NaN          NaN
805               NaN          NaN               NaN          NaN
806               NaN          NaN               NaN        False
807               NaN          NaN               NaN          NaN
808               NaN          NaN               NaN          NaN
809               NaN          NaN               NaN          NaN
810               NaN          NaN               NaN          NaN

    button_number trial_index time_elapsed     rt
804             1          26       721402  45418
805             3          27       724456   3052
806             1          28       739554  15096
807             1          29       764632  25076
808             1          30       768451   3817
809             3          31       770852   2400
810             3          32       771842    989

[7 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
870  m9q6e0oj7a      fmbg      8       2   critical      mbd       gêă
871  m9q6e0oj7a      fmbg      8       2   critical      fbs    niuhiê
872  m9q6e0oj7a      fmbg      8       2   critical      fbd       qăo
873  m9q6e0oj7a      fmbg      8       2      catch      mbs    nyumuo
874  m9q6e0oj7a      fmbg      8       2   critical      fzd       qăo
875  m9q6e0oj7a      fmbg      8       2   critical      fzs    niuhiê
876  m9q6e0oj7a      fmbg      8       2   critical      mzs    nyumuo

    expected  correct  undo  ...  generaliser2_term generaliser3  \
870   nyumuo        0     0  ...                gêă          NaN
871   nyumuo        0     0  ...                gêă          fbs
872   nyumuo        0     0  ...                gêă          fbs
873   nyumuo        1     0  ...                gêă          fbs
874      gêă        0     0  ...                gêă          fbs
875      gêă        0     0  ...                gêă          fbs
876      gêă        0     0  ...                gêă          fbs

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
870               NaN          NaN               NaN          NaN
871            niuhiê          NaN               NaN          NaN
872            niuhiê          NaN               NaN          NaN
873            niuhiê          NaN               NaN        False
874            niuhiê          NaN               NaN          NaN
875            niuhiê          fzs            niuhiê          NaN
876            niuhiê          fzs            niuhiê          NaN

    button_number trial_index time_elapsed     rt
870             3         167      1295588  20534
871             1         168      1306998  11406
872             0         169      1311333   4333
873             2         170      1313815   2481
874             0         171      1316830   3012
875             1         172      1319426   2594
876             2         173      1321578   2151

[7 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
830  m9q6e0oj7a      fmbg      4       3   critical      mbs    morïky
832  m9q6e0oj7a      fmbg      4       3   critical      mbs      kïmy
833  m9q6e0oj7a      fmbg      4       3   critical      fzd    morïky
834  m9q6e0oj7a      fmbg      4       3   critical      fbd      qïru
835  m9q6e0oj7a      fmbg      4       3   critical      mzd    morïky
836  m9q6e0oj7a      fmbg      4       3   critical      mbd      qïru
837  m9q6e0oj7a      fmbg      4       3      catch      fzs  męwaqïfe
839  m9q6e0oj7a      fmbg      4       3   critical      mbd      qïru
840  m9q6e0oj7a      fmbg      4       3   critical      mzs  męwaqïfe

     expected  correct  undo  ...  generaliser2_term generaliser3  \
830  męwaqïfe        0     0  ...               kïmy          mbs
832  męwaqïfe        0     0  ...               kïmy          mbs
833  męwaqïfe        0     0  ...               kïmy          mbs
834      kïmy        0     0  ...               kïmy          mbs
835      kïmy        0     0  ...               kïmy          mbs
836  męwaqïfe        0     0  ...               kïmy          mbs
837  męwaqïfe        1     0  ...               kïmy          mbs
839  męwaqïfe        0     0  ...               kïmy          mbs
840      kïmy        0     0  ...               kïmy          mbs

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
830            morïky          NaN               NaN          NaN
832            morïky          NaN               NaN          NaN
833            morïky          fzd            morïky          NaN
834            morïky          fzd            morïky          NaN
835            morïky          fzd            morïky          NaN
836            morïky          fzd            morïky          NaN
837            morïky          fzd            morïky        False
839            morïky          fzd            morïky          NaN
840            morïky          fzd            morïky          NaN

    button_number trial_index time_elapsed    rt
830             2          85       987321   651
832             0          87       997320  8490
833             2          88      1004047  6725
834             1          89      1009845  5796
835             2          90      1014375  4527
836             1          91      1018089  3710
837             3          92      1020134  2040
839             1          94      1028505  6855
840             3          95      1032705  4199

[9 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
812  m9q6e0oj7a      fmbg      2       4   critical      fzs    uquçun
813  m9q6e0oj7a      fmbg      2       4   critical      fbs      øqoç
814  m9q6e0oj7a      fmbg      2       4   critical      mzs    uquçun
815  m9q6e0oj7a      fmbg      2       4   critical      mzd  içiqusem
816  m9q6e0oj7a      fmbg      2       4   critical      mbd    emøyeç
817  m9q6e0oj7a      fmbg      2       4   critical      mbs      øqoç
818  m9q6e0oj7a      fmbg      2       4      catch      fbd    emøyeç

     expected  correct  undo  ...  generaliser2_term generaliser3  \
812  içiqusem        0     0  ...           içiqusem          fzs
813    emøyeç        0     0  ...           içiqusem          fzs
814  içiqusem        0     0  ...           içiqusem          fzs
815  içiqusem        1     0  ...           içiqusem          fzs
816  içiqusem        0     0  ...           içiqusem          fzs
817  içiqusem        0     0  ...           içiqusem          fzs
818    emøyeç        1     0  ...           içiqusem          fzs

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
812            uquçun          NaN               NaN          NaN
813            uquçun          NaN               NaN          NaN
814            uquçun          mzs            uquçun          NaN
815            uquçun          mzs            uquçun          NaN
816            uquçun          mzs            uquçun          NaN
817            uquçun          mzs            uquçun          NaN
818            uquçun          mzs            uquçun        False

    button_number trial_index time_elapsed     rt
812             3          45       835131  43521
813             0          46       836441   1308
814             3          47       844758   8314
815             1          48       846903   2143
816             2          49       852183   5279
817             0          50       855312   3125
818             2          51       863464   8151

[7 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
820  m9q6e0oj7a      fmbg      3       5   critical      mzs    agivud
821  m9q6e0oj7a      fmbg      3       5   critical      mbd    ozatof
822  m9q6e0oj7a      fmbg      3       5      catch      fzd      otev
823  m9q6e0oj7a      fmbg      3       5   critical      fbd    ozatof

       random_id condition  block  system trial_type selectee selection  \
1792  yfc8915946      mfgb      1       0   critical      mbs    hïlaki
1793  yfc8915946      mfgb      1       0   critical      mzs      qïru
1794  yfc8915946      mfgb      1       0   critical      mbd  bokokohï
1795  yfc8915946      mfgb      1       0   critical        b  męwaqïfe
1796  yfc8915946      mfgb      1       0      catch      fzs  męwaqïfe
1797  yfc8915946      mfgb      1       0   critical      fbd  bokokohï
1798  yfc8915946      mfgb      1       0   critical      fzd    hïlaki
1799  yfc8915946      mfgb      1       0   critical      mzd    hïlaki
1800  yfc8915946      mfgb      1       0   critical      fbs    hïlaki

      expected  correct  undo  ...  generaliser2_term generaliser3  \
1792  męwaqïfe        0     0  ...           bokokohï          mbs
1793  męwaqïfe        0     0  ...           bokokohï          mbs
1794  męwaqïfe        0     0  ...           bokokohï          mbs
1795  bokokohï        0     0  ...           bokokohï          mbs
1796  męwaqïfe        1     0  ...           bokokohï          mbs
1797  męwaqïfe        0     0  ...           bokokohï          mbs
1798  męwaqïfe        0     0  ...           bokokohï          mbs
1799  męwaqïfe        0     0  ...           bokokohï          mbs
1800  męwaqïfe        0     0  ...           bokokohï          mbs

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1792            hïlaki          NaN               NaN          NaN
1793            hïlaki          NaN               NaN          NaN
1794            hïlaki          NaN               NaN          NaN
1795            hïlaki          NaN               NaN          NaN
1796            hïlaki          NaN               NaN        False
1797            hïlaki          NaN               NaN          NaN
1798            hïlaki          fzd            hïlaki          NaN
1799            hïlaki          fzd            hïlaki          NaN
1800            hïlaki          fzd            hïlaki          NaN

     button_number trial_index time_elapsed    rt
1792             0          24       147158  6647
1793             1          25       150421  3261
1794             2          26       152717  2295
1795             3          27       153797  1079
1796             3          28       162821  9022
1797             2          29       167317  4494
1798             0          30       170453  3134
1799             0          31       177757  7302
1800             0          32       182893  5134

[9 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1850  yfc8915946      mfgb      8       1      catch      fzs     žbodu
1851  yfc8915946      mfgb      8       1   critical      mbs     vbāžo
1852  yfc8915946      mfgb      8       1   critical      mzs     žbodu
1853  yfc8915946      mfgb      8       1   critical      fzd     vruži
1854  yfc8915946      mfgb      8       1   critical      mzd    ngcāžo
1855  yfc8915946      mfgb      8       1   critical      fbs     žbodu
1856  yfc8915946      mfgb      8       1   critical      fbd    ngcāžo

     expected  correct  undo  ...  generaliser2_term generaliser3  \
1850    žbodu        1     0  ...              vruži          NaN
1851    vruži        0     0  ...              vruži          mbs
1852    vruži        0     0  ...              vruži          mbs
1853    žbodu        0     0  ...              vruži          mbs
1854    vruži        0     0  ...              vruži          mbs
1855    žbodu        1     0  ...              vruži          mbs
1856    žbodu        0     0  ...              vruži          mbs

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1850               NaN          NaN               NaN        False
1851             vbāžo          NaN               NaN          NaN
1852             vbāžo          NaN               NaN          NaN
1853             vbāžo          NaN               NaN          NaN
1854             vbāžo          mzd            ngcāžo          NaN
1855             vbāžo          mzd            ngcāžo          NaN
1856             vbāžo          mzd            ngcāžo          NaN

     button_number trial_index time_elapsed    rt
1850             3         159       555108  4414
1851             0         160       560916  5806
1852             3         161       564284  3367
1853             2         162       567741  3455
1854             1         163       572436  4694
1855             3         164       579884  7446
1856             1         165       588868  8983

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1842  yfc8915946      mfgb      7       2   critical      mzs  tsåvvses
1843  yfc8915946      mfgb      7       2   critical      mzd  rhymsvåd
1844  yfc8915946      mfgb      7       2      catch      fzd  rhymsvåd
1845  yfc8915946      mfgb      7       2   critical      fbd  smêvskêv
1846  yfc8915946      mfgb      7       2   critical      fzs  tsåvvses
1847  yfc8915946      mfgb      7       2   critical      mbd  rhymsvåd
1848  yfc8915946      mfgb      7       2   critical      fbs   sfêvdok

      expected  correct  undo  ...  generaliser2_term generaliser3  \
1842  rhymsvåd        0     0  ...           rhymsvåd          mzs
1843  rhymsvåd        1     0  ...           rhymsvåd          mzs
1844  rhymsvåd        1     0  ...           rhymsvåd          mzs
1845   sfêvdok        0     0  ...           rhymsvåd          mzs
1846  rhymsvåd        0     0  ...           rhymsvåd          mzs
1847   sfêvdok        0     0  ...           rhymsvåd          mzs
1848   sfêvdok        1     0  ...           rhymsvåd          mzs

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1842          tsåvvses          NaN               NaN          NaN
1843          tsåvvses          NaN               NaN          NaN
1844          tsåvvses          NaN               NaN        False
1845          tsåvvses          fbd          smêvskêv          NaN
1846          tsåvvses          fbd          smêvskêv          NaN
1847          tsåvvses          fbd          smêvskêv          NaN
1848          tsåvvses          fbd          smêvskêv          NaN

     button_number trial_index time_elapsed     rt
1842             3         140       506157   8988
1843             1         141       509060   2902
1844             1         142       510588   1527
1845             0         143       521764  11175
1846             3         144       526580   4815
1847             1         145       538660  12078
1848             2         146       544516   5855

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1802  yfc8915946      mfgb      2       3   critical      fbd     nuubö
1803  yfc8915946      mfgb      2       3      catch      mzs     šïïnö
1804  yfc8915946      mfgb      2       3   critical      fzs     šïïnö
1805  yfc8915946      mfgb      2       3   critical      mbd   tuumïhu
1806  yfc8915946      mfgb      2       3   critical      mzd   tuumïhu
1807  yfc8915946      mfgb      2       3   critical      fbs     šïïnö
1808  yfc8915946      mfgb      2       3   critical      fzd   tuumïhu

     expected  correct  undo  ...  generaliser2_term generaliser3  \
1802    šïïnö        0     0  ...              šïïnö          fbd
1803    šïïnö        1     0  ...              šïïnö          fbd
1804  tuumïhu        0     0  ...              šïïnö          fbd
1805  tuumïhu        1     0  ...              šïïnö          fbd
1806    šïïnö        0     0  ...              šïïnö          fbd
1807    šïïnö        1     0  ...              šïïnö          fbd
1808  tuumïhu        1     0  ...              šïïnö          fbd

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1802             nuubö          NaN               NaN          NaN
1803             nuubö          NaN               NaN        False
1804             nuubö          NaN               NaN          NaN
1805             nuubö          NaN               NaN          NaN
1806             nuubö          NaN               NaN          NaN
1807             nuubö          NaN               NaN          NaN
1808             nuubö          NaN               NaN          NaN

     button_number trial_index time_elapsed     rt
1802             2          45       219701  12855
1803             3          46       223517   3814
1804             3          47       226669   3150
1805             0          48       229541   2870
1806             0          49       233221   3679
1807             3          50       238413   5190
1808             0          51       242813   4399

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1818  yfc8915946      mfgb      4       4   critical      fbd    awupav
1819  yfc8915946      mfgb      4       4   critical      fzd      otev
1820  yfc8915946      mfgb      4       4      catch      fbs    awupav
1821  yfc8915946      mfgb      4       4   critical      mbs    awupav
1822  yfc8915946      mfgb      4       4   critical      fzs    ozatof
1823  yfc8915946      mfgb      4       4   critical      mbd    agivud
1824  yfc8915946      mfgb      4       4   critical      mzs      otev

     expected  correct  undo  ...  generaliser2_term generaliser3  \
1818   awupav        1     0  ...             ozatof          NaN
1819   ozatof        0     0  ...             ozatof          fzd
1820   awupav        1     0  ...             ozatof          fzd
1821   ozatof        0     0  ...             ozatof          fzd
1822   ozatof        1     0  ...             ozatof          fzd
1823   ozatof        0     0  ...             ozatof          fzd
1824   ozatof        0     0  ...             ozatof          fzd

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1818               NaN          NaN               NaN          NaN
1819              otev          NaN               NaN          NaN
1820              otev          NaN               NaN        False
1821              otev          NaN               NaN          NaN
1822              otev          NaN               NaN          NaN
1823              otev          NaN               NaN          NaN
1824              otev          mzs              otev          NaN

     button_number trial_index time_elapsed     rt
1818             0          83       339085  11727
1819             2          84       344413   5327
1820             0          85       348573   4158
1821             0          86       361743  13182
1822             1          87       366479   4735
1823             3          88       370711   4231
1824             2          89       375119   4407

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1834  yfc8915946      mfgb      6       5   critical      fbs    hyonăo
1835  yfc8915946      mfgb      6       5   critical      fzs    huanăa
1836  yfc8915946      mfgb      6       5   critical      fbd       qăo
1837  yfc8915946      mfgb      6       5   critical      mbd    goozăi
1838  yfc8915946      mfgb      6       5   critical      mbs    hyonăo
1839  yfc8915946      mfgb      6       5   critical      mzs    hyonăo
1840  yfc8915946      mfgb      6       5      catch      mzd       qăo

     expected  correct  undo  ...  generaliser2_term generaliser3  \
1834      qăo        0     0  ...                qăo          fbs
1835   goozăi        0     0  ...                qăo          fbs
1836      qăo        1     0  ...                qăo          fbs
1837      qăo        0     0  ...                qăo          fbs
1838      qăo        0     0  ...                qăo          fbs
1839      qăo        0     0  ...                qăo          fbs
1840      qăo        1     0  ...                qăo          fbs

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1834            hyonăo          NaN               NaN          NaN
1835            hyonăo          NaN               NaN          NaN
1836            hyonăo          NaN               NaN          NaN
1837            hyonăo          NaN               NaN          NaN
1838            hyonăo          mbs            hyonăo          NaN
1839            hyonăo          mbs            hyonăo          NaN
1840            hyonăo          mbs            hyonăo        False

     button_number trial_index time_elapsed     rt
1834             1         121       454901  14495
1835             0         122       466045  11143
1836             3         123       474165   8118
1837             2         124       479684   5518
1838             1         125       484444   4758
1839             1         126       488693   4247
1840             3         127       491509   2814

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1826  yfc8915946      mfgb      5       6   critical      fzd    goviku
1827  yfc8915946      mfgb      5       6      catch      mbd    lepego
1828  yfc8915946      mfgb      5       6   critical      fzs    kawuka
1829  yfc8915946      mfgb      5       6   critical      fbs   popingi
1830  yfc8915946      mfgb      5       6   critical      mbs   popingi
1831  yfc8915946      mfgb      5       6   critical      fbd    goviku
1832  yfc8915946      mfgb      5       6   critical      mzs   popingi

     expected  correct  undo  ...  generaliser2_term generaliser3  \
1826   goviku        1     0  ...             goviku          NaN
1827   lepego        1     0  ...             goviku          NaN
1828   goviku        0     0  ...             goviku          fzs
1829   goviku        0     0  ...             goviku          fzs
1830   lepego        0     0  ...             goviku          fzs
1831   goviku        1     0  ...             goviku          fzs
1832   goviku        0     0  ...             goviku          fzs

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1826               NaN          NaN               NaN          NaN
1827               NaN          NaN               NaN        False
1828            kawuka          NaN               NaN          NaN
1829            kawuka          NaN               NaN          NaN
1830            kawuka          NaN               NaN          NaN
1831            kawuka          NaN               NaN          NaN
1832            kawuka          NaN               NaN          NaN

     button_number trial_index time_elapsed     rt
1826             1         102       396335  10439
1827             2         103       400951   4614
1828             3         104       407543   6591
1829             0         105       412934   5390
1830             0         106       419766   6831
1831             1         107       422549   2767
1832             0         108       424957   2407

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1810  yfc8915946      mfgb      3       7      catch      mzd  orinoçim
1811  yfc8915946      mfgb      3       7   critical      fbs  aqinudød
1812  yfc8915946      mfgb      3       7   critical      fbd  orinoçim
1813  yfc8915946      mfgb      3       7   critical      fzs  aqinudød
1814  yfc8915946      mfgb      3       7   critical      fzd  orinoçim
1815  yfc8915946      mfgb      3       7   critical      mbd  orinoçim
1816  yfc8915946      mfgb      3       7   critical      mzs  aqinudød

      expected  correct  undo  ...  generaliser2_term generaliser3  \
1810  orinoçim        1     0  ...           aqinudød          NaN
1811  aqinudød        1     0  ...           aqinudød          NaN
1812  aqinudød        0     0  ...           aqinudød          NaN
1813  aqinudød        1     0  ...           aqinudød          NaN
1814  aqinudød        0     0  ...           aqinudød          NaN
1815  aqinudød        0     0  ...           aqinudød          NaN
1816  orinoçim        0     0  ...           aqinudød          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1810               NaN          NaN               NaN        False
1811               NaN          NaN               NaN          NaN
1812               NaN          NaN               NaN          NaN
1813               NaN          NaN               NaN          NaN
1814               NaN          NaN               NaN          NaN
1815               NaN          NaN               NaN          NaN
1816               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed     rt
1810             3          64       283477  14023
1811             2          65       289085   5606
1812             3          66       294477   5391
1813             2          67       298365   3886
1814             3          68       300229   1863
1815             3          69       303597   3366
1816             2          70       306589   2990

[7 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
534  6xbr38yopd      fmgb      6       0   critical      mbd  smêvskêv
535  6xbr38yopd      fmgb      6       0   critical      mzs  smêvskêv
536  6xbr38yopd      fmgb      6       0   critical        z   sfêvdok
537  6xbr38yopd      fmgb      6       0      catch        b  rhymsvåd
538  6xbr38yopd      fmgb      6       0   critical      mzd  smêvskêv
539  6xbr38yopd      fmgb      6       0   critical      mbs  smêvskêv
540  6xbr38yopd      fmgb      6       0   critical      fbs  smêvskêv
541  6xbr38yopd      fmgb      6       0   critical      fbd  smêvskêv
542  6xbr38yopd      fmgb      6       0   critical      fzd  smêvskêv

     expected  correct  undo  ...  generaliser2_term generaliser3  \
534  smêvskêv        1     0  ...           rhymsvåd          NaN
535  smêvskêv        1     0  ...           rhymsvåd          NaN
536  rhymsvåd        0     0  ...           rhymsvåd            z
537  rhymsvåd        1     0  ...           rhymsvåd            z
538  smêvskêv        1     0  ...           rhymsvåd            z
539  smêvskêv        1     0  ...           rhymsvåd            z
540  smêvskêv        1     0  ...           rhymsvåd            z
541  smêvskêv        1     0  ...           rhymsvåd            z
542  smêvskêv        1     0  ...           rhymsvåd            z

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
534               NaN          NaN               NaN          NaN
535               NaN          NaN               NaN          NaN
536           sfêvdok          NaN               NaN          NaN
537           sfêvdok          NaN               NaN        False
538           sfêvdok          NaN               NaN          NaN
539           sfêvdok          NaN               NaN          NaN
540           sfêvdok          NaN               NaN          NaN
541           sfêvdok          NaN               NaN          NaN
542           sfêvdok          NaN               NaN          NaN

    button_number trial_index time_elapsed     rt
534             2         119       520779    185
535             2         120       529418   8637
536             1         121       544253  14832
537             0         122       546261   2006
538             2         123       547898   1635
539             2         124       548472    572
540             2         125       549308    835
541             2         126       549796    485
542             2         127       550333    535

[9 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
494  6xbr38yopd      fmgb      1       1      catch      fbs   ngapapu
495  6xbr38yopd      fmgb      1       1   critical      mbs    kawuka

       random_id condition  block  system trial_type selectee selection  \
1958  eeyykmwnln      fmbg      2       6   critical      mbd    goviku
1959  eeyykmwnln      fmbg      2       6   critical      fbd    lawolu
1960  eeyykmwnln      fmbg      2       6   critical      mzd    lawolu
1961  eeyykmwnln      fmbg      2       6   critical      fzs    lawolu
1962  eeyykmwnln      fmbg      2       6   critical      mzs    lawolu
1963  eeyykmwnln      fmbg      2       6   critical      fzd    lawolu
1964  eeyykmwnln      fmbg      2       6      catch      mbs    goviku

     expected  correct  undo  ...  generaliser2_term generaliser3  \
1958   goviku        1     0  ...             lawolu          NaN
1959   lawolu        1     0  ...             lawolu          NaN
1960   lawolu        1     0  ...             lawolu          NaN
1961   lawolu        1     0  ...             lawolu          NaN
1962   lawolu        1     0  ...             lawolu          NaN
1963   lawolu        1     0  ...             lawolu          NaN
1964   goviku        1     0  ...             lawolu          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1958               NaN          NaN               NaN          NaN
1959               NaN          NaN               NaN          NaN
1960               NaN          NaN               NaN          NaN
1961               NaN          NaN               NaN          NaN
1962               NaN          NaN               NaN          NaN
1963               NaN          NaN               NaN          NaN
1964               NaN          NaN               NaN        False

     button_number trial_index time_elapsed     rt
1958             1          49       397417   6707
1959             2          50       399090   1671
1960             2          51       408376   9284
1961             2          52       419258  10882
1962             2          53       422146   2887
1963             2          54       425269   3121
1964             1          55       433571   8301

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1966  eeyykmwnln      fmbg      3       7   critical      fzd  męwaqïfe
1967  eeyykmwnln      fmbg      3       7   critical      mbd  męwaqïfe
1968  eeyykmwnln      fmbg      3       7   critical      mbs  męwaqïfe
1969  eeyykmwnln      fmbg      3       7      catch      fzs  męwaqïfe
1970  eeyykmwnln      fmbg      3       7   critical      fbs  męwaqïfe
1971  eeyykmwnln      fmbg      3       7   critical      mzs      qïru
1972  eeyykmwnln      fmbg      3       7   critical      fbd  męwaqïfe

      expected  correct  undo  ...  generaliser2_term generaliser3  \
1966  męwaqïfe        1     0  ...           męwaqïfe          NaN
1967  męwaqïfe        1     0  ...           męwaqïfe          NaN
1968  męwaqïfe        1     0  ...           męwaqïfe          NaN
1969  męwaqïfe        1     0  ...           męwaqïfe          NaN
1970  męwaqïfe        1     0  ...           męwaqïfe          NaN
1971      qïru        1     0  ...           męwaqïfe          NaN
1972  męwaqïfe        1     0  ...           męwaqïfe          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1966               NaN          NaN               NaN          NaN
1967               NaN          NaN               NaN          NaN
1968               NaN          NaN               NaN          NaN
1969               NaN          NaN               NaN        False
1970               NaN          NaN               NaN          NaN
1971               NaN          NaN               NaN          NaN
1972               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed    rt
1966             1          68       497361  2280
1967             1          69       500045  2683
1968             1          70       501489  1443
1969             1          71       503301  1811
1970             1          72       504602  1300
1971             0          73       506411  1808
1972             1          74       507730  1317

[7 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
964  9enmmxzrqm      mfgb      1       0   critical      fbs      kïmy
965  9enmmxzrqm      mfgb      1       0   critical      fzd    hïlaki
966  9enmmxzrqm      mfgb      1       0   critical      mzs      kïmy
967  9enmmxzrqm      mfgb      1       0   critical      mzd    hïlaki
968  9enmmxzrqm      mfgb      1       0   critical      mbd    hïlaki
969  9enmmxzrqm      mfgb      1       0   critical      fzs      kïmy
970  9enmmxzrqm      mfgb      1       0   critical      fbd    hïlaki
978  9enmmxzrqm      mfgb      1       0   critical      fbs      kïmy
979  9enmmxzrqm      mfgb      1       0   critical      fzd  lobowaby
980  9enmmxzrqm      mfgb      1       0   critical      mzs      kïmy
981  9enmmxzrqm      mfgb      1       0   critical      mzd  lobowaby
982  9enmmxzrqm      mfgb      1       0   critical      mbd  lobowaby
983  9enmmxzrqm      mfgb      1       0   critical      fzs      kïmy
984  9enmmxzrqm      mfgb      1       0   critical      fbd  lobowaby
985  9enmmxzrqm      mfgb      1       0   critical        b      bybï
986  9enmmxzrqm      mfgb      1       0      catch      mbs      kïmy

    expected  correct  undo  ...  generaliser2_term generaliser3  \
964     kïmy        1     0  ...             hïlaki          NaN
965     kïmy        0     0  ...             hïlaki          NaN
966     kïmy        1     0  ...             hïlaki          NaN
967     kïmy        0     0  ...             hïlaki          NaN
968     kïmy        0     0  ...             hïlaki          NaN
969     kïmy        1     0  ...             hïlaki          NaN
970     kïmy        0     0  ...             hïlaki          NaN
978     kïmy        1     0  ...             hïlaki          NaN
979     kïmy        0     0  ...             hïlaki          fzd
980     kïmy        1     0  ...             hïlaki          fzd
981     kïmy        0     0  ...             hïlaki          fzd
982     kïmy        0     0  ...             hïlaki          fzd
983     kïmy        1     0  ...             hïlaki          fzd
984     kïmy        0     0  ...             hïlaki          fzd
985   hïlaki        0     0  ...             hïlaki          fzd
986     kïmy        1     0  ...             hïlaki          fzd

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
964               NaN          NaN               NaN          NaN
965               NaN          NaN               NaN          NaN
966               NaN          NaN               NaN          NaN
967               NaN          NaN               NaN          NaN
968               NaN          NaN               NaN          NaN
969               NaN          NaN               NaN          NaN
970               NaN          NaN               NaN          NaN
978               NaN          NaN               NaN          NaN
979          lobowaby          NaN               NaN          NaN
980          lobowaby          NaN               NaN          NaN
981          lobowaby          mzd          lobowaby          NaN
982          lobowaby          mzd          lobowaby          NaN
983          lobowaby          mzd          lobowaby          NaN
984          lobowaby          mzd          lobowaby          NaN
985          lobowaby          mzd          lobowaby          NaN
986          lobowaby          mzd          lobowaby        False

    button_number trial_index time_elapsed     rt
964             1          24       363503  12816
965             0          25       365884   2374
966             1          26       370388   4502
967             0          27       371950   1556
968             0          28       373584   1630
969             1          29       375503   1915
970             0          30       377204   1698
978             1          38       396419   7921
979             3          39       401719   5296
980             1          40       403867   2145
981             3          41       406099   2228
982             3          42       409452   3350
983             1          43       411753   2297
984             3          44       413052   1296
985             2          45       414537   1481
986             1          46       417454   2913

[16 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1042  9enmmxzrqm      mfgb      7       1   critical      mzd    adeçim
1043  9enmmxzrqm      mfgb      7       1   critical      fbs    ømenad
1044  9enmmxzrqm      mfgb      7       1   critical      mbd    adeçim
1045  9enmmxzrqm      mfgb      7       1   critical      mzs  içiqusem
1046  9enmmxzrqm      mfgb      7       1   critical      fzd    adeçim
1047  9enmmxzrqm      mfgb      7       1   critical      fbd    adeçim
1048  9enmmxzrqm      mfgb      7       1      catch      fzs    ømenad

      expected  correct  undo  ...  generaliser2_term generaliser3  \
1042  içiqusem        0     0  ...           içiqusem          mzd
1043    ømenad        1     0  ...           içiqusem          mzd
1044  içiqusem        0     0  ...           içiqusem          mzd
1045  içiqusem        1     0  ...           içiqusem          mzd
1046    ømenad        0     0  ...           içiqusem          mzd
1047    ømenad        0     0  ...           içiqusem          mzd
1048    ømenad        1     0  ...           içiqusem          mzd

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1042            adeçim          NaN               NaN          NaN
1043            adeçim          NaN               NaN          NaN
1044            adeçim          mbd            adeçim          NaN
1045            adeçim          mbd            adeçim          NaN
1046            adeçim          mbd            adeçim          NaN
1047            adeçim          mbd            adeçim          NaN
1048            adeçim          mbd            adeçim        False

     button_number trial_index time_elapsed     rt
1042             1         168       924205  17851
1043             2         169       928873   4665
1044             1         170       933324   4449
1045             3         171       936025   2699
1046             1         172       938376   2349
1047             1         173       940843   2464
1048             2         174       955678  14833

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1050  9enmmxzrqm      mfgb      8       2   critical      mbd    goozăi
1051  9enmmxzrqm      mfgb      8       2   critical      fzs    nyumuo
1052  9enmmxzrqm      mfgb      8       2      catch      fzd       gêă
1053  9enmmxzrqm      mfgb      8       2   critical      fbd    hyonăo
1054  9enmmxzrqm      mfgb      8       2   critical      mzd       gêă
1055  9enmmxzrqm      mfgb      8       2   critical      mzs    nyumuo
1056  9enmmxzrqm      mfgb      8       2   critical      mbs    hyonăo

     expected  correct  undo  ...  generaliser2_term generaliser3  \
1050   goozăi        1     0  ...                gêă          NaN
1051      gêă        0     0  ...                gêă          fzs
1052      gêă        1     0  ...                gêă          fzs
1053   goozăi        0     0  ...                gêă          fzs
1054      gêă        1     0  ...                gêă          fzs
1055      gêă        0     0  ...                gêă          fzs
1056   goozăi        0     0  ...                gêă          fzs

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1050               NaN          NaN               NaN          NaN
1051            nyumuo          NaN               NaN          NaN
1052            nyumuo          NaN               NaN        False
1053            nyumuo          NaN               NaN          NaN
1054            nyumuo          NaN               NaN          NaN
1055            nyumuo          mzs            nyumuo          NaN
1056            nyumuo          mzs            nyumuo          NaN

     button_number trial_index time_elapsed    rt
1050             3         187       973296  4396
1051             1         188       978099  4800
1052             2         189       982585  4484
1053             0         190       989633  7047
1054             2         191       994001  4365
1055             1         192       996036  2033
1056             0         193      1001354  5316

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
996   9enmmxzrqm      mfgb      3       3   critical      mbs     vruži
998   9enmmxzrqm      mfgb      3       3   critical      mbs    cžunge
1000  9enmmxzrqm      mfgb      3       3   critical      mbs  rbāranžā
1001  9enmmxzrqm      mfgb      3       3      catch      fbd  vropcāre
1002  9enmmxzrqm      mfgb      3       3   critical      mzd  vropcāre
1003  9enmmxzrqm      mfgb      3       3   critical      fzd    cžunge
1004  9enmmxzrqm      mfgb      3       3   critical      mzs  rbāranžā
1005  9enmmxzrqm      mfgb      3       3   critical      fbs  rbāranžā
1006  9enmmxzrqm      mfgb      3       3   critical      fzs  rbāranžā

      expected  correct  undo  ...  generaliser2_term generaliser3  \
996     cžunge        0     0  ...           vropcāre          mbs
998     cžunge        1     0  ...           vropcāre          mbs
1000    cžunge        0     0  ...           vropcāre          mbs
1001  vropcāre        1     0  ...           vropcāre          mbs
1002  vropcāre        1     0  ...           vropcāre          mbs
1003    cžunge        1     0  ...           vropcāre          mbs
1004  vropcāre        0     0  ...           vropcāre          mbs
1005  vropcāre        0     0  ...           vropcāre          mbs
1006    cžunge        0     0  ...           vropcāre          mbs

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
996              vruži          NaN               NaN          NaN
998              vruži          NaN               NaN          NaN
1000             vruži          NaN               NaN          NaN
1001             vruži          NaN               NaN        False
1002             vruži          NaN               NaN          NaN
1003             vruži          NaN               NaN          NaN
1004             vruži          NaN               NaN          NaN
1005             vruži          NaN               NaN          NaN
1006             vruži          NaN               NaN          NaN

     button_number trial_index time_elapsed    rt
996              0          78       555373  6082
998              3          80       567572  5545
1000             2          82       570257  1264
1001             1          83       578943  8684
1002             1          84       582376  3431
1003             3          85       587046  4667
1004             2          86       593680  6631
1005             2          87       594431   749
1006             2          88       601016  6582

[9 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1034  9enmmxzrqm      mfgb      6       4      catch      fbs  beiguumu
1035  9enmmxzrqm      mfgb      6       4   critical      mbs  canšuehu
1036  9enmmxzrqm      mfgb      6       4   critical      fzd     nuubö
1037  9enmmxzrqm      mfgb      6       4   critical      mbd     nuubö
1038  9enmmxzrqm      mfgb      6       4   critical      mzd     nuubö
1039  9enmmxzrqm      mfgb      6       4   critical      fbd  šaaqaude
1040  9enmmxzrqm      mfgb      6       4   critical      mzs  canšuehu

      expected  correct  undo  ...  generaliser2_term generaliser3  \
1034  beiguumu        1     0  ...           canšuehu          NaN
1035  canšuehu        1     0  ...           canšuehu          NaN
1036  canšuehu        0     0  ...           canšuehu          fzd
1037  canšuehu        0     0  ...           canšuehu          fzd
1038  canšuehu        0     0  ...           canšuehu          fzd
1039  beiguumu        0     0  ...           canšuehu          fzd
1040  canšuehu        1     0  ...           canšuehu          fzd

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1034               NaN          NaN               NaN        False
1035               NaN          NaN               NaN          NaN
1036             nuubö          NaN               NaN          NaN
1037             nuubö          mbd             nuubö          NaN
1038             nuubö          mbd             nuubö          NaN
1039             nuubö          mbd             nuubö          NaN
1040             nuubö          mbd             nuubö          NaN

     button_number trial_index time_elapsed     rt
1034             1         149       861432  13431
1035             2         150       868518   7084
1036             3         151       875936   7415
1037             3         152       879486   3548
1038             3         153       880636   1148
1039             0         154       885803   5164
1040             2         155       888753   2946

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1016  9enmmxzrqm      mfgb      5       5   critical      mbd    lawolu
1017  9enmmxzrqm      mfgb      5       5      catch      fbs    goviku
1018  9enmmxzrqm      mfgb      5       5   critical      mbs      luge
1019  9enmmxzrqm      mfgb      5       5   critical      fbd    lawolu
1020  9enmmxzrqm      mfgb      5       5   critical      mzs      luge
1021  9enmmxzrqm      mfgb      5       5   critical      mzd    lawolu
1022  9enmmxzrqm      mfgb      5       5   critical      fzs    kawuka
1028  9enmmxzrqm      mfgb      5       5   critical      mbs    goviku
1029  9enmmxzrqm      mfgb      5       5   critical      fbd      luge
1030  9enmmxzrqm      mfgb      5       5   critical      mzs    goviku
1031  9enmmxzrqm      mfgb      5       5   critical      mzd      luge
1032  9enmmxzrqm      mfgb      5       5   critical      fzs    lawolu

     expected  correct  undo  ...  generaliser2_term generaliser3  \
1016   goviku        0     0  ...             goviku          mbd
1017   goviku        1     0  ...             goviku          mbd
1018   goviku        0     0  ...             goviku          mbd
1019   goviku        0     0  ...             goviku          mbd
1020   goviku        0     0  ...             goviku          mbd
1021   goviku        0     0  ...             goviku          mbd
1022   kawuka        1     0  ...             goviku          mbd
1028   goviku        1     0  ...             goviku          mbd
1029   goviku        0     0  ...             goviku          mbd
1030   goviku        1     0  ...             goviku          mbd
1031   goviku        0     0  ...             goviku          mbd
1032   kawuka        0     0  ...             goviku          mbd

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1016            lawolu          NaN               NaN          NaN
1017            lawolu          NaN               NaN        False
1018            lawolu          NaN               NaN          NaN
1019            lawolu          fbd            lawolu          NaN
1020            lawolu          fbd            lawolu          NaN
1021            lawolu          fbd            lawolu          NaN
1022            lawolu          fbd            lawolu          NaN
1028            lawolu          fbd            lawolu          NaN
1029            lawolu          fbd            lawolu          NaN
1030            lawolu          fbd            lawolu          NaN
1031            lawolu          fbd            lawolu          NaN

      random_id condition  block  system trial_type selectee selection  \
768  4k1ad46eg9      fmbg      5       3   critical      fzd    kawuka
769  4k1ad46eg9      fmbg      5       3   critical      mbs      wupu
770  4k1ad46eg9      fmbg      5       3   critical      fbs      wupu
771  4k1ad46eg9      fmbg      5       3      catch      mbd    kawuka
772  4k1ad46eg9      fmbg      5       3   critical      fbd    kawuka
773  4k1ad46eg9      fmbg      5       3   critical      mzd    kawuka
774  4k1ad46eg9      fmbg      5       3   critical      fzs      wupu

    expected  correct  undo  ...  generaliser2_term generaliser3  \
768   kawuka        1     0  ...               wupu          NaN
769   kawuka        0     0  ...               wupu          NaN
770     wupu        1     0  ...               wupu          NaN
771   kawuka        1     0  ...               wupu          NaN
772     wupu        0     0  ...               wupu          NaN
773     wupu        0     0  ...               wupu          NaN
774   kawuka        0     0  ...               wupu          NaN

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
768               NaN          NaN               NaN          NaN
769               NaN          NaN               NaN          NaN
770               NaN          NaN               NaN          NaN
771               NaN          NaN               NaN        False
772               NaN          NaN               NaN          NaN
773               NaN          NaN               NaN          NaN
774               NaN          NaN               NaN          NaN

    button_number trial_index time_elapsed     rt
768             2         122      1808959  44762
769             3         123      1837439  28468
770             3         124      1846326   8881
771             2         125      1851186   4853
772             2         126      1858127   6931
773             2         127      1863488   5351
774             3         128      1872441   8943

[7 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
714  4k1ad46eg9      fmbg      1       4   critical      mbd  bokokohï
715  4k1ad46eg9      fmbg      1       4   critical      mbs  bokokohï
716  4k1ad46eg9      fmbg      1       4   critical      mzs  bokokohï
720  4k1ad46eg9      fmbg      1       4   critical      mbd  bokokohï
721  4k1ad46eg9      fmbg      1       4   critical      mbs    morïky
724  4k1ad46eg9      fmbg      1       4   critical      mbd      kïmy
725  4k1ad46eg9      fmbg      1       4   critical      mbs  bokokohï
726  4k1ad46eg9      fmbg      1       4   critical      mzs  bokokohï
727  4k1ad46eg9      fmbg      1       4   critical      fbs      kïmy
728  4k1ad46eg9      fmbg      1       4   critical      mzd      kïmy
734  4k1ad46eg9      fmbg      1       4   critical      mbd  bokokohï
735  4k1ad46eg9      fmbg      1       4   critical      mbs  bokokohï
736  4k1ad46eg9      fmbg      1       4   critical      mzs      kïmy
737  4k1ad46eg9      fmbg      1       4   critical      fbs  bokokohï
738  4k1ad46eg9      fmbg      1       4   critical      mzd      kïmy
739  4k1ad46eg9      fmbg      1       4   critical      fzs      kïmy
740  4k1ad46eg9      fmbg      1       4      catch      fbd  bokokohï

     expected  correct  undo  ...  generaliser2_term generaliser3  \
714      kïmy        0     0  ...               kïmy          NaN
715      kïmy        0     0  ...               kïmy          NaN
716      kïmy        0     0  ...               kïmy          NaN
720      kïmy        0     0  ...               kïmy          NaN
721      kïmy        0     0  ...               kïmy          mbs
724      kïmy        1     0  ...               kïmy          mbs
725      kïmy        0     0  ...               kïmy          mbs
726      kïmy        0     0  ...               kïmy          mbs
727  bokokohï        0     0  ...               kïmy          mbs
728      kïmy        1     0  ...               kïmy          mbs
734      kïmy        0     0  ...               kïmy          mbs
735      kïmy        0     0  ...               kïmy          mbs
736      kïmy        1     0  ...               kïmy          mbs
737  bokokohï        1     0  ...               kïmy          mbs
738      kïmy        1     0  ...               kïmy          mbs
739      kïmy        1     0  ...               kïmy          mbs
740  bokokohï        1     0  ...               kïmy          mbs

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
714               NaN          NaN               NaN          NaN
715               NaN          NaN               NaN          NaN
716               NaN          NaN               NaN          NaN
720               NaN          NaN               NaN          NaN
721            morïky          NaN               NaN          NaN
724            morïky          NaN               NaN          NaN
725            morïky          NaN               NaN          NaN
726            morïky          NaN               NaN          NaN
727            morïky          NaN               NaN          NaN
728            morïky          NaN               NaN          NaN
734            morïky          NaN               NaN          NaN
735            morïky          NaN               NaN          NaN
736            morïky          NaN               NaN          NaN
737            morïky          NaN               NaN          NaN
738            morïky          NaN               NaN          NaN
739            morïky          NaN               NaN          NaN
740            morïky          NaN               NaN        False

    button_number trial_index time_elapsed      rt
714             0          26       662332    9005
715             0          27       667657    5312
716             0          28       669850    2183
720             0          32       681937    8433
721             1          33       706082   24138
724             2          36       778043   68366
725             0          37       785020    6969
726             0          38       836476   51444
727             2          39       949582  113094
728             2          40      1010433   60836
734             0          46      1156686  130462
735             0          47      1168827   12129
736             2          48      1175104    6269
737             0          49      1182647    7532
738             2          50      1189786    7125
739             2          51      1225455   35657
740             0          52      1235568   10105

[17 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
752  4k1ad46eg9      fmbg      3       5   critical      fbs  kvurddåh
753  4k1ad46eg9      fmbg      3       5   critical      mzs  smêvskêv
754  4k1ad46eg9      fmbg      3       5      catch      fzd  kvurddåh
755  4k1ad46eg9      fmbg      3       5   critical      mzd  kvurddåh
756  4k1ad46eg9      fmbg      3       5   critical      fbd  smêvskêv
757  4k1ad46eg9      fmbg      3       5   critical      fzs  smêvskêv
758  4k1ad46eg9      fmbg      3       5   critical      mbs  kvurddåh

     expected  correct  undo  ...  generaliser2_term generaliser3  \
752  smêvskêv        0     0  ...           smêvskêv          NaN
753  smêvskêv        1     0  ...           smêvskêv          NaN
754  kvurddåh        1     0  ...           smêvskêv          NaN
755  smêvskêv        0     0  ...           smêvskêv          NaN
756  smêvskêv        1     0  ...           smêvskêv          NaN
757  kvurddåh        0     0  ...           smêvskêv          NaN
758  smêvskêv        0     0  ...           smêvskêv          NaN

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
752               NaN          NaN               NaN          NaN
753               NaN          NaN               NaN          NaN
754               NaN          NaN               NaN        False
755               NaN          NaN               NaN          NaN
756               NaN          NaN               NaN          NaN
757               NaN          NaN               NaN          NaN
758               NaN          NaN               NaN          NaN

    button_number trial_index time_elapsed     rt
752             3          84      1534845  38538
753             0          85      1549645  14789
754             3          86      1557588   7932
755             3          87      1566098   8496
756             0          88      1573918   7814
757             0          89      1582621   8695
758             3          90      1588613   5980

[7 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
792  4k1ad46eg9      fmbg      8       6   critical      mbd     vbāžo
793  4k1ad46eg9      fmbg      8       6   critical      mzs    ngcāžo
794  4k1ad46eg9      fmbg      8       6      catch      fbs     vbāžo
797  4k1ad46eg9      fmbg      8       6   critical      mbd     vbāžo
798  4k1ad46eg9      fmbg      8       6   critical      mzs     vbāžo
799  4k1ad46eg9      fmbg      8       6   critical      fzs     vbāžo
800  4k1ad46eg9      fmbg      8       6   critical      fzd    ngcāžo
801  4k1ad46eg9      fmbg      8       6   critical      fbd    ngcāžo
802  4k1ad46eg9      fmbg      8       6   critical      mzd    ngcāžo

    expected  correct  undo  ...  generaliser2_term generaliser3  \
792   ngcāžo        0     0  ...              vbāžo          NaN
793    vbāžo        0     0  ...              vbāžo          NaN
794    vbāžo        1     0  ...              vbāžo          NaN
797   ngcāžo        0     0  ...              vbāžo          NaN
798    vbāžo        1     0  ...              vbāžo          NaN
799    vbāžo        1     0  ...              vbāžo          NaN
800    vbāžo        0     0  ...              vbāžo          NaN
801    vbāžo        0     0  ...              vbāžo          NaN
802    vbāžo        0     0  ...              vbāžo          NaN

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
792               NaN          NaN               NaN          NaN
793               NaN          NaN               NaN          NaN
794               NaN          NaN               NaN        False
797               NaN          NaN               NaN          NaN
798               NaN          NaN               NaN          NaN
799               NaN          NaN               NaN          NaN
800               NaN          NaN               NaN          NaN
801               NaN          NaN               NaN          NaN
802               NaN          NaN               NaN          NaN

    button_number trial_index time_elapsed     rt
792             3         179      2172398  19408
793             1         180      2178214   5803
794             3         181      2184699   6473
797             3         184      2228507  25755
798             3         185      2243880  15361
799             3         186      2254115  10224
800             1         187      2263924   9798
801             1         188      2269756   5820
802             1         189      2276521   6756

[9 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
784  4k1ad46eg9      fmbg      7       7   critical      fzs    emøyeç
785  4k1ad46eg9      fmbg      7       7   critical      mbs  aqinudød
786  4k1ad46eg9      fmbg      7       7      catch      mzs    emøyeç
787  4k1ad46eg9      fmbg      7       7   critical      mzd  aqinudød
788  4k1ad46eg9      fmbg      7       7   critical      fzd  aqinudød
789  4k1ad46eg9      fmbg      7       7   critical      fbd    emøyeç
790  4k1ad46eg9      fmbg      7       7   critical      mbd    emøyeç

     expected  correct  undo  ...  generaliser2_term generaliser3  \
784  aqinudød        0     0  ...           aqinudød          NaN
785  aqinudød        1     0  ...           aqinudød          NaN
786    emøyeç        1     0  ...           aqinudød          NaN
787    emøyeç        0     0  ...           aqinudød          NaN
788  aqinudød        1     0  ...           aqinudød          NaN
789  aqinudød        0     0  ...           aqinudød          NaN
790  aqinudød        0     0  ...           aqinudød          NaN

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
784               NaN          NaN               NaN          NaN
785               NaN          NaN               NaN          NaN
786               NaN          NaN               NaN        False
787               NaN          NaN               NaN          NaN
788               NaN          NaN               NaN          NaN
789               NaN          NaN               NaN          NaN
790               NaN          NaN               NaN          NaN

    button_number trial_index time_elapsed     rt
784             2         160      2055325  31594
785             1         161      2062570   7234
786             2         162      2070246   7665
787             1         163      2086099  15846
788             1         164      2093169   7058
789             2         165      2102787   9607
790             2         166      2113501  10702

[7 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \
114  chksbtwpa9      mfbg      7       0   critical      mbs    nyumuo
115  chksbtwpa9      mfbg      7       0   critical      mzs    nyumuo
116  chksbtwpa9      mfbg      7       0   critical      fzs    nyumuo
117  chksbtwpa9      mfbg      7       0   critical      mzd    nyumuo
118  chksbtwpa9      mfbg      7       0      catch        z    nyumuo
119  chksbtwpa9      mfbg      7       0   critical      mbd    nyumuo
120  chksbtwpa9      mfbg      7       0   critical      fbd    nyumuo
121  chksbtwpa9      mfbg      7       0   critical        b    nyumuo
122  chksbtwpa9      mfbg      7       0   critical      fbs    nyumuo

    expected  correct  undo  ...  generaliser2_term generaliser3  \
114   nyumuo        1     0  ...             nyumuo          NaN
115   nyumuo        1     0  ...             nyumuo          NaN
116   nyumuo        1     0  ...             nyumuo          NaN
117   nyumuo        1     0  ...             nyumuo          NaN
118   nyumuo        1     0  ...             nyumuo          NaN
119   nyumuo        1     0  ...             nyumuo          NaN
120   nyumuo        1     0  ...             nyumuo          NaN
121   nyumuo        1     0  ...             nyumuo          NaN
122   nyumuo        1     0  ...             nyumuo          NaN

    generaliser3_term generaliser4 generaliser4_term catch_failed  \
114               NaN          NaN               NaN          NaN
115               NaN          NaN               NaN          NaN
116               NaN          NaN               NaN          NaN
117               NaN          NaN               NaN          NaN
118               NaN          NaN               NaN        False
119               NaN          NaN               NaN          NaN
120               NaN          NaN               NaN          NaN
121               NaN          NaN               NaN          NaN
122               NaN          NaN               NaN          NaN

    button_number trial_index time_elapsed    rt
114             2         138       342638  4881
115             2         139       343092   452
116             2         140       343733   638
117             2         141       344321   586
118             2         142       344991   668
119             2         143       345680   685
120             2         144       346267   585
121             2         145       346837   567
122             2         146       347440   601

[9 rows x 24 columns]
     random_id condition  block  system trial_type selectee selection  \
82  chksbtwpa9      mfbg      3       1   critical      mzs    ngcāžo
83  chksbtwpa9      mfbg      3       1   critical      fzs     byure
84  chksbtwpa9      mfbg      3       1      catch      mbd    ngcāžo
85  chksbtwpa9      mfbg      3       1   critical      mbs    ngcāžo
86  chksbtwpa9      mfbg      3       1   critical      fbs     byure
87  chksbtwpa9      mfbg      3       1   critical      fbd     byure
88  chksbtwpa9      mfbg      3       1   critical      mzd    ngcāžo

   expected  correct  undo  ...  generaliser2_term generaliser3  \
82   ngcāžo        1     0  ...             ngcāžo          NaN
83    byure        1     0  ...             ngcāžo          NaN
84   ngcāžo        1     0  ...             ngcāžo          NaN
85   ngcāžo        1     0  ...             ngcāžo          NaN
86    byure        1     0  ...             ngcāžo          NaN
87    byure        1     0  ...             ngcāžo          NaN
88   ngcāžo        1     0  ...             ngcāžo          NaN

   generaliser3_term generaliser4 generaliser4_term catch_failed  \
82               NaN          NaN               NaN          NaN
83               NaN          NaN               NaN          NaN
84               NaN          NaN               NaN        False
85               NaN          NaN               NaN          NaN
86               NaN          NaN               NaN          NaN
87               NaN          NaN               NaN          NaN
88               NaN          NaN               NaN          NaN

   button_number trial_index time_elapsed    rt
82             0          64       235714  2794
83             1          65       237792  2075
84             0          66       239439  1644
85             0          67       241010  1568
86             1          68       242670  1658
87             1          69       243557   884
88             0          70       244542   982

[7 rows x 24 columns]
     random_id condition  block  system trial_type selectee selection  \
66  chksbtwpa9      mfbg      1       2   critical      fzs  rhymsvåd
67  chksbtwpa9      mfbg      1       2   critical      mzd  kvurddåh
68  chksbtwpa9      mfbg      1       2   critical      fbd  kvurddåh
69  chksbtwpa9      mfbg      1       2   critical      mzs  rhymsvåd
70  chksbtwpa9      mfbg      1       2   critical      mbs  rhymsvåd
71  chksbtwpa9      mfbg      1       2      catch      fbs  rhymsvåd
72  chksbtwpa9      mfbg      1       2   critical      mbd  kvurddåh

    expected  correct  undo  ...  generaliser2_term generaliser3  \
66  kvurddåh        0     0  ...           kvurddåh          NaN
67  kvurddåh        1     0  ...           kvurddåh          NaN
68  rhymsvåd        0     0  ...           kvurddåh          NaN
69  kvurddåh        0     0  ...           kvurddåh          NaN
70  rhymsvåd        1     0  ...           kvurddåh          NaN
71  rhymsvåd        1     0  ...           kvurddåh          NaN
72  rhymsvåd        0     0  ...           kvurddåh          NaN

   generaliser3_term generaliser4 generaliser4_term catch_failed  \
66               NaN          NaN               NaN          NaN
67               NaN          NaN               NaN          NaN
68               NaN          NaN               NaN          NaN
69               NaN          NaN               NaN          NaN
70               NaN          NaN               NaN          NaN
71               NaN          NaN               NaN        False
72               NaN          NaN               NaN          NaN

   button_number trial_index time_elapsed    rt
66             0          26       154768  3627
67             1          27       157842  3070
68             1          28       159115  1271
69             0          29       160532  1413
70             0          30       162786  2252
71             0          31       164620  1831
72             1          32       165572   949

[7 rows x 24 columns]
      random_id condition  block  system trial_type selectee selection  \

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2777  srcyko4mfl      fmbg      2       2   critical      mbd     byure
2778  srcyko4mfl      fmbg      2       2      catch      mbs    cžunge
2779  srcyko4mfl      fmbg      2       2   critical      mzd     byure
2780  srcyko4mfl      fmbg      2       2   critical      fzd     vruži
2781  srcyko4mfl      fmbg      2       2   critical      fbs     vruži
2782  srcyko4mfl      fmbg      2       2   critical      fbd     vruži
2783  srcyko4mfl      fmbg      2       2   critical      mzs    cžunge

     expected  correct  undo  ...  generaliser2_term generaliser3  \
2777   cžunge        0     0  ...              vruži          mbd
2778   cžunge        1     0  ...              vruži          mbd
2779    vruži        0     0  ...              vruži          mbd
2780    vruži        1     0  ...              vruži          mbd
2781   cžunge        0     0  ...              vruži          mbd
2782   cžunge        0     0  ...              vruži          mbd
2783    vruži        0     0  ...              vruži          mbd

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2777             byure          NaN               NaN          NaN
2778             byure          NaN               NaN        False
2779             byure          mzd             byure          NaN
2780             byure          mzd             byure          NaN
2781             byure          mzd             byure          NaN
2782             byure          mzd             byure          NaN
2783             byure          mzd             byure          NaN

     button_number trial_index time_elapsed     rt
2777             3          45       204624  29648
2778             2          46       207708   3080
2779             3          47       209392   1681
2780             0          48       214525   5131
2781             0          49       221091   6563
2782             0          50       228075   6980
2783             2          51       230291   2213

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2813  srcyko4mfl      fmbg      6       3   critical      fzd  içiqusem
2814  srcyko4mfl      fmbg      6       3   critical      mzs  orinoçim
2815  srcyko4mfl      fmbg      6       3   critical      fbs  içiqusem
2816  srcyko4mfl      fmbg      6       3   critical      fzs  orinoçim
2817  srcyko4mfl      fmbg      6       3      catch      mbs  içiqusem
2818  srcyko4mfl      fmbg      6       3   critical      mzd  içiqusem
2819  srcyko4mfl      fmbg      6       3   critical      mbd  orinoçim

      expected  correct  undo  ...  generaliser2_term generaliser3  \
2813  içiqusem        1     0  ...           orinoçim          NaN
2814  orinoçim        1     0  ...           orinoçim          NaN
2815  orinoçim        0     0  ...           orinoçim          NaN
2816  içiqusem        0     0  ...           orinoçim          NaN
2817  içiqusem        1     0  ...           orinoçim          NaN
2818  orinoçim        0     0  ...           orinoçim          NaN
2819  içiqusem        0     0  ...           orinoçim          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2813               NaN          NaN               NaN          NaN
2814               NaN          NaN               NaN          NaN
2815               NaN          NaN               NaN          NaN
2816               NaN          NaN               NaN          NaN
2817               NaN          NaN               NaN        False
2818               NaN          NaN               NaN          NaN
2819               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed    rt
2813             3         123       394193  4631
2814             0         124       397826  3630
2815             3         125       403626  5798
2816             0         126       409381  5752
2817             3         127       412143  2758
2818             3         128       414211  2066
2819             0         129       417159  2946

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2829  srcyko4mfl      fmbg      8       4   critical      mzd  idanuluf
2830  srcyko4mfl      fmbg      8       4   critical      fzs  idanuluf
2831  srcyko4mfl      fmbg      8       4      catch      mbs  idanuluf
2832  srcyko4mfl      fmbg      8       4   critical      mzs  idanuluf
2833  srcyko4mfl      fmbg      8       4   critical      mbd  idanuluf
2834  srcyko4mfl      fmbg      8       4   critical      fzd  idanuluf
2835  srcyko4mfl      fmbg      8       4   critical      fbs    ulywaf

      expected  correct  undo  ...  generaliser2_term generaliser3  \
2829  idanuluf        1     0  ...           idanuluf          NaN
2830  idanuluf        1     0  ...           idanuluf          NaN
2831  idanuluf        1     0  ...           idanuluf          NaN
2832  idanuluf        1     0  ...           idanuluf          NaN
2833  idanuluf        1     0  ...           idanuluf          NaN
2834  idanuluf        1     0  ...           idanuluf          NaN
2835    ulywaf        1     0  ...           idanuluf          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2829               NaN          NaN               NaN          NaN
2830               NaN          NaN               NaN          NaN
2831               NaN          NaN               NaN        False
2832               NaN          NaN               NaN          NaN
2833               NaN          NaN               NaN          NaN
2834               NaN          NaN               NaN          NaN
2835               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed    rt
2829             3         161       495560  9096
2830             3         162       501545  5982
2831             3         163       503877  2330
2832             3         164       504844   963
2833             3         165       505612   766
2834             3         166       507110  1496
2835             2         167       509378  2264

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2785  srcyko4mfl      fmbg      3       5   critical      mbs    goviku
2786  srcyko4mfl      fmbg      3       5   critical      mbd    goviku
2787  srcyko4mfl      fmbg      3       5   critical      mzs    goviku
2788  srcyko4mfl      fmbg      3       5   critical      fzd    goviku
2790  srcyko4mfl      fmbg      3       5   critical      fzd   ngapapu
2791  srcyko4mfl      fmbg      3       5   critical      fbd    goviku
2792  srcyko4mfl      fmbg      3       5      catch      fzs   ngapapu
2793  srcyko4mfl      fmbg      3       5   critical      mzd    goviku

     expected  correct  undo  ...  generaliser2_term generaliser3  \
2785   goviku        1     0  ...             goviku          NaN
2786   goviku        1     0  ...             goviku          NaN
2787   goviku        1     0  ...             goviku          NaN
2788  ngapapu        0     0  ...             goviku          NaN
2790  ngapapu        1     0  ...             goviku          NaN
2791   goviku        1     0  ...             goviku          NaN
2792  ngapapu        1     0  ...             goviku          NaN
2793   goviku        1     0  ...             goviku          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2785               NaN          NaN               NaN          NaN
2786               NaN          NaN               NaN          NaN
2787               NaN          NaN               NaN          NaN
2788               NaN          NaN               NaN          NaN
2790               NaN          NaN               NaN          NaN
2791               NaN          NaN               NaN          NaN
2792               NaN          NaN               NaN        False
2793               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed     rt
2785             3          64       251576   4349
2786             3          65       254710   3131
2787             3          66       265343  10631
2788             3          67       265876    530
2790             1          69       271841   3780
2791             3          70       274592   2747
2792             1          71       278725   4131
2793             3          72       282027   3298

[8 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2795  srcyko4mfl      fmbg      4       6   critical      fzd     šïïnö
2796  srcyko4mfl      fmbg      4       6   critical      mbs     yaöpe
2797  srcyko4mfl      fmbg      4       6   critical      fzs     šïïnö
2798  srcyko4mfl      fmbg      4       6   critical      fbd     šïïnö
2799  srcyko4mfl      fmbg      4       6   critical      fbs     šïïnö
2800  srcyko4mfl      fmbg      4       6   critical      mzd     šïïnö
2801  srcyko4mfl      fmbg      4       6      catch      mzs     šïïnö

     expected  correct  undo  ...  generaliser2_term generaliser3  \
2795    šïïnö        1     0  ...              šïïnö          NaN
2796    yaöpe        1     0  ...              šïïnö          NaN
2797    šïïnö        1     0  ...              šïïnö          NaN
2798    šïïnö        1     0  ...              šïïnö          NaN
2799    šïïnö        1     0  ...              šïïnö          NaN
2800    šïïnö        1     0  ...              šïïnö          NaN
2801    šïïnö        1     0  ...              šïïnö          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2795               NaN          NaN               NaN          NaN
2796               NaN          NaN               NaN          NaN
2797               NaN          NaN               NaN          NaN
2798               NaN          NaN               NaN          NaN
2799               NaN          NaN               NaN          NaN
2800               NaN          NaN               NaN          NaN
2801               NaN          NaN               NaN        False

     button_number trial_index time_elapsed    rt
2795             1          85       300392  3647
2796             3          86       306959  6563
2797             1          87       308925  1963
2798             1          88       313727  4799
2799             1          89       315576  1845
2800             1          90       318292  2713
2801             1          91       321509  3215

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2769  srcyko4mfl      fmbg      1       7   critical      mzs  kvurddåh
2770  srcyko4mfl      fmbg      1       7      catch      fbs  kvurddåh
2771  srcyko4mfl      fmbg      1       7   critical      fzs  kvurddåh
2772  srcyko4mfl      fmbg      1       7   critical      fbd  rhymsvåd
2773  srcyko4mfl      fmbg      1       7   critical      mbd  rhymsvåd
2774  srcyko4mfl      fmbg      1       7   critical      fzd  rhymsvåd
2775  srcyko4mfl      fmbg      1       7   critical      mbs  kvurddåh

      expected  correct  undo  ...  generaliser2_term generaliser3  \
2769  rhymsvåd        0     0  ...           kvurddåh          NaN
2770  kvurddåh        1     0  ...           kvurddåh          NaN
2771  kvurddåh        1     0  ...           kvurddåh          NaN
2772  kvurddåh        0     0  ...           kvurddåh          NaN
2773  kvurddåh        0     0  ...           kvurddåh          NaN
2774  kvurddåh        0     0  ...           kvurddåh          NaN
2775  kvurddåh        1     0  ...           kvurddåh          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2769               NaN          NaN               NaN          NaN
2770               NaN          NaN               NaN        False
2771               NaN          NaN               NaN          NaN
2772               NaN          NaN               NaN          NaN
2773               NaN          NaN               NaN          NaN
2774               NaN          NaN               NaN          NaN
2775               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed    rt
2769             1          26       136291  7529
2770             1          27       143658  7360
2771             1          28       152207  8546
2772             0          29       158492  6282
2773             0          30       161593  3099
2774             0          31       162860  1265
2775             1          32       164673  1810

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2953  vfc66vqf8v      fmbg      7       0   critical      mzs    huanăa
2954  vfc66vqf8v      fmbg      7       0   critical      fbd    huanăa
2955  vfc66vqf8v      fmbg      7       0   critical      fzd    nyumuo
2956  vfc66vqf8v      fmbg      7       0   critical      mzd    huanăa
2959  vfc66vqf8v      fmbg      7       0   critical      fzd       gêă
2960  vfc66vqf8v      fmbg      7       0   critical      mzd    huanăa
2961  vfc66vqf8v      fmbg      7       0   critical      mbd       gêă
2963  vfc66vqf8v      fmbg      7       0   critical      mbd       gêă
2964  vfc66vqf8v      fmbg      7       0   critical        z    nyumuo
2965  vfc66vqf8v      fmbg      7       0      catch      fzs       gêă
2966  vfc66vqf8v      fmbg      7       0   critical      mbs       gêă
2967  vfc66vqf8v      fmbg      7       0   critical      fbs    huanăa

     expected  correct  undo  ...  generaliser2_term generaliser3  \
2953      gêă        0     0  ...             nyumuo          mzs
2954      gêă        0     0  ...             nyumuo          mzs
2955      gêă        0     0  ...             nyumuo          mzs
2956      gêă        0     0  ...             nyumuo          mzs
2959      gêă        1     0  ...             nyumuo          mzs
2960      gêă        0     0  ...             nyumuo          mzs
2961      gêă        1     0  ...             nyumuo          mzs
2963      gêă        1     0  ...             nyumuo          mzs
2964   nyumuo        1     0  ...             nyumuo          mzs
2965      gêă        1     0  ...             nyumuo          mzs
2966      gêă        1     0  ...             nyumuo          mzs
2967      gêă        0     0  ...             nyumuo          mzs

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2953            huanăa          NaN               NaN          NaN
2954            huanăa          NaN               NaN          NaN
2955            huanăa          NaN               NaN          NaN
2956            huanăa          NaN               NaN          NaN
2959            huanăa          NaN               NaN          NaN
2960            huanăa          NaN               NaN          NaN
2961            huanăa          NaN               NaN          NaN
2963            huanăa          NaN               NaN          NaN
2964            huanăa          NaN               NaN          NaN
2965            huanăa          NaN               NaN        False
2966            huanăa          NaN               NaN          NaN
2967            huanăa          NaN               NaN          NaN

     button_number trial_index time_elapsed     rt
2953             2         140       326901  38051
2954             2         141       329608   2706
2955             3         142       331621   2011
2956             2         143       333873   2252
2959             0         146       347856   4433
2960             2         147       349674   1818
2961             0         148       351959   2284
2963             0         150       356745   1519
2964             3         151       359351   2605
2965             0         152       361133   1781
2966             0         153       363429   2295
2967             2         154       365122   1692

[12 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2969  vfc66vqf8v      fmbg      8       1   critical      mbs  idanuluf
2970  vfc66vqf8v      fmbg      8       1   critical      fbs    awupav
2971  vfc66vqf8v      fmbg      8       1      catch      fbd    awupav
2972  vfc66vqf8v      fmbg      8       1   critical      fzd  idanuluf
2973  vfc66vqf8v      fmbg      8       1   critical      mzd      otev
2974  vfc66vqf8v      fmbg      8       1   critical      fzs  idanuluf
2975  vfc66vqf8v      fmbg      8       1   critical      mbd  idanuluf

     expected  correct  undo  ...  generaliser2_term generaliser3  \
2969     otev        0     0  ...               otev          mbs
2970   awupav        1     0  ...               otev          mbs
2971   awupav        1     0  ...               otev          mbs
2972   awupav        0     0  ...               otev          mbs
2973     otev        1     0  ...               otev          mbs
2974   awupav        0     0  ...               otev          mbs
2975     otev        0     0  ...               otev          mbs

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2969          idanuluf          NaN               NaN          NaN
2970          idanuluf          NaN               NaN          NaN
2971          idanuluf          NaN               NaN        False
2972          idanuluf          fzd          idanuluf          NaN
2973          idanuluf          fzd          idanuluf          NaN
2974          idanuluf          fzd          idanuluf          NaN
2975          idanuluf          fzd          idanuluf          NaN

     button_number trial_index time_elapsed     rt
2969             2         167       407960  31266
2970             1         168       409962   2001
2971             1         169       411218   1255
2972             2         170       413123   1904
2973             3         171       414495   1371
2974             2         172       415802   1306
2975             2         173       417453   1650

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2935  vfc66vqf8v      fmbg      5       2   critical      fbs     nuubö
2936  vfc66vqf8v      fmbg      5       2   critical      mbd   cöahido
2937  vfc66vqf8v      fmbg      5       2      catch      fzd     šïïnö
2938  vfc66vqf8v      fmbg      5       2   critical      mzd     nuubö
2939  vfc66vqf8v      fmbg      5       2   critical      mzs     nuubö
2940  vfc66vqf8v      fmbg      5       2   critical      fzs     šïïnö
2941  vfc66vqf8v      fmbg      5       2   critical      fbd     nuubö

     expected  correct  undo  ...  generaliser2_term generaliser3  \
2935  cöahido        0     0  ...              šïïnö          fbs
2936  cöahido        1     0  ...              šïïnö          fbs
2937    šïïnö        1     0  ...              šïïnö          fbs
2938    šïïnö        0     0  ...              šïïnö          fbs
2939    šïïnö        0     0  ...              šïïnö          fbs
2940    šïïnö        1     0  ...              šïïnö          fbs
2941  cöahido        0     0  ...              šïïnö          fbs

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2935             nuubö          NaN               NaN          NaN
2936             nuubö          NaN               NaN          NaN
2937             nuubö          NaN               NaN        False
2938             nuubö          NaN               NaN          NaN
2939             nuubö          NaN               NaN          NaN
2940             nuubö          NaN               NaN          NaN
2941             nuubö          NaN               NaN          NaN

     button_number trial_index time_elapsed     rt
2935             2         102       241815  31744

       random_id condition  block  system trial_type selectee  selection  \
1316  by11zvzmpo      mfgb      4       5      catch      fzs  powisunge
1317  by11zvzmpo      mfgb      4       5   critical      fbd       luge
1318  by11zvzmpo      mfgb      4       5   critical      fbs  powisunge
1319  by11zvzmpo      mfgb      4       5   critical      mbs  powisunge
1320  by11zvzmpo      mfgb      4       5   critical      mzs  powisunge
1321  by11zvzmpo      mfgb      4       5   critical      fzd       luge
1322  by11zvzmpo      mfgb      4       5   critical      mzd       luge

       expected  correct  undo  ...  generaliser2_term generaliser3  \
1316  powisunge        1     0  ...               luge          NaN
1317       luge        1     0  ...               luge          NaN
1318       luge        0     0  ...               luge          NaN
1319       luge        0     0  ...               luge          NaN
1320       luge        0     0  ...               luge          NaN
1321  powisunge        0     0  ...               luge          NaN
1322       luge        1     0  ...               luge          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1316               NaN          NaN               NaN        False
1317               NaN          NaN               NaN          NaN
1318               NaN          NaN               NaN          NaN
1319               NaN          NaN               NaN          NaN
1320               NaN          NaN               NaN          NaN
1321               NaN          NaN               NaN          NaN
1322               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed    rt
1316             2          83       461228  3022
1317             1          84       462637  1406
1318             2          85       463941  1301
1319             2          86       466222  2278
1320             2          87       467196   972
1321             1          88       468876  1678
1322             1          89       469508   630

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1300  by11zvzmpo      mfgb      2       6   critical      mbd    baumiă
1301  by11zvzmpo      mfgb      2       6      catch      fzs    baumiă
1302  by11zvzmpo      mfgb      2       6   critical      mzd    hyonăo
1303  by11zvzmpo      mfgb      2       6   critical      fbd    hyonăo
1304  by11zvzmpo      mfgb      2       6   critical      fbs    baumiă
1305  by11zvzmpo      mfgb      2       6   critical      mzs    baumiă
1306  by11zvzmpo      mfgb      2       6   critical      fzd    hyonăo

     expected  correct  undo  ...  generaliser2_term generaliser3  \
1300   hyonăo        0     0  ...             baumiă          NaN
1301   baumiă        1     0  ...             baumiă          NaN
1302   baumiă        0     0  ...             baumiă          NaN
1303   baumiă        0     0  ...             baumiă          NaN
1304   baumiă        1     0  ...             baumiă          NaN
1305   baumiă        1     0  ...             baumiă          NaN
1306   baumiă        0     0  ...             baumiă          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1300               NaN          NaN               NaN          NaN
1301               NaN          NaN               NaN        False
1302               NaN          NaN               NaN          NaN
1303               NaN          NaN               NaN          NaN
1304               NaN          NaN               NaN          NaN
1305               NaN          NaN               NaN          NaN
1306               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed     rt
1300             2          45       216883  36640
1301             2          46       221483   4597
1302             3          47       232483  10998
1303             3          48       235675   3190
1304             2          49       236875   1198
1305             2          50       237860    982
1306             3          51       239612   1750

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
1348  by11zvzmpo      mfgb      7       7   critical      mbd    adeçim
1349  by11zvzmpo      mfgb      7       7      catch      mzs  aqinudød
1350  by11zvzmpo      mfgb      7       7   critical      mbs  aqinudød
1351  by11zvzmpo      mfgb      7       7   critical      mzd    adeçim
1352  by11zvzmpo      mfgb      7       7   critical      fbs  aqinudød
1353  by11zvzmpo      mfgb      7       7   critical      fzs  aqinudød
1354  by11zvzmpo      mfgb      7       7   critical      fzd    adeçim

      expected  correct  undo  ...  generaliser2_term generaliser3  \
1348    adeçim        1     0  ...             adeçim          NaN
1349  aqinudød        1     0  ...             adeçim          NaN
1350    adeçim        0     0  ...             adeçim          NaN
1351  aqinudød        0     0  ...             adeçim          NaN
1352    adeçim        0     0  ...             adeçim          NaN
1353    adeçim        0     0  ...             adeçim          NaN
1354    adeçim        1     0  ...             adeçim          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
1348               NaN          NaN               NaN          NaN
1349               NaN          NaN               NaN        False
1350               NaN          NaN               NaN          NaN
1351               NaN          NaN               NaN          NaN
1352               NaN          NaN               NaN          NaN
1353               NaN          NaN               NaN          NaN
1354               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed    rt
1348             0         146       628586  2703
1349             1         147       630474  1886
1350             1         148       631538  1062
1351             0         149       633243  1702
1352             1         150       634393  1148
1353             1         151       635266   871
1354             0         152       636050   781

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2517  wa2j69ws6s      fmbg      5       0   critical      fbd    adeçim
2518  wa2j69ws6s      fmbg      5       0      catch      mzs    adeçim
2519  wa2j69ws6s      fmbg      5       0   critical      mbd    adeçim
2520  wa2j69ws6s      fmbg      5       0   critical      fzs    adeçim
2521  wa2j69ws6s      fmbg      5       0   critical      mbs    adeçim
2522  wa2j69ws6s      fmbg      5       0   critical        b    emøyeç
2523  wa2j69ws6s      fmbg      5       0   critical      mzd    adeçim
2524  wa2j69ws6s      fmbg      5       0   critical      fbs    adeçim
2525  wa2j69ws6s      fmbg      5       0   critical      fzd    adeçim

     expected  correct  undo  ...  generaliser2_term generaliser3  \
2517   adeçim        1     0  ...             emøyeç          NaN
2518   adeçim        1     0  ...             emøyeç          NaN
2519   adeçim        1     0  ...             emøyeç          NaN
2520   adeçim        1     0  ...             emøyeç          NaN
2521   adeçim        1     0  ...             emøyeç          NaN
2522   emøyeç        1     0  ...             emøyeç          NaN
2523   adeçim        1     0  ...             emøyeç          NaN
2524   adeçim        1     0  ...             emøyeç          NaN
2525   adeçim        1     0  ...             emøyeç          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2517               NaN          NaN               NaN          NaN
2518               NaN          NaN               NaN        False
2519               NaN          NaN               NaN          NaN
2520               NaN          NaN               NaN          NaN
2521               NaN          NaN               NaN          NaN
2522               NaN          NaN               NaN          NaN
2523               NaN          NaN               NaN          NaN
2524               NaN          NaN               NaN          NaN
2525               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed    rt
2517             3         100       347053  8106
2518             3         101       348650  1592
2519             3         102       351704  3050
2520             3         103       352917  1207
2521             3         104       353854   932
2522             1         105       357667  3807
2523             3         106       359646  1972
2524             3         107       360977  1324
2525             3         108       363070  2085

[9 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2493  wa2j69ws6s      fmbg      2       1   critical      mzs    morïky
2494  wa2j69ws6s      fmbg      2       1   critical      mzd    morïky
2495  wa2j69ws6s      fmbg      2       1   critical      fzd      bybï
2496  wa2j69ws6s      fmbg      2       1   critical      fbd      bybï
2497  wa2j69ws6s      fmbg      2       1   critical      mbd    morïky
2498  wa2j69ws6s      fmbg      2       1   critical      fbs      bybï
2499  wa2j69ws6s      fmbg      2       1      catch      mbs    morïky

     expected  correct  undo  ...  generaliser2_term generaliser3  \
2493   morïky        1     0  ...             morïky          NaN
2494   morïky        1     0  ...             morïky          NaN
2495     bybï        1     0  ...             morïky          NaN
2496     bybï        1     0  ...             morïky          NaN
2497   morïky        1     0  ...             morïky          NaN
2498     bybï        1     0  ...             morïky          NaN
2499   morïky        1     0  ...             morïky          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2493               NaN          NaN               NaN          NaN
2494               NaN          NaN               NaN          NaN
2495               NaN          NaN               NaN          NaN
2496               NaN          NaN               NaN          NaN
2497               NaN          NaN               NaN          NaN
2498               NaN          NaN               NaN          NaN
2499               NaN          NaN               NaN        False

     button_number trial_index time_elapsed    rt
2493             3          45       206081  7552
2494             3          46       212357  6271
2495             1          47       214568  2202
2496             1          48       216258  1685
2497             3          49       218210  1944
2498             1          50       220049  1833
2499             3          51       225189  5135

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2535  wa2j69ws6s      fmbg      7       2   critical      mbs   sfêvdok
2536  wa2j69ws6s      fmbg      7       2   critical      fbd   sfêvdok
2537  wa2j69ws6s      fmbg      7       2   critical      fzd  kvurddåh
2538  wa2j69ws6s      fmbg      7       2   critical      fzs  kvurddåh
2539  wa2j69ws6s      fmbg      7       2      catch      fbs   sfêvdok
2540  wa2j69ws6s      fmbg      7       2   critical      mzs  kvurddåh
2541  wa2j69ws6s      fmbg      7       2   critical      mbd   sfêvdok

      expected  correct  undo  ...  generaliser2_term generaliser3  \
2535   sfêvdok        1     0  ...           kvurddåh          NaN
2536   sfêvdok        1     0  ...           kvurddåh          NaN
2537  kvurddåh        1     0  ...           kvurddåh          NaN
2538  kvurddåh        1     0  ...           kvurddåh          NaN
2539   sfêvdok        1     0  ...           kvurddåh          NaN
2540  kvurddåh        1     0  ...           kvurddåh          NaN
2541   sfêvdok        1     0  ...           kvurddåh          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2535               NaN          NaN               NaN          NaN
2536               NaN          NaN               NaN          NaN
2537               NaN          NaN               NaN          NaN
2538               NaN          NaN               NaN          NaN
2539               NaN          NaN               NaN        False
2540               NaN          NaN               NaN          NaN
2541               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed    rt
2535             1         140       425424  9543
2536             1         141       427148  1718
2537             3         142       430416  3258
2538             3         143       431342   920
2539             1         144       433410  2063
2540             3         145       434967  1550
2541             1         146       436614  1640

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2509  wa2j69ws6s      fmbg      4       3   critical      mbs       gêă
2510  wa2j69ws6s      fmbg      4       3      catch      fzd    taobyo
2511  wa2j69ws6s      fmbg      4       3   critical      mzd    taobyo
2512  wa2j69ws6s      fmbg      4       3   critical      fzs    taobyo
2513  wa2j69ws6s      fmbg      4       3   critical      mbd       gêă
2514  wa2j69ws6s      fmbg      4       3   critical      mzs    taobyo
2515  wa2j69ws6s      fmbg      4       3   critical      fbs       gêă

     expected  correct  undo  ...  generaliser2_term generaliser3  \
2509   taobyo        0     0  ...                gêă          NaN
2510   taobyo        1     0  ...                gêă          NaN
2511      gêă        0     0  ...                gêă          NaN
2512   taobyo        1     0  ...                gêă          NaN
2513   taobyo        0     0  ...                gêă          NaN
2514      gêă        0     0  ...                gêă          NaN
2515      gêă        1     0  ...                gêă          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2509               NaN          NaN               NaN          NaN
2510               NaN          NaN               NaN        False
2511               NaN          NaN               NaN          NaN
2512               NaN          NaN               NaN          NaN
2513               NaN          NaN               NaN          NaN
2514               NaN          NaN               NaN          NaN
2515               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed    rt
2509             3          83       311459  8934
2510             2          84       314806  3341
2511             2          85       318785  3973
2512             2          86       322109  3318
2513             3          87       324500  2384
2514             2          88       326012  1507
2515             3          89       327405  1386

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2501  wa2j69ws6s      fmbg      3       4   critical      mbd     šïïnö
2502  wa2j69ws6s      fmbg      3       4   critical      mzs     šïïnö
2503  wa2j69ws6s      fmbg      3       4      catch      mbs     šïïnö
2504  wa2j69ws6s      fmbg      3       4   critical      fzd     šïïnö
2505  wa2j69ws6s      fmbg      3       4   critical      mzd     šïïnö
2506  wa2j69ws6s      fmbg      3       4   critical      fzs     šïïnö
2507  wa2j69ws6s      fmbg      3       4   critical      fbs   tuumïhu

     expected  correct  undo  ...  generaliser2_term generaliser3  \
2501    šïïnö        1     0  ...              šïïnö          NaN
2502    šïïnö        1     0  ...              šïïnö          NaN
2503    šïïnö        1     0  ...              šïïnö          NaN
2504    šïïnö        1     0  ...              šïïnö          NaN
2505    šïïnö        1     0  ...              šïïnö          NaN
2506    šïïnö        1     0  ...              šïïnö          NaN
2507  tuumïhu        1     0  ...              šïïnö          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2501               NaN          NaN               NaN          NaN
2502               NaN          NaN               NaN          NaN
2503               NaN          NaN               NaN        False
2504               NaN          NaN               NaN          NaN
2505               NaN          NaN               NaN          NaN
2506               NaN          NaN               NaN          NaN
2507               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed    rt
2501             1          64       270136  4434
2502             1          65       271179  1037
2503             1          66       274065  2879
2504             1          67       277578  3508
2505             1          68       278970  1383
2506             1          69       280356  1381
2507             2          70       281849  1487

[7 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2543  wa2j69ws6s      fmbg      8       5   critical      fbs     žbodu
2545  wa2j69ws6s      fmbg      8       5   critical      fbs     žbodu
2546  wa2j69ws6s      fmbg      8       5   critical      mbs     žbodu
2547  wa2j69ws6s      fmbg      8       5   critical      mbd     žbodu
2548  wa2j69ws6s      fmbg      8       5      catch      mzd     žbodu
2549  wa2j69ws6s      fmbg      8       5   critical      fzs     pžicā
2550  wa2j69ws6s      fmbg      8       5   critical      mzs     žbodu
2551  wa2j69ws6s      fmbg      8       5   critical      fbd     žbodu

     expected  correct  undo  ...  generaliser2_term generaliser3  \
2543    žbodu        1     0  ...              žbodu          NaN
2545    žbodu        1     0  ...              žbodu          NaN
2546    žbodu        1     0  ...              žbodu          NaN
2547    žbodu        1     0  ...              žbodu          NaN
2548    žbodu        1     0  ...              žbodu          NaN
2549    pžicā        1     0  ...              žbodu          NaN
2550    žbodu        1     0  ...              žbodu          NaN
2551    žbodu        1     0  ...              žbodu          NaN

     generaliser3_term generaliser4 generaliser4_term catch_failed  \
2543               NaN          NaN               NaN          NaN
2545               NaN          NaN               NaN          NaN
2546               NaN          NaN               NaN          NaN
2547               NaN          NaN               NaN          NaN
2548               NaN          NaN               NaN        False
2549               NaN          NaN               NaN          NaN
2550               NaN          NaN               NaN          NaN
2551               NaN          NaN               NaN          NaN

     button_number trial_index time_elapsed    rt
2543             0         159       457093  3737
2545             0         161       469135  6914
2546             0         162       472954  3814
2547             0         163       473926   966
2548             0         164       475236  1305
2549             2         165       477277  2034
2550             0         166       480035  2753
2551             0         167       480828   787

[8 rows x 24 columns]
       random_id condition  block  system trial_type selectee selection  \
2527  wa2j69ws6s      fmbg      6       6   critical      fbs  egezalat
2528  wa2j69ws6s      fmbg      6       6   critical      mbd    awupav
2529  wa2j69ws6s      fmbg      6       6      catch      mzs  egezalat
2530  wa2j69ws6s      fmbg      6       6   critical      fzs  egezalat
2531  wa2j69ws6s      fmbg      6       6   critical      fbd  egezalat
2532  wa2j69ws6s      fmbg      6       6   critical      fzd  egezalat

,random_id,condition,block,system,selectee,chosen_term,gen1,gen1_term,gen2,gen2_term,correct
0,1mxy428t9t,mfgb,5,0,z,hyonăo,mbs,goozăi,z,hyonăo,1
1,1mxy428t9t,mfgb,5,0,mbd,goozăi,mbs,goozăi,z,hyonăo,0
2,1mxy428t9t,mfgb,5,0,mzs,goozăi,mbs,goozăi,z,hyonăo,0
3,1mxy428t9t,mfgb,5,0,fzs,goozăi,mbs,goozăi,z,hyonăo,0
4,1mxy428t9t,mfgb,5,0,mzd,goozăi,mbs,goozăi,z,hyonăo,1
...,...,...,...,...,...,...,...,...,...,...,...
2203,wa2j69ws6s,fmbg,1,7,mzs,luge,mzd,lepego,fbd,luge,0
2204,wa2j69ws6s,fmbg,1,7,fzs,luge,mzd,lepego,fbd,luge,1
2205,wa2j69ws6s,fmbg,1,7,fzd,lepego,mzd,lepego,fbd,luge,1
2206,wa2j69ws6s,fmbg,1,7,mbs,luge,mzd,lepego,fbd,luge,1
2207,wa2j69ws6s,fmbg,1,7,mbd,lepego,mzd,lepego,fbd,luge,1

# By-participant baselines and z-scores

Creating a baseline distribution for participant responses - are participants generalising more predictively than we would expect by chance?

Shuffle the participants' responses - break all predictive bonds, but maintain number of terms used and entropy of each term.

In [89]:
def shuffle_ppt_responses(df):
        
    ks = {}
    
    choices = []
    catcher = ""
    
    for i in range(len(df)):
        relative = df['selectee'].values[i] # get the referent for each trial
        
        if df['trial_type'].values[i] == 'catch': # ignore if it's a catch trial
            continue

        else:
            term = df['selection'].values[i] # get the term the participant chose for this referent
            ks[relative] = term # add it to the dict
            
            
    terms = list(ks.values()) # get all the terms the participant used
    
    random.shuffle(terms) # and shuffle them
    
    # then reassign them to referents in this random order
    index = 0
    for i in ks:
        ks[i] = terms[index]
        index += 1
    
    # assign the generalisers to the dict - these don't get shuffled
    generaliser1 = df['generaliser1'].values[0]
    ks[generaliser1] = df['generaliser1_term'].values[0]
    generaliser2 = df['generaliser2'].values[0]
    ks[generaliser2] = df['generaliser2_term'].values[0]

    return ks

Shuffle each participant output a number of times and compare to the true value - save the z-score to a CSV file.

In [90]:
def by_participant_baselines(filename,filename2,times):
    
    data = []
    z_data = []
    
    for ppt_id in random_ids:
        df = get_ppt_df(ppt_id)
        
        try:
            df.empty == False
        except:
            continue
            
        for system in [0,1,2,3,4,5,6,7]:

            system_df = df.drop(df[df.system != system].index)
            
            if system_df.empty:
                continue
                
            else:

                if True in set(system_df['catch_failed']):
                    pass

                else:

                    block = system_df['block'].values[0]
                    indx = system_df[system_df.trial_type == 'catch'].index[0]
                    system_df = system_df.drop(indx)

                    ppt_responses = get_ppt_ks(system_df)
                    true_ks = make_ks(language_types[system],ppt_responses)

                    true_value = predictive_structure(true_ks)

                    sim_values = []

                    for j in range(times):

                        results = {}

                        shuffled_responses = shuffle_ppt_responses(system_df)

                        sim = make_ks(language_types[system],shuffled_responses)

                        ps = predictive_structure(sim)

                        sim_values.append(ps)

                        results['random_id'] = ppt_id
                        results['block'] = block
                        results['system'] = system
                        results['simulated_value'] = ps
                        results['true_value'] = true_value
                        results['data_type'] = 'simulation'

                        for relative in sim:
                            results[relative] = sim[relative]

                        data.append(results)

                    z_results = {}

                    mean = np.mean(sim_values)
                    sd = np.std(sim_values)

                    z_results['random_id'] = ppt_id
                    z_results['block'] = block
                    z_results['system'] = system
                    z_results['true_value'] = true_value
                    z_results['simulated_mean'] = mean
                    z_results['simulated_sd'] = sd
                    z_results['z'] = (true_value - mean) / sd

                    z_data.append(z_results)

        
    pd.DataFrame(data).to_csv('data/' + filename + '.csv',index=False) # save the dataframe
    pd.DataFrame(z_data).to_csv('data/' + filename2 + '.csv',index=False) # save the dataframe


            
    return pd.DataFrame(data)

In [91]:
by_participant_baselines('by_participant_baselines_equal','by_participant_z_equal',1000)

C:\Users\s1604058\AppData\Local\Temp\ipykernel_10212\3986574290.py:74: RuntimeWarning: invalid value encountered in scalar divide
  z_results['z'] = (true_value - mean) / sd
C:\Users\s1604058\AppData\Local\Temp\ipykernel_10212\3986574290.py:74: RuntimeWarning: invalid value encountered in scalar divide
  z_results['z'] = (true_value - mean) / sd
C:\Users\s1604058\AppData\Local\Temp\ipykernel_10212\3986574290.py:74: RuntimeWarning: invalid value encountered in scalar divide
  z_results['z'] = (true_value - mean) / sd
C:\Users\s1604058\AppData\Local\Temp\ipykernel_10212\3986574290.py:74: RuntimeWarning: invalid value encountered in scalar divide
  z_results['z'] = (true_value - mean) / sd
C:\Users\s1604058\AppData\Local\Temp\ipykernel_10212\3986574290.py:74: RuntimeWarning: invalid value encountered in scalar divide
  z_results['z'] = (true_value - mean) / sd

,random_id,block,system,simulated_value,true_value,data_type,mbd,mzs,fzs,mzd,...,fzd,fbs,mbs,z,m,f,mz,mb,fz,fb
0,1mxy428t9t,5,0,1.26827,1.26827,simulation,goozăi,goozăi,goozăi,goozăi,...,goozăi,goozăi,goozăi,hyonăo,0,1,2,2,2,2
1,1mxy428t9t,5,0,1.26827,1.26827,simulation,goozăi,goozăi,goozăi,goozăi,...,goozăi,goozăi,goozăi,hyonăo,0,1,2,2,2,2
2,1mxy428t9t,5,0,1.26827,1.26827,simulation,goozăi,goozăi,goozăi,goozăi,...,goozăi,goozăi,goozăi,hyonăo,0,1,2,2,2,2
3,1mxy428t9t,5,0,1.26827,1.26827,simulation,goozăi,goozăi,goozăi,goozăi,...,goozăi,goozăi,goozăi,hyonăo,0,1,2,2,2,2
4,1mxy428t9t,5,0,1.26827,1.26827,simulation,goozăi,goozăi,goozăi,goozăi,...,goozăi,goozăi,goozăi,hyonăo,0,1,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284995,wa2j69ws6s,1,7,1.48952,1.48952,simulation,luge,luge,luge,lepego,...,lepego,luge,lepego,4,0,1,3,2,2,2
284996,wa2j69ws6s,1,7,1.48952,1.48952,simulation,lepego,luge,lepego,lepego,...,luge,luge,luge,4,0,1,3,2,2,2
284997,wa2j69ws6s,1,7,1.48952,1.48952,simulation,lepego,luge,lepego,lepego,...,luge,luge,luge,4,0,1,3,2,2,2
284998,wa2j69ws6s,1,7,0.88792,1.48952,simulation,lepego,lepego,luge,lepego,...,luge,luge,luge,4,0,1,3,2,2,2
284999,wa2j69ws6s,1,7,0.88792,1.48952,simulation,luge,lepego,lepego,lepego,...,luge,luge,luge,4,0,1,3,2,2,2

# Semantic distance analysis

To generate the heatmap plots in Figure 14, we need to calculate the proportion with which each pair of referents was put into the same category (i.e. participants assigned them the same term).

In [34]:
selectees = ['mbs','mbd','mzs','mzd','fbs','fbd','fzs','fzd','z','b']

In [ ]:
def calculate_distance():
    

    for system in [0,1,2,3,4,5,6,7]:
    
        languages = []
        
        for ppt_id in random_ids:
            df = get_ppt_df(ppt_id)
                    
            # first, get all participant kinship systems
            try:
                if df.empty == False:

                    system_df = df.drop(df[df.system != system].index)

                    if True in set(system_df['catch_failed']):
                        pass
                    else:
                        ppt_responses = get_ppt_ks(system_df)
                        languages.append(ppt_responses)
            except:
                continue
    
            data = []

            # then, for each pair of relatives, score 1 if they were given the same label

            for relative1 in selectees:
                for relative2 in selectees:
                    scores = []
                    for i in range(len(languages)):
                        if relative1 in languages[i] and relative2 in languages[i]:
                            if languages[i][relative1] == languages[i][relative2]:
                                score = 1
                            else:
                                score = 0
                            scores.append(score)
                        else: 
                            continue
                    try:        
                        dist = sum(scores)/len(scores)
                    except:
                        dist = 0

        #             print(sum(scores),len(scores))

                    results = {}
                    results['x'] = relative1
                    results['y'] = relative2
                    results['z'] = dist
                    results['system'] = system
                    results['system_type'] = systems[system]
                    results['system_group'] = system_groups[system]
                    results['gender_distinction'] = gender_distinction

                    data.append(results)
    
    pd.DataFrame(data).to_csv('data/' + str(system) + '_distance.csv',index=False) # save the dataframe
    
    return pd.DataFrame(data)

In [29]:
# calculate_distance(0)

The following builds a dataframe that instantiates what our data would look like in an ideal world, i.e. if participants categorised kin predictively 100% of the time (for the bottom row of Figure 14):

In [32]:
perfect_languages = [[['z','b'],['mzd','mzs','mbd','mbs','fzd','fzs','fbd','fbs']], # Type I
                [['mzd','mzs','mbd','mbs'],['fzd','fzs','fbd','fbs']], # Type II side
                [['mzd','mzs','fzd','fzs'],['mbd','mbs','fbd','fbs']], # Type II gen
                [['mzd','mzs','fbd','fbs'],['mbd','mbs','fzd','fzs']], # Type II opp
                [['mzd','mzs','mbd','mbs','fzd','fzs'],['fbd','fbs']], # Type III fb
                [['mzd','mzs','mbd','mbs','fbd','fbs'],['fzd','fzs']], # Type III fz
                [['mzd','mzs','fzd','fzs','fbd','fbs'],['mbd','mbs']], # Type III mb
                [['mbd','mbs','fzd','fzs','fbd','fbs'],['mzd','mzs']]] # Type III mz

In [35]:
def perfect_distance(perfect_languages,filename):
    
    df = []
    for language in perfect_languages:
        
        for relative1 in selectees:
            for relative2 in selectees:
                data = {}
                if relative1 in language[0] and relative2 in language[0]:
                    data['x'] = relative1
                    data['y'] = relative2
                    data['z'] = 1
                    
                elif relative1 in language[1] and relative2 in language[1]:
                    data['x'] = relative1
                    data['y'] = relative2
                    data['z'] = 1
                else:
                    data['x'] = relative1
                    data['y'] = relative2
                    data['z'] = 0.1
                    
                system = perfect_languages.index(language)
                data['system'] = system
                data['system_type'] = systems[system]
                data['system_group'] = system_groups[system]
                
                df.append(data)
                
#     pd.DataFrame(df).to_csv('data/' + filename + '.csv',index=False) # save the dataframe
    
    return pd.DataFrame(df)

# Gender analysis

Our participants often encode gender. For some exploratory analysis, let's calculate the proportion of gender distinctions made by our participants.

In [37]:
boys = ['mbs','mzs','fbs','fzs','b']
girls = ['mbd','mzd','fbd','fzd','z']

gender_pairs = [['mbs','mbd'],['mzs','mzd'],['fbs','fbd'],['fzs','fzd'],['b','z']]

In [39]:
def gender_distinctions(filename):
    data = []
    
    for ppt_id in random_ids:
        
        df = get_ppt_df(ppt_id)
        
        try:
            df.empty == False
        except:
            continue
        
        for system in [0,1,2,3,4,5,6,7]:

            system_df = df.drop(df[df.system != system].index)

            if True in set(system_df['catch_failed']):
                pass

            else:

                ppt_responses = get_ppt_ks(system_df)
                
                for pair in gender_pairs:
                    results = {}
                    
                    boy = pair[0]
                    girl = pair[1]
                    if boy in ppt_responses and girl in ppt_responses:
                        if ppt_responses[boy] == ppt_responses[girl]:
                            gen = 0
                        else:
                            gen = 1
                
#                 for relative1 in ppt_responses:
#                     for relative2 in ppt_responses:
#                             if relative1 in boys and relative2 in girls:
#                                 if ppt_responses[relative1] == ppt_responses[relative2]:
#                                     gen = 0
#                                 else:
#                                     gen = 1
                        results['random_id'] = system_df['random_id'].values[0]
                        results['condition'] = system_df['condition'].values[0]
                        results['block'] = system_df['block'].values[0]
                        results['system'] = system_df['system'].values[0]
                        results['relative1'] = boy
                        results['relative2'] = girl
                        results['relative1_term'] = ppt_responses[boy]
                        results['relative2_term'] = ppt_responses[girl]
                        results['distinction'] = gen
                            

                        data.append(results)
                    
    pd.DataFrame(data).to_csv('data/' + filename + '.csv',index=False) # save the dataframe
                    
    return pd.DataFrame(data)

In [ ]:
gender_distinctions('gender_distinctions')